image: memoio/mefs-env:go13

stages:
  - golangci-lint
  - compile
  - short-test
  - long-test

variables:
  UPCOUNT: "50"
  NETKEY: "dev"
  ETHENDPOINT: "http://212.64.28.207:8101"
  QETHENDPOINT: "http://39.100.146.165:8101"

before_script:
  - mkdir -p $GOPATH/src/github.com/memoio
  - cd $GOPATH/src/github.com/memoio
  - \cp -rf $CI_PROJECT_DIR $GOPATH/src/github.com/memoio
  - cd $GOPATH/src/github.com/memoio/go-mefs
  - git reset --hard

role-golint:
  stage: golangci-lint
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs/role
    - golangci-lint run --no-config --deadline=60m --disable-all --enable=govet --enable=deadcode --enable=errcheck --enable=gosimple --enable=ineffassign --enable=staticcheck --enable=structcheck --enable=typecheck --enable=unused --enable=varcheck --enable=depguard --enable=gochecknoglobals --enable=goconst --enable=gocritic --enable=gocyclo --enable=gofmt --enable=goimports --enable=golint --enable=gosec --enable=interfacer --enable=maligned --enable=misspell --enable=nakedret --enable=prealloc --enable=scopelint --enable=stylecheck --enable=unconvert --enable=unparam
  tags:
    - "47.92.5.51"
  allow_failure: true
  only:
    - master

bls12-golint:
  stage: golangci-lint
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs/bls12
    - golangci-lint run --no-config --deadline=60m --disable-all --enable=govet --enable=deadcode --enable=errcheck --enable=gosimple --enable=ineffassign --enable=staticcheck --enable=structcheck --enable=typecheck --enable=unused --enable=varcheck --enable=depguard --enable=gochecknoglobals --enable=goconst --enable=gocritic --enable=gocyclo --enable=gofmt --enable=goimports --enable=golint --enable=gosec --enable=interfacer --enable=maligned --enable=misspell --enable=nakedret --enable=prealloc --enable=scopelint --enable=stylecheck --enable=unconvert --enable=unparam
  tags:
    - "47.92.5.51"
  allow_failure: true
  only:
    - master

contracts-golint:
  stage: golangci-lint
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs/contracts
    - golangci-lint run --no-config --deadline=60m --disable-all --enable=govet --enable=deadcode --enable=errcheck --enable=gosimple --enable=ineffassign --enable=staticcheck --enable=structcheck --enable=typecheck --enable=unused --enable=varcheck --enable=depguard --enable=gochecknoglobals --enable=goconst --enable=gocritic --enable=gocyclo --enable=gofmt --enable=goimports --enable=golint --enable=gosec --enable=interfacer --enable=maligned --enable=misspell --enable=nakedret --enable=prealloc --enable=scopelint --enable=stylecheck --enable=unconvert --enable=unparam
  tags:
    - "47.92.5.51"
  allow_failure: true
  only:
    - master

data_format-golint:
  stage: golangci-lint
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs/data-format
    - golangci-lint run --no-config --deadline=60m --disable-all --enable=govet --enable=deadcode --enable=errcheck --enable=gosimple --enable=ineffassign --enable=staticcheck --enable=structcheck --enable=typecheck --enable=unused --enable=varcheck --enable=depguard --enable=gochecknoglobals --enable=goconst --enable=gocritic --enable=gocyclo --enable=gofmt --enable=goimports --enable=golint --enable=gosec --enable=interfacer --enable=maligned --enable=misspell --enable=nakedret --enable=prealloc --enable=scopelint --enable=stylecheck --enable=unconvert --enable=unparam
  tags:
    - "47.92.5.51"
  allow_failure: true
  only:
    - master

utils-golint:
  stage: golangci-lint
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs/utils
    - golangci-lint run --no-config --deadline=60m --disable-all --enable=govet --enable=deadcode --enable=errcheck --enable=gosimple --enable=ineffassign --enable=staticcheck --enable=structcheck --enable=typecheck --enable=unused --enable=varcheck --enable=depguard --enable=gochecknoglobals --enable=goconst --enable=gocritic --enable=gocyclo --enable=gofmt --enable=goimports --enable=golint --enable=gosec --enable=interfacer --enable=maligned --enable=misspell --enable=nakedret --enable=prealloc --enable=scopelint --enable=stylecheck --enable=unconvert --enable=unparam
  tags:
    - "47.92.5.51"
  allow_failure: true
  only:
    - master

mefs-golint:
  stage: golangci-lint
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs/cmd
    - golangci-lint run --no-config --deadline=60m --disable-all --enable=govet --enable=deadcode --enable=errcheck --enable=gosimple --enable=ineffassign --enable=staticcheck --enable=structcheck --enable=typecheck --enable=unused --enable=varcheck --enable=depguard --enable=gochecknoglobals --enable=goconst --enable=gocritic --enable=gocyclo --enable=gofmt --enable=goimports --enable=golint --enable=gosec --enable=interfacer --enable=maligned --enable=misspell --enable=nakedret --enable=prealloc --enable=scopelint --enable=stylecheck --enable=unconvert --enable=unparam
  tags:
    - "47.92.5.51"
  allow_failure: true
  only:
    - master

compile:
  stage: compile
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs
    - GO111MODULE=off make install
  tags:
    - "47.92.5.51"

unit_test:
  stage: short-test
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs
    - sh ./bin/mcl.sh
    - GO111MODULE=off make test
  tags:
    - "47.92.5.51"

role_test:
  stage: short-test
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs
    - echo $ETHENDPOINT
    - sh ./bin/mcl.sh
    - GO111MODULE=off go run test/roleContract/test.go -eth=$ETHENDPOINT -qeth=$QETHENDPOINT
  tags:
    - "47.92.5.51"
  only:
    - schedules

query_test:
  stage: short-test
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs
    - echo $ETHENDPOINT
    - sh ./bin/mcl.sh
    - GO111MODULE=off go run test/query/test.go -eth=$ETHENDPOINT -qeth=$QETHENDPOINT
  tags:
    - "47.92.5.51"
  only:
    - schedules

offer_test:
  stage: short-test
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs
    - echo $ETHENDPOINT
    - sh ./bin/mcl.sh
    - GO111MODULE=off go run test/offer/test.go -eth=$ETHENDPOINT -qeth=$QETHENDPOINT
  tags:
    - "47.92.5.51"
  only:
    - schedules

upkeeping_test:
  stage: short-test
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs
    - echo $ETHENDPOINT
    - sh ./bin/mcl.sh
    - GO111MODULE=off go run test/upkeeping/test.go -eth=$ETHENDPOINT -qeth=$QETHENDPOINT
  tags:
    - "47.92.5.51"
  only:
    - schedules

channel_test:
  stage: short-test
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs
    - echo $ETHENDPOINT
    - sh ./bin/mcl.sh
    - GO111MODULE=off go run test/channel/test.go -eth=$ETHENDPOINT -qeth=$QETHENDPOINT
  tags:
    - "47.92.5.51"
  only:
    - schedules

pos_test:
  stage: short-test
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs
    - echo $ETHENDPOINT
    - sh ./bin/mcl.sh
    - GO111MODULE=off go run test/pos/test.go -eth=$ETHENDPOINT -qeth=$QETHENDPOINT
  tags:
    - "47.92.5.51"
  only:
    - schedules

lfs_test:
  stage: long-test
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs
    - GO111MODULE=off make install
    - cd $GOPATH/src/github.com/memoio/go-mefs/bin
    - chmod 777 lfsTest.sh
    - echo $ETHENDPOINT
    - echo $NETKEY
    - ./lfsTest.sh $ETHENDPOINT $NETKEY
  after_script:
    - cat ~/daemon.stdout
  tags:
    - "47.92.5.51"
  only:
    - schedules

challenge_test:
  stage: long-test
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs
    - GO111MODULE=off make install
    - cd $GOPATH/src/github.com/memoio/go-mefs/bin
    - chmod 777 challengeTest.sh
    - echo $ETHENDPOINT
    - echo $NETKEY
    - ./challengeTest.sh $ETHENDPOINT $NETKEY
  after_script:
    - cat ~/daemon.stdout
    - cat ~/.mefs/logs/info.log
    - cat ~/.mefs/logs/error.log
  tags:
    - "47.92.5.51"
  only:
    - schedules

upload_test:
  stage: long-test
  when: always
  script:
    - cd $GOPATH/src/github.com/memoio/go-mefs
    - GO111MODULE=off make install
    - cd $GOPATH/src/github.com/memoio/go-mefs/bin
    - chmod 777 uploadTest.sh
    - echo $ETHENDPOINT
    - echo $NETKEY
    - echo $UPCOUNT
    - ./uploadTest.sh $ETHENDPOINT $NETKEY $UPCOUNT
  after_script:
    - cat ~/daemon.stdout
    - cat ~/.mefs/logs/info.log
    - cat ~/.mefs/logs/error.log
  tags:
    - "47.92.5.51"
  only:
    - schedules
