package keeper

import ()

// handlePosAdd handles block_meta which is generated by pos
func handlePosAdd() {
	// add provider to upkeeping if it is not in upkeeping
}

// handlePosDelete() handles block_meta deletion
func handlePosDelete() {

}
