// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lfs.proto

package user_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SuperBlock struct {
	Buckets              map[int32]string `protobuf:"bytes,1,rep,name=Buckets,proto3" json:"Buckets,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MetaBackupCount      int32            `protobuf:"varint,2,opt,name=MetaBackupCount,proto3" json:"MetaBackupCount,omitempty"`
	NextBucketID         int32            `protobuf:"varint,3,opt,name=NextBucketID,proto3" json:"NextBucketID,omitempty"`
	MagicNumber          int32            `protobuf:"varint,4,opt,name=MagicNumber,proto3" json:"MagicNumber,omitempty"`
	Version              int32            `protobuf:"varint,5,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SuperBlock) Reset()         { *m = SuperBlock{} }
func (m *SuperBlock) String() string { return proto.CompactTextString(m) }
func (*SuperBlock) ProtoMessage()    {}
func (*SuperBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3f13cde69be66c, []int{0}
}

func (m *SuperBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperBlock.Unmarshal(m, b)
}
func (m *SuperBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperBlock.Marshal(b, m, deterministic)
}
func (m *SuperBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperBlock.Merge(m, src)
}
func (m *SuperBlock) XXX_Size() int {
	return xxx_messageInfo_SuperBlock.Size(m)
}
func (m *SuperBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperBlock.DiscardUnknown(m)
}

var xxx_messageInfo_SuperBlock proto.InternalMessageInfo

func (m *SuperBlock) GetBuckets() map[int32]string {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *SuperBlock) GetMetaBackupCount() int32 {
	if m != nil {
		return m.MetaBackupCount
	}
	return 0
}

func (m *SuperBlock) GetNextBucketID() int32 {
	if m != nil {
		return m.NextBucketID
	}
	return 0
}

func (m *SuperBlock) GetMagicNumber() int32 {
	if m != nil {
		return m.MagicNumber
	}
	return 0
}

func (m *SuperBlock) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type BucketInfo struct {
	BucketName           string   `protobuf:"bytes,1,opt,name=BucketName,proto3" json:"BucketName,omitempty"`
	BucketID             int32    `protobuf:"varint,2,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	Policy               int32    `protobuf:"varint,3,opt,name=Policy,proto3" json:"Policy,omitempty"`
	DataCount            int32    `protobuf:"varint,4,opt,name=DataCount,proto3" json:"DataCount,omitempty"`
	ParityCount          int32    `protobuf:"varint,5,opt,name=ParityCount,proto3" json:"ParityCount,omitempty"`
	CurStripe            int32    `protobuf:"varint,6,opt,name=CurStripe,proto3" json:"CurStripe,omitempty"`
	NextOffset           int32    `protobuf:"varint,7,opt,name=NextOffset,proto3" json:"NextOffset,omitempty"`
	Ctime                string   `protobuf:"bytes,8,opt,name=Ctime,proto3" json:"Ctime,omitempty"`
	LastModified         string   `protobuf:"bytes,9,opt,name=LastModified,proto3" json:"LastModified,omitempty"`
	ObjectsBlockSize     int32    `protobuf:"varint,10,opt,name=ObjectsBlockSize,proto3" json:"ObjectsBlockSize,omitempty"`
	SegmentSize          uint64   `protobuf:"varint,11,opt,name=SegmentSize,proto3" json:"SegmentSize,omitempty"`
	TagFlag              uint64   `protobuf:"varint,12,opt,name=TagFlag,proto3" json:"TagFlag,omitempty"`
	Deletion             bool     `protobuf:"varint,13,opt,name=Deletion,proto3" json:"Deletion,omitempty"`
	Encryption           bool     `protobuf:"varint,14,opt,name=Encryption,proto3" json:"Encryption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketInfo) Reset()         { *m = BucketInfo{} }
func (m *BucketInfo) String() string { return proto.CompactTextString(m) }
func (*BucketInfo) ProtoMessage()    {}
func (*BucketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3f13cde69be66c, []int{1}
}

func (m *BucketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketInfo.Unmarshal(m, b)
}
func (m *BucketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketInfo.Marshal(b, m, deterministic)
}
func (m *BucketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketInfo.Merge(m, src)
}
func (m *BucketInfo) XXX_Size() int {
	return xxx_messageInfo_BucketInfo.Size(m)
}
func (m *BucketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BucketInfo proto.InternalMessageInfo

func (m *BucketInfo) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *BucketInfo) GetBucketID() int32 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *BucketInfo) GetPolicy() int32 {
	if m != nil {
		return m.Policy
	}
	return 0
}

func (m *BucketInfo) GetDataCount() int32 {
	if m != nil {
		return m.DataCount
	}
	return 0
}

func (m *BucketInfo) GetParityCount() int32 {
	if m != nil {
		return m.ParityCount
	}
	return 0
}

func (m *BucketInfo) GetCurStripe() int32 {
	if m != nil {
		return m.CurStripe
	}
	return 0
}

func (m *BucketInfo) GetNextOffset() int32 {
	if m != nil {
		return m.NextOffset
	}
	return 0
}

func (m *BucketInfo) GetCtime() string {
	if m != nil {
		return m.Ctime
	}
	return ""
}

func (m *BucketInfo) GetLastModified() string {
	if m != nil {
		return m.LastModified
	}
	return ""
}

func (m *BucketInfo) GetObjectsBlockSize() int32 {
	if m != nil {
		return m.ObjectsBlockSize
	}
	return 0
}

func (m *BucketInfo) GetSegmentSize() uint64 {
	if m != nil {
		return m.SegmentSize
	}
	return 0
}

func (m *BucketInfo) GetTagFlag() uint64 {
	if m != nil {
		return m.TagFlag
	}
	return 0
}

func (m *BucketInfo) GetDeletion() bool {
	if m != nil {
		return m.Deletion
	}
	return false
}

func (m *BucketInfo) GetEncryption() bool {
	if m != nil {
		return m.Encryption
	}
	return false
}

type ObjectInfo struct {
	ObjectName           string            `protobuf:"bytes,1,opt,name=ObjectName,proto3" json:"ObjectName,omitempty"`
	ObjectSize           int32             `protobuf:"varint,2,opt,name=ObjectSize,proto3" json:"ObjectSize,omitempty"`
	ContentType          string            `protobuf:"bytes,3,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	ETag                 string            `protobuf:"bytes,4,opt,name=ETag,proto3" json:"ETag,omitempty"`
	BucketID             int32             `protobuf:"varint,5,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,6,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StripeStart          int32             `protobuf:"varint,7,opt,name=StripeStart,proto3" json:"StripeStart,omitempty"`
	OffsetStart          int32             `protobuf:"varint,8,opt,name=offsetStart,proto3" json:"offsetStart,omitempty"`
	Ctime                string            `protobuf:"bytes,9,opt,name=Ctime,proto3" json:"Ctime,omitempty"`
	Deletion             bool              `protobuf:"varint,10,opt,name=Deletion,proto3" json:"Deletion,omitempty"`
	Dir                  bool              `protobuf:"varint,11,opt,name=Dir,proto3" json:"Dir,omitempty"`
	NextPart             string            `protobuf:"bytes,12,opt,name=NextPart,proto3" json:"NextPart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ObjectInfo) Reset()         { *m = ObjectInfo{} }
func (m *ObjectInfo) String() string { return proto.CompactTextString(m) }
func (*ObjectInfo) ProtoMessage()    {}
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3f13cde69be66c, []int{2}
}

func (m *ObjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectInfo.Unmarshal(m, b)
}
func (m *ObjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectInfo.Marshal(b, m, deterministic)
}
func (m *ObjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectInfo.Merge(m, src)
}
func (m *ObjectInfo) XXX_Size() int {
	return xxx_messageInfo_ObjectInfo.Size(m)
}
func (m *ObjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectInfo proto.InternalMessageInfo

func (m *ObjectInfo) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

func (m *ObjectInfo) GetObjectSize() int32 {
	if m != nil {
		return m.ObjectSize
	}
	return 0
}

func (m *ObjectInfo) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *ObjectInfo) GetETag() string {
	if m != nil {
		return m.ETag
	}
	return ""
}

func (m *ObjectInfo) GetBucketID() int32 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *ObjectInfo) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ObjectInfo) GetStripeStart() int32 {
	if m != nil {
		return m.StripeStart
	}
	return 0
}

func (m *ObjectInfo) GetOffsetStart() int32 {
	if m != nil {
		return m.OffsetStart
	}
	return 0
}

func (m *ObjectInfo) GetCtime() string {
	if m != nil {
		return m.Ctime
	}
	return ""
}

func (m *ObjectInfo) GetDeletion() bool {
	if m != nil {
		return m.Deletion
	}
	return false
}

func (m *ObjectInfo) GetDir() bool {
	if m != nil {
		return m.Dir
	}
	return false
}

func (m *ObjectInfo) GetNextPart() string {
	if m != nil {
		return m.NextPart
	}
	return ""
}

type SignForChannel struct {
	Sig                  []byte   `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	UserPK               []byte   `protobuf:"bytes,2,opt,name=UserPK,proto3" json:"UserPK,omitempty"`
	UserAddress          string   `protobuf:"bytes,3,opt,name=UserAddress,proto3" json:"UserAddress,omitempty"`
	ProviderAddress      string   `protobuf:"bytes,4,opt,name=ProviderAddress,proto3" json:"ProviderAddress,omitempty"`
	Money                []byte   `protobuf:"bytes,5,opt,name=Money,proto3" json:"Money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignForChannel) Reset()         { *m = SignForChannel{} }
func (m *SignForChannel) String() string { return proto.CompactTextString(m) }
func (*SignForChannel) ProtoMessage()    {}
func (*SignForChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3f13cde69be66c, []int{3}
}

func (m *SignForChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignForChannel.Unmarshal(m, b)
}
func (m *SignForChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignForChannel.Marshal(b, m, deterministic)
}
func (m *SignForChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignForChannel.Merge(m, src)
}
func (m *SignForChannel) XXX_Size() int {
	return xxx_messageInfo_SignForChannel.Size(m)
}
func (m *SignForChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_SignForChannel.DiscardUnknown(m)
}

var xxx_messageInfo_SignForChannel proto.InternalMessageInfo

func (m *SignForChannel) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *SignForChannel) GetUserPK() []byte {
	if m != nil {
		return m.UserPK
	}
	return nil
}

func (m *SignForChannel) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *SignForChannel) GetProviderAddress() string {
	if m != nil {
		return m.ProviderAddress
	}
	return ""
}

func (m *SignForChannel) GetMoney() []byte {
	if m != nil {
		return m.Money
	}
	return nil
}

func init() {
	proto.RegisterType((*SuperBlock)(nil), "user.pb.SuperBlock")
	proto.RegisterMapType((map[int32]string)(nil), "user.pb.SuperBlock.BucketsEntry")
	proto.RegisterType((*BucketInfo)(nil), "user.pb.BucketInfo")
	proto.RegisterType((*ObjectInfo)(nil), "user.pb.ObjectInfo")
	proto.RegisterMapType((map[string]string)(nil), "user.pb.ObjectInfo.MetadataEntry")
	proto.RegisterType((*SignForChannel)(nil), "user.pb.SignForChannel")
}

func init() { proto.RegisterFile("lfs.proto", fileDescriptor_9a3f13cde69be66c) }

var fileDescriptor_9a3f13cde69be66c = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x95, 0x9b, 0xe6, 0x8f, 0xb7, 0x6e, 0x7f, 0xd5, 0xea, 0x27, 0xb4, 0xaa, 0x10, 0x0a, 0x39,
	0x45, 0x1c, 0x72, 0x80, 0x0b, 0x2a, 0xe2, 0x40, 0x93, 0x56, 0x42, 0x90, 0x36, 0xb2, 0x03, 0xf7,
	0x8d, 0x33, 0x31, 0x26, 0x8e, 0x6d, 0xad, 0xd7, 0x15, 0xe6, 0x43, 0xf0, 0x09, 0xf8, 0x28, 0x88,
	0xcf, 0x86, 0x66, 0x36, 0xb6, 0x37, 0xe1, 0xc0, 0x6d, 0xdf, 0x9b, 0x37, 0xce, 0xbc, 0x7d, 0x3b,
	0x61, 0x6e, 0xb2, 0x29, 0x26, 0xb9, 0xca, 0x74, 0xc6, 0xfb, 0x65, 0x01, 0x6a, 0x92, 0xaf, 0x46,
	0x3f, 0x4e, 0x18, 0x0b, 0xca, 0x1c, 0xd4, 0x4d, 0x92, 0x85, 0x5b, 0x7e, 0xcd, 0xfa, 0x37, 0x65,
	0xb8, 0x05, 0x5d, 0x08, 0x67, 0xd8, 0x19, 0x9f, 0xbd, 0x1c, 0x4e, 0xf6, 0xca, 0x49, 0xab, 0x9a,
	0xec, 0x25, 0xb7, 0xa9, 0x56, 0x95, 0x5f, 0x37, 0xf0, 0x31, 0xfb, 0x6f, 0x0e, 0x5a, 0xde, 0xc8,
	0x70, 0x5b, 0xe6, 0xd3, 0xac, 0x4c, 0xb5, 0x38, 0x19, 0x3a, 0xe3, 0xae, 0x7f, 0x4c, 0xf3, 0x11,
	0xf3, 0xee, 0xe1, 0x9b, 0x36, 0x8d, 0xef, 0x67, 0xa2, 0x43, 0xb2, 0x03, 0x8e, 0x0f, 0xd9, 0xd9,
	0x5c, 0x46, 0x71, 0x78, 0x5f, 0xee, 0x56, 0xa0, 0xc4, 0x29, 0x49, 0x6c, 0x8a, 0x0b, 0xd6, 0xff,
	0x0c, 0xaa, 0x88, 0xb3, 0x54, 0x74, 0xa9, 0x5a, 0xc3, 0xab, 0x6b, 0xe6, 0xd9, 0x23, 0xf2, 0x4b,
	0xd6, 0xd9, 0x42, 0x25, 0x1c, 0x52, 0xe1, 0x91, 0xff, 0xcf, 0xba, 0x8f, 0x32, 0x29, 0x81, 0x26,
	0x74, 0x7d, 0x03, 0xae, 0x4f, 0x5e, 0x3b, 0xa3, 0x5f, 0x1d, 0xc6, 0xf6, 0x43, 0xa4, 0x9b, 0x8c,
	0x3f, 0xab, 0xd1, 0xbd, 0xdc, 0x01, 0x7d, 0xc1, 0xf5, 0x2d, 0x86, 0x5f, 0xb1, 0x41, 0x63, 0xc3,
	0xb8, 0x6d, 0x30, 0x7f, 0xc2, 0x7a, 0x8b, 0x2c, 0x89, 0xc3, 0x6a, 0x6f, 0x70, 0x8f, 0xf8, 0x53,
	0xe6, 0xce, 0xa4, 0x96, 0xe6, 0x8a, 0x8c, 0xb1, 0x96, 0x40, 0xe3, 0x0b, 0xa9, 0x62, 0x5d, 0x99,
	0xba, 0xb1, 0x66, 0x53, 0xd8, 0x3f, 0x2d, 0x55, 0xa0, 0x55, 0x9c, 0x83, 0xe8, 0x99, 0xfe, 0x86,
	0xc0, 0x89, 0xf1, 0x22, 0x1f, 0x36, 0x9b, 0x02, 0xb4, 0xe8, 0x53, 0xd9, 0x62, 0xd0, 0xfa, 0x54,
	0xc7, 0x3b, 0x10, 0x03, 0x63, 0x9d, 0x00, 0x46, 0xf2, 0x51, 0x16, 0x7a, 0x9e, 0xad, 0xe3, 0x4d,
	0x0c, 0x6b, 0xe1, 0x52, 0xf1, 0x80, 0xe3, 0x2f, 0xd8, 0xe5, 0xc3, 0xea, 0x2b, 0x84, 0xba, 0xa0,
	0x67, 0x10, 0xc4, 0xdf, 0x41, 0x30, 0xfa, 0xfe, 0x5f, 0x3c, 0xba, 0x08, 0x20, 0xda, 0x41, 0xaa,
	0x49, 0x76, 0x36, 0x74, 0xc6, 0xa7, 0xbe, 0x4d, 0x61, 0x7c, 0x4b, 0x19, 0xdd, 0x25, 0x32, 0x12,
	0x1e, 0x55, 0x6b, 0x88, 0x77, 0x3a, 0x83, 0x04, 0x34, 0x26, 0x7b, 0x3e, 0x74, 0xc6, 0x03, 0xbf,
	0xc1, 0xe8, 0xee, 0x36, 0x0d, 0x55, 0x95, 0x53, 0xf5, 0x82, 0xaa, 0x16, 0x33, 0xfa, 0xdd, 0x61,
	0xcc, 0x0c, 0x53, 0xc7, 0x67, 0x90, 0x1d, 0x5f, 0xcb, 0xb4, 0x75, 0x9a, 0xd2, 0x04, 0x68, 0x31,
	0x68, 0x63, 0x9a, 0xa5, 0x1a, 0x52, 0xbd, 0xac, 0x72, 0xa0, 0x1c, 0x5d, 0xdf, 0xa6, 0x38, 0x67,
	0xa7, 0xb7, 0x4b, 0x19, 0x51, 0x8e, 0xae, 0x4f, 0xe7, 0x83, 0x47, 0xd1, 0x3d, 0x7a, 0x14, 0x6f,
	0xd9, 0x00, 0xd7, 0x61, 0x2d, 0xb5, 0x14, 0x3d, 0x5a, 0xb1, 0xe7, 0xcd, 0x8a, 0xb5, 0x83, 0x4f,
	0x6a, 0x8d, 0xd9, 0xb1, 0xa6, 0x85, 0xee, 0x95, 0x72, 0x0e, 0xb4, 0x54, 0x75, 0xbc, 0x36, 0x85,
	0x8a, 0x8c, 0x92, 0x36, 0x8a, 0x81, 0x51, 0x58, 0x54, 0xfb, 0x02, 0x5c, 0xfb, 0x05, 0xd8, 0xb7,
	0xce, 0x8e, 0x6e, 0xfd, 0x92, 0x75, 0x66, 0xb1, 0xa2, 0x14, 0x07, 0x3e, 0x1e, 0x51, 0x8d, 0x6f,
	0x6a, 0x81, 0x3f, 0xe1, 0xd1, 0x67, 0x1a, 0x7c, 0xf5, 0x86, 0x9d, 0x1f, 0x8c, 0x6f, 0xef, 0x9f,
	0xfb, 0xaf, 0xfd, 0xfb, 0xe9, 0xb0, 0x8b, 0x20, 0x8e, 0xd2, 0xbb, 0x4c, 0x4d, 0xbf, 0xc8, 0x34,
	0x85, 0x04, 0xdb, 0x83, 0x38, 0xa2, 0x76, 0xcf, 0xc7, 0x23, 0x6e, 0xd6, 0xa7, 0x02, 0xd4, 0xe2,
	0x03, 0xf5, 0x7b, 0xfe, 0x1e, 0xa1, 0x77, 0x3c, 0xbd, 0x5b, 0xaf, 0x15, 0x14, 0x45, 0x1d, 0x97,
	0x45, 0xe1, 0x9f, 0xd4, 0x42, 0x65, 0x8f, 0xf1, 0xba, 0x55, 0x99, 0xe4, 0x8e, 0x69, 0x1c, 0x71,
	0x9e, 0xa5, 0x50, 0x51, 0x82, 0x9e, 0x6f, 0xc0, 0xaa, 0x47, 0xff, 0x9f, 0xaf, 0xfe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x77, 0xf1, 0x2d, 0x9b, 0x4c, 0x05, 0x00, 0x00,
}
