// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lfs.proto

package user_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SuperBlockInfo struct {
	BucketsSet           []uint64 `protobuf:"varint,1,rep,packed,name=BucketsSet,proto3" json:"BucketsSet,omitempty"`
	MetaBackupCount      int32    `protobuf:"varint,2,opt,name=MetaBackupCount,proto3" json:"MetaBackupCount,omitempty"`
	NextBucketID         int32    `protobuf:"varint,3,opt,name=NextBucketID,proto3" json:"NextBucketID,omitempty"`
	MagicNumber          int32    `protobuf:"varint,4,opt,name=MagicNumber,proto3" json:"MagicNumber,omitempty"`
	Version              int32    `protobuf:"varint,5,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuperBlockInfo) Reset()         { *m = SuperBlockInfo{} }
func (m *SuperBlockInfo) String() string { return proto.CompactTextString(m) }
func (*SuperBlockInfo) ProtoMessage()    {}
func (*SuperBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3f13cde69be66c, []int{0}
}

func (m *SuperBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperBlockInfo.Unmarshal(m, b)
}
func (m *SuperBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperBlockInfo.Marshal(b, m, deterministic)
}
func (m *SuperBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperBlockInfo.Merge(m, src)
}
func (m *SuperBlockInfo) XXX_Size() int {
	return xxx_messageInfo_SuperBlockInfo.Size(m)
}
func (m *SuperBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SuperBlockInfo proto.InternalMessageInfo

func (m *SuperBlockInfo) GetBucketsSet() []uint64 {
	if m != nil {
		return m.BucketsSet
	}
	return nil
}

func (m *SuperBlockInfo) GetMetaBackupCount() int32 {
	if m != nil {
		return m.MetaBackupCount
	}
	return 0
}

func (m *SuperBlockInfo) GetNextBucketID() int32 {
	if m != nil {
		return m.NextBucketID
	}
	return 0
}

func (m *SuperBlockInfo) GetMagicNumber() int32 {
	if m != nil {
		return m.MagicNumber
	}
	return 0
}

func (m *SuperBlockInfo) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type BucketInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	BucketID             int32    `protobuf:"varint,2,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	Policy               int32    `protobuf:"varint,3,opt,name=Policy,proto3" json:"Policy,omitempty"`
	DataCount            int32    `protobuf:"varint,4,opt,name=DataCount,proto3" json:"DataCount,omitempty"`
	ParityCount          int32    `protobuf:"varint,5,opt,name=ParityCount,proto3" json:"ParityCount,omitempty"`
	CurStripe            int64    `protobuf:"varint,6,opt,name=CurStripe,proto3" json:"CurStripe,omitempty"`
	NextOffset           int64    `protobuf:"varint,7,opt,name=NextOffset,proto3" json:"NextOffset,omitempty"`
	ObjectsBlockSize     int64    `protobuf:"varint,8,opt,name=ObjectsBlockSize,proto3" json:"ObjectsBlockSize,omitempty"`
	SegmentSize          uint64   `protobuf:"varint,9,opt,name=SegmentSize,proto3" json:"SegmentSize,omitempty"`
	TagFlag              uint64   `protobuf:"varint,10,opt,name=TagFlag,proto3" json:"TagFlag,omitempty"`
	Ctime                string   `protobuf:"bytes,11,opt,name=Ctime,proto3" json:"Ctime,omitempty"`
	LastModified         string   `protobuf:"bytes,12,opt,name=LastModified,proto3" json:"LastModified,omitempty"`
	Deletion             bool     `protobuf:"varint,13,opt,name=Deletion,proto3" json:"Deletion,omitempty"`
	Encryption           bool     `protobuf:"varint,14,opt,name=Encryption,proto3" json:"Encryption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketInfo) Reset()         { *m = BucketInfo{} }
func (m *BucketInfo) String() string { return proto.CompactTextString(m) }
func (*BucketInfo) ProtoMessage()    {}
func (*BucketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3f13cde69be66c, []int{1}
}

func (m *BucketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketInfo.Unmarshal(m, b)
}
func (m *BucketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketInfo.Marshal(b, m, deterministic)
}
func (m *BucketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketInfo.Merge(m, src)
}
func (m *BucketInfo) XXX_Size() int {
	return xxx_messageInfo_BucketInfo.Size(m)
}
func (m *BucketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BucketInfo proto.InternalMessageInfo

func (m *BucketInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BucketInfo) GetBucketID() int32 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *BucketInfo) GetPolicy() int32 {
	if m != nil {
		return m.Policy
	}
	return 0
}

func (m *BucketInfo) GetDataCount() int32 {
	if m != nil {
		return m.DataCount
	}
	return 0
}

func (m *BucketInfo) GetParityCount() int32 {
	if m != nil {
		return m.ParityCount
	}
	return 0
}

func (m *BucketInfo) GetCurStripe() int64 {
	if m != nil {
		return m.CurStripe
	}
	return 0
}

func (m *BucketInfo) GetNextOffset() int64 {
	if m != nil {
		return m.NextOffset
	}
	return 0
}

func (m *BucketInfo) GetObjectsBlockSize() int64 {
	if m != nil {
		return m.ObjectsBlockSize
	}
	return 0
}

func (m *BucketInfo) GetSegmentSize() uint64 {
	if m != nil {
		return m.SegmentSize
	}
	return 0
}

func (m *BucketInfo) GetTagFlag() uint64 {
	if m != nil {
		return m.TagFlag
	}
	return 0
}

func (m *BucketInfo) GetCtime() string {
	if m != nil {
		return m.Ctime
	}
	return ""
}

func (m *BucketInfo) GetLastModified() string {
	if m != nil {
		return m.LastModified
	}
	return ""
}

func (m *BucketInfo) GetDeletion() bool {
	if m != nil {
		return m.Deletion
	}
	return false
}

func (m *BucketInfo) GetEncryption() bool {
	if m != nil {
		return m.Encryption
	}
	return false
}

type ObjectInfo struct {
	Name                 string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	BucketID             int32             `protobuf:"varint,2,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	Size                 int64             `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	StripeStart          int64             `protobuf:"varint,4,opt,name=StripeStart,proto3" json:"StripeStart,omitempty"`
	OffsetStart          int64             `protobuf:"varint,5,opt,name=offsetStart,proto3" json:"offsetStart,omitempty"`
	Ctime                string            `protobuf:"bytes,6,opt,name=Ctime,proto3" json:"Ctime,omitempty"`
	ContentType          string            `protobuf:"bytes,7,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	ETag                 string            `protobuf:"bytes,8,opt,name=ETag,proto3" json:"ETag,omitempty"`
	Deletion             bool              `protobuf:"varint,9,opt,name=Deletion,proto3" json:"Deletion,omitempty"`
	Dir                  bool              `protobuf:"varint,10,opt,name=Dir,proto3" json:"Dir,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,11,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NextPart             string            `protobuf:"bytes,12,opt,name=NextPart,proto3" json:"NextPart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ObjectInfo) Reset()         { *m = ObjectInfo{} }
func (m *ObjectInfo) String() string { return proto.CompactTextString(m) }
func (*ObjectInfo) ProtoMessage()    {}
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3f13cde69be66c, []int{2}
}

func (m *ObjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectInfo.Unmarshal(m, b)
}
func (m *ObjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectInfo.Marshal(b, m, deterministic)
}
func (m *ObjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectInfo.Merge(m, src)
}
func (m *ObjectInfo) XXX_Size() int {
	return xxx_messageInfo_ObjectInfo.Size(m)
}
func (m *ObjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectInfo proto.InternalMessageInfo

func (m *ObjectInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectInfo) GetBucketID() int32 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *ObjectInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ObjectInfo) GetStripeStart() int64 {
	if m != nil {
		return m.StripeStart
	}
	return 0
}

func (m *ObjectInfo) GetOffsetStart() int64 {
	if m != nil {
		return m.OffsetStart
	}
	return 0
}

func (m *ObjectInfo) GetCtime() string {
	if m != nil {
		return m.Ctime
	}
	return ""
}

func (m *ObjectInfo) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *ObjectInfo) GetETag() string {
	if m != nil {
		return m.ETag
	}
	return ""
}

func (m *ObjectInfo) GetDeletion() bool {
	if m != nil {
		return m.Deletion
	}
	return false
}

func (m *ObjectInfo) GetDir() bool {
	if m != nil {
		return m.Dir
	}
	return false
}

func (m *ObjectInfo) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ObjectInfo) GetNextPart() string {
	if m != nil {
		return m.NextPart
	}
	return ""
}

type SignForChannel struct {
	Sig                  []byte   `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	UserPK               []byte   `protobuf:"bytes,2,opt,name=UserPK,proto3" json:"UserPK,omitempty"`
	UserAddress          string   `protobuf:"bytes,3,opt,name=UserAddress,proto3" json:"UserAddress,omitempty"`
	ProviderAddress      string   `protobuf:"bytes,4,opt,name=ProviderAddress,proto3" json:"ProviderAddress,omitempty"`
	Money                []byte   `protobuf:"bytes,5,opt,name=Money,proto3" json:"Money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignForChannel) Reset()         { *m = SignForChannel{} }
func (m *SignForChannel) String() string { return proto.CompactTextString(m) }
func (*SignForChannel) ProtoMessage()    {}
func (*SignForChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3f13cde69be66c, []int{3}
}

func (m *SignForChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignForChannel.Unmarshal(m, b)
}
func (m *SignForChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignForChannel.Marshal(b, m, deterministic)
}
func (m *SignForChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignForChannel.Merge(m, src)
}
func (m *SignForChannel) XXX_Size() int {
	return xxx_messageInfo_SignForChannel.Size(m)
}
func (m *SignForChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_SignForChannel.DiscardUnknown(m)
}

var xxx_messageInfo_SignForChannel proto.InternalMessageInfo

func (m *SignForChannel) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *SignForChannel) GetUserPK() []byte {
	if m != nil {
		return m.UserPK
	}
	return nil
}

func (m *SignForChannel) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *SignForChannel) GetProviderAddress() string {
	if m != nil {
		return m.ProviderAddress
	}
	return ""
}

func (m *SignForChannel) GetMoney() []byte {
	if m != nil {
		return m.Money
	}
	return nil
}

func init() {
	proto.RegisterType((*SuperBlockInfo)(nil), "user.pb.SuperBlockInfo")
	proto.RegisterType((*BucketInfo)(nil), "user.pb.BucketInfo")
	proto.RegisterType((*ObjectInfo)(nil), "user.pb.ObjectInfo")
	proto.RegisterMapType((map[string]string)(nil), "user.pb.ObjectInfo.MetadataEntry")
	proto.RegisterType((*SignForChannel)(nil), "user.pb.SignForChannel")
}

func init() { proto.RegisterFile("lfs.proto", fileDescriptor_9a3f13cde69be66c) }

var fileDescriptor_9a3f13cde69be66c = []byte{
	// 611 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x95, 0x6b, 0x27, 0x8d, 0x37, 0x69, 0x7f, 0xd5, 0xea, 0x27, 0xb4, 0xaa, 0x10, 0x32, 0x39,
	0x59, 0x1c, 0x72, 0x80, 0x0b, 0x02, 0x71, 0xa0, 0x49, 0x2b, 0x55, 0x90, 0x36, 0x5a, 0x17, 0xee,
	0x1b, 0x67, 0x62, 0x4c, 0x1c, 0xdb, 0x5a, 0xaf, 0x2b, 0xcc, 0x67, 0xe1, 0xcc, 0x99, 0x33, 0x9f,
	0x0e, 0xcd, 0x6c, 0xfe, 0x38, 0xe1, 0xc6, 0x6d, 0xe6, 0xcd, 0x1b, 0xf9, 0xcd, 0x7b, 0xb6, 0x99,
	0x9f, 0x2d, 0xab, 0x51, 0xa9, 0x0b, 0x53, 0xf0, 0xd3, 0xba, 0x02, 0x3d, 0x2a, 0xe7, 0xc3, 0xdf,
	0x0e, 0x3b, 0x8f, 0xea, 0x12, 0xf4, 0x55, 0x56, 0xc4, 0xab, 0xdb, 0x7c, 0x59, 0xf0, 0x67, 0x8c,
	0x5d, 0xd5, 0xf1, 0x0a, 0x4c, 0x15, 0x81, 0x11, 0x4e, 0xe0, 0x86, 0x9e, 0x6c, 0x21, 0x3c, 0x64,
	0xff, 0x4d, 0xc1, 0xa8, 0x2b, 0x15, 0xaf, 0xea, 0x72, 0x5c, 0xd4, 0xb9, 0x11, 0x27, 0x81, 0x13,
	0x76, 0xe4, 0x31, 0xcc, 0x87, 0x6c, 0x70, 0x07, 0xdf, 0x8c, 0xdd, 0xbd, 0x9d, 0x08, 0x97, 0x68,
	0x07, 0x18, 0x0f, 0x58, 0x7f, 0xaa, 0x92, 0x34, 0xbe, 0xab, 0xd7, 0x73, 0xd0, 0xc2, 0x23, 0x4a,
	0x1b, 0xe2, 0x82, 0x9d, 0x7e, 0x06, 0x5d, 0xa5, 0x45, 0x2e, 0x3a, 0x34, 0xdd, 0xb6, 0xc3, 0x5f,
	0xee, 0x56, 0x2a, 0x09, 0xe7, 0xcc, 0xbb, 0x53, 0x6b, 0x10, 0x4e, 0xe0, 0x84, 0xbe, 0xa4, 0x9a,
	0x5f, 0xb2, 0xde, 0xee, 0xf1, 0x56, 0xe5, 0xae, 0xe7, 0x4f, 0x58, 0x77, 0x56, 0x64, 0x69, 0xdc,
	0x6c, 0x84, 0x6d, 0x3a, 0xfe, 0x94, 0xf9, 0x13, 0x65, 0x94, 0x3d, 0xcd, 0x0a, 0xda, 0x03, 0x28,
	0x78, 0xa6, 0x74, 0x6a, 0x1a, 0x3b, 0xb7, 0x92, 0xda, 0x10, 0xee, 0x8f, 0x6b, 0x1d, 0x19, 0x9d,
	0x96, 0x20, 0xba, 0x81, 0x13, 0xba, 0x72, 0x0f, 0xa0, 0xbd, 0x68, 0xc0, 0xfd, 0x72, 0x59, 0x81,
	0x11, 0xa7, 0x34, 0x6e, 0x21, 0xfc, 0x05, 0xbb, 0xb8, 0x9f, 0x7f, 0x85, 0xd8, 0x54, 0x14, 0x49,
	0x94, 0x7e, 0x07, 0xd1, 0x23, 0xd6, 0x5f, 0x38, 0x6a, 0x89, 0x20, 0x59, 0x43, 0x6e, 0x88, 0xe6,
	0x07, 0x4e, 0xe8, 0xc9, 0x36, 0x84, 0xe6, 0x3d, 0xa8, 0xe4, 0x26, 0x53, 0x89, 0x60, 0x34, 0xdd,
	0xb6, 0xfc, 0x7f, 0xd6, 0x19, 0x9b, 0x74, 0x0d, 0xa2, 0x4f, 0x76, 0xd9, 0x06, 0x23, 0xfb, 0xa8,
	0x2a, 0x33, 0x2d, 0x16, 0xe9, 0x32, 0x85, 0x85, 0x18, 0xd0, 0xf0, 0x00, 0x43, 0x4f, 0x27, 0x90,
	0x81, 0xc1, 0x44, 0xce, 0x02, 0x27, 0xec, 0xc9, 0x5d, 0x8f, 0xd7, 0x5d, 0xe7, 0xb1, 0x6e, 0x4a,
	0x9a, 0x9e, 0xd3, 0xb4, 0x85, 0x0c, 0x7f, 0xba, 0x8c, 0xd9, 0x33, 0xfe, 0x29, 0x32, 0xce, 0x3c,
	0xba, 0xd4, 0x25, 0x43, 0xbc, 0x9d, 0x09, 0x64, 0x6d, 0x64, 0x94, 0xb6, 0x81, 0xb9, 0xb2, 0x0d,
	0x21, 0xa3, 0x20, 0x73, 0x2d, 0xa3, 0x63, 0x19, 0x2d, 0x68, 0x6f, 0x46, 0xb7, 0x6d, 0x46, 0xc0,
	0xfa, 0xe3, 0x22, 0x37, 0x90, 0x9b, 0x87, 0xa6, 0x04, 0xca, 0xca, 0x97, 0x6d, 0x08, 0xf5, 0x5c,
	0x3f, 0xa8, 0x84, 0x02, 0xf2, 0x25, 0xd5, 0x07, 0xf6, 0xf8, 0x47, 0xf6, 0x5c, 0x30, 0x77, 0x92,
	0x6a, 0x8a, 0xa2, 0x27, 0xb1, 0xe4, 0xef, 0x58, 0x0f, 0x3f, 0x9b, 0x85, 0x32, 0x4a, 0xf4, 0x03,
	0x37, 0xec, 0xbf, 0x7c, 0x3e, 0xda, 0x7c, 0x9c, 0xa3, 0xbd, 0x51, 0xa3, 0x2d, 0xe7, 0x3a, 0x37,
	0xba, 0x91, 0xbb, 0x15, 0x7c, 0x18, 0xbe, 0x3b, 0x33, 0xbc, 0xcb, 0x66, 0xb5, 0xeb, 0x2f, 0xdf,
	0xb2, 0xb3, 0x83, 0x35, 0x7c, 0xfa, 0x0a, 0x9a, 0x8d, 0xd9, 0x58, 0xe2, 0xdd, 0x8f, 0x2a, 0xab,
	0x81, 0x8c, 0xf6, 0xa5, 0x6d, 0xde, 0x9c, 0xbc, 0x76, 0x86, 0x3f, 0xf0, 0xc7, 0x90, 0x26, 0xf9,
	0x4d, 0xa1, 0xc7, 0x5f, 0x54, 0x9e, 0x43, 0x86, 0xeb, 0x51, 0x9a, 0xd0, 0xfa, 0x40, 0x62, 0x89,
	0x5f, 0xd0, 0xa7, 0x0a, 0xf4, 0xec, 0x03, 0xed, 0x0f, 0xe4, 0xa6, 0x43, 0xe3, 0xb0, 0x7a, 0xbf,
	0x58, 0x68, 0xa8, 0x2a, 0x4a, 0xcb, 0x97, 0x6d, 0x08, 0x7f, 0x22, 0x33, 0x5d, 0x3c, 0xa6, 0x8b,
	0x3d, 0xcb, 0x23, 0xd6, 0x31, 0x8c, 0x12, 0xa7, 0x45, 0x0e, 0x0d, 0xc5, 0x36, 0x90, 0xb6, 0x99,
	0x77, 0xe9, 0x3f, 0xf6, 0xea, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x28, 0x21, 0xe2, 0xd4,
	0x04, 0x00, 0x00,
}
