// Code generated by protoc-gen-go. DO NOT EDIT.
// source: options.proto

package user_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BucketOptions struct {
	Policy               int32    `protobuf:"varint,3,opt,name=Policy,proto3" json:"Policy,omitempty"`
	DataCount            int32    `protobuf:"varint,4,opt,name=DataCount,proto3" json:"DataCount,omitempty"`
	ParityCount          int32    `protobuf:"varint,5,opt,name=ParityCount,proto3" json:"ParityCount,omitempty"`
	SegmentSize          uint64   `protobuf:"varint,11,opt,name=SegmentSize,proto3" json:"SegmentSize,omitempty"`
	TagFlag              uint64   `protobuf:"varint,12,opt,name=TagFlag,proto3" json:"TagFlag,omitempty"`
	Encryption           bool     `protobuf:"varint,14,opt,name=Encryption,proto3" json:"Encryption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketOptions) Reset()         { *m = BucketOptions{} }
func (m *BucketOptions) String() string { return proto.CompactTextString(m) }
func (*BucketOptions) ProtoMessage()    {}
func (*BucketOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{0}
}

func (m *BucketOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketOptions.Unmarshal(m, b)
}
func (m *BucketOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketOptions.Marshal(b, m, deterministic)
}
func (m *BucketOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketOptions.Merge(m, src)
}
func (m *BucketOptions) XXX_Size() int {
	return xxx_messageInfo_BucketOptions.Size(m)
}
func (m *BucketOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BucketOptions proto.InternalMessageInfo

func (m *BucketOptions) GetPolicy() int32 {
	if m != nil {
		return m.Policy
	}
	return 0
}

func (m *BucketOptions) GetDataCount() int32 {
	if m != nil {
		return m.DataCount
	}
	return 0
}

func (m *BucketOptions) GetParityCount() int32 {
	if m != nil {
		return m.ParityCount
	}
	return 0
}

func (m *BucketOptions) GetSegmentSize() uint64 {
	if m != nil {
		return m.SegmentSize
	}
	return 0
}

func (m *BucketOptions) GetTagFlag() uint64 {
	if m != nil {
		return m.TagFlag
	}
	return 0
}

func (m *BucketOptions) GetEncryption() bool {
	if m != nil {
		return m.Encryption
	}
	return false
}

func init() {
	proto.RegisterType((*BucketOptions)(nil), "user.pb.BucketOptions")
}

func init() { proto.RegisterFile("options.proto", fileDescriptor_110d40819f1994f9) }

var fileDescriptor_110d40819f1994f9 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2f, 0x28, 0xc9,
	0xcc, 0xcf, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2,
	0x2b, 0x48, 0x52, 0x3a, 0xcc, 0xc8, 0xc5, 0xeb, 0x54, 0x9a, 0x9c, 0x9d, 0x5a, 0xe2, 0x0f, 0x51,
	0x20, 0x24, 0xc6, 0xc5, 0x16, 0x90, 0x9f, 0x93, 0x99, 0x5c, 0x29, 0xc1, 0xac, 0xc0, 0xa8, 0xc1,
	0x1a, 0x04, 0xe5, 0x09, 0xc9, 0x70, 0x71, 0xba, 0x24, 0x96, 0x24, 0x3a, 0xe7, 0x97, 0xe6, 0x95,
	0x48, 0xb0, 0x80, 0xa5, 0x10, 0x02, 0x42, 0x0a, 0x5c, 0xdc, 0x01, 0x89, 0x45, 0x99, 0x25, 0x95,
	0x10, 0x79, 0x56, 0xb0, 0x3c, 0xb2, 0x10, 0x48, 0x45, 0x70, 0x6a, 0x7a, 0x6e, 0x6a, 0x5e, 0x49,
	0x70, 0x66, 0x55, 0xaa, 0x04, 0xb7, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0xb2, 0x90, 0x90, 0x04, 0x17,
	0x7b, 0x48, 0x62, 0xba, 0x5b, 0x4e, 0x62, 0xba, 0x04, 0x0f, 0x58, 0x16, 0xc6, 0x15, 0x92, 0xe3,
	0xe2, 0x72, 0xcd, 0x4b, 0x2e, 0xaa, 0x04, 0x3b, 0x51, 0x82, 0x4f, 0x81, 0x51, 0x83, 0x23, 0x08,
	0x49, 0x24, 0x89, 0x0d, 0xec, 0x2b, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x82, 0x2a, 0x41,
	0x34, 0xe6, 0x00, 0x00, 0x00,
}
