package loader

import (
	"github.com/memoio/go-mefs/plugin"
	pluginflatfs "github.com/memoio/go-mefs/plugin/plugins/flatfs"
	pluginlevelds "github.com/memoio/go-mefs/plugin/plugins/levelds"
)

// DO NOT EDIT THIS FILE
// This file is being generated as part of plugin build process
// To change it, modify the plugin/loader/preload.sh

var preloadPlugins = []plugin.Plugin{
	pluginflatfs.Plugins[0],
	pluginlevelds.Plugins[0],
}
