// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: block.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BucketOptions struct {
	Version     int32 `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Policy      int32 `protobuf:"varint,2,opt,name=Policy,proto3" json:"Policy,omitempty"`
	DataCount   int32 `protobuf:"varint,3,opt,name=DataCount,proto3" json:"DataCount,omitempty"`
	ParityCount int32 `protobuf:"varint,4,opt,name=ParityCount,proto3" json:"ParityCount,omitempty"`
	TagFlag     int32 `protobuf:"varint,5,opt,name=TagFlag,proto3" json:"TagFlag,omitempty"`
	SegmentSize int32 `protobuf:"varint,6,opt,name=SegmentSize,proto3" json:"SegmentSize,omitempty"`
	// number of segments
	SegmentCount         int32    `protobuf:"varint,7,opt,name=SegmentCount,proto3" json:"SegmentCount,omitempty"`
	Encryption           bool     `protobuf:"varint,8,opt,name=Encryption,proto3" json:"Encryption,omitempty"`
	Start                int32    `protobuf:"varint,11,opt,name=Start,proto3" json:"Start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketOptions) Reset()         { *m = BucketOptions{} }
func (m *BucketOptions) String() string { return proto.CompactTextString(m) }
func (*BucketOptions) ProtoMessage()    {}
func (*BucketOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}
func (m *BucketOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketOptions.Unmarshal(m, b)
}
func (m *BucketOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketOptions.Marshal(b, m, deterministic)
}
func (m *BucketOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketOptions.Merge(m, src)
}
func (m *BucketOptions) XXX_Size() int {
	return xxx_messageInfo_BucketOptions.Size(m)
}
func (m *BucketOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BucketOptions proto.InternalMessageInfo

func (m *BucketOptions) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BucketOptions) GetPolicy() int32 {
	if m != nil {
		return m.Policy
	}
	return 0
}

func (m *BucketOptions) GetDataCount() int32 {
	if m != nil {
		return m.DataCount
	}
	return 0
}

func (m *BucketOptions) GetParityCount() int32 {
	if m != nil {
		return m.ParityCount
	}
	return 0
}

func (m *BucketOptions) GetTagFlag() int32 {
	if m != nil {
		return m.TagFlag
	}
	return 0
}

func (m *BucketOptions) GetSegmentSize() int32 {
	if m != nil {
		return m.SegmentSize
	}
	return 0
}

func (m *BucketOptions) GetSegmentCount() int32 {
	if m != nil {
		return m.SegmentCount
	}
	return 0
}

func (m *BucketOptions) GetEncryption() bool {
	if m != nil {
		return m.Encryption
	}
	return false
}

func (m *BucketOptions) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func init() {
	proto.RegisterType((*BucketOptions)(nil), "proto.BucketOptions")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d) }

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0xe9, 0x6a, 0xba, 0xeb, 0x54, 0x2f, 0x83, 0xc8, 0x1c, 0x44, 0xca, 0x9e, 0xf6, 0xe4,
	0xc5, 0x37, 0xf0, 0xdf, 0xd5, 0x65, 0x2b, 0xde, 0xd3, 0x10, 0x4a, 0x68, 0x4d, 0x4a, 0x3a, 0x3d,
	0xd4, 0x17, 0xf1, 0x75, 0xa5, 0x93, 0x8a, 0xf5, 0x14, 0x7e, 0xbf, 0x2f, 0x5f, 0x86, 0x0c, 0x14,
	0x75, 0x17, 0x4c, 0x7b, 0xdf, 0xc7, 0xc0, 0x01, 0x95, 0x1c, 0xfb, 0xef, 0x0d, 0x5c, 0x3d, 0x8e,
	0xa6, 0xb5, 0xfc, 0xd6, 0xb3, 0x0b, 0x7e, 0x40, 0x82, 0xed, 0x87, 0x8d, 0x83, 0x0b, 0x9e, 0xb2,
	0x32, 0x3b, 0xa8, 0xd3, 0x2f, 0xe2, 0x0d, 0xe4, 0xc7, 0xd0, 0x39, 0x33, 0xd1, 0x46, 0x82, 0x85,
	0xf0, 0x16, 0x2e, 0x9e, 0x35, 0xeb, 0xa7, 0x30, 0x7a, 0xa6, 0x33, 0x89, 0xfe, 0x04, 0x96, 0x50,
	0x1c, 0x75, 0x74, 0x3c, 0xa5, 0xfc, 0x5c, 0xf2, 0xb5, 0x9a, 0x27, 0xbe, 0xeb, 0xe6, 0xb5, 0xd3,
	0x0d, 0xa9, 0x34, 0x71, 0xc1, 0xb9, 0x5b, 0xd9, 0xe6, 0xd3, 0x7a, 0xae, 0xdc, 0x97, 0xa5, 0x3c,
	0x75, 0x57, 0x0a, 0xf7, 0x70, 0xb9, 0x60, 0x7a, 0x7e, 0x2b, 0x57, 0xfe, 0x39, 0xbc, 0x03, 0x78,
	0xf1, 0x26, 0x4e, 0xf2, 0x41, 0xda, 0x95, 0xd9, 0x61, 0x77, 0x5a, 0x19, 0xbc, 0x06, 0x55, 0xb1,
	0x8e, 0x4c, 0x85, 0x94, 0x13, 0xd4, 0xb9, 0x2c, 0xe8, 0xe1, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc7,
	0x07, 0x31, 0x20, 0x36, 0x01, 0x00, 0x00,
}
