// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lfs.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SuperBlockInfo struct {
	BucketsSet           []uint64 `protobuf:"varint,1,rep,packed,name=BucketsSet,proto3" json:"BucketsSet,omitempty"`
	MetaBackupCount      int32    `protobuf:"varint,2,opt,name=MetaBackupCount,proto3" json:"MetaBackupCount,omitempty"`
	NextBucketID         int32    `protobuf:"varint,3,opt,name=NextBucketID,proto3" json:"NextBucketID,omitempty"`
	MagicNumber          int32    `protobuf:"varint,4,opt,name=MagicNumber,proto3" json:"MagicNumber,omitempty"`
	Version              int32    `protobuf:"varint,5,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuperBlockInfo) Reset()         { *m = SuperBlockInfo{} }
func (m *SuperBlockInfo) String() string { return proto.CompactTextString(m) }
func (*SuperBlockInfo) ProtoMessage()    {}
func (*SuperBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3f13cde69be66c, []int{0}
}
func (m *SuperBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperBlockInfo.Unmarshal(m, b)
}
func (m *SuperBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperBlockInfo.Marshal(b, m, deterministic)
}
func (m *SuperBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperBlockInfo.Merge(m, src)
}
func (m *SuperBlockInfo) XXX_Size() int {
	return xxx_messageInfo_SuperBlockInfo.Size(m)
}
func (m *SuperBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SuperBlockInfo proto.InternalMessageInfo

func (m *SuperBlockInfo) GetBucketsSet() []uint64 {
	if m != nil {
		return m.BucketsSet
	}
	return nil
}

func (m *SuperBlockInfo) GetMetaBackupCount() int32 {
	if m != nil {
		return m.MetaBackupCount
	}
	return 0
}

func (m *SuperBlockInfo) GetNextBucketID() int32 {
	if m != nil {
		return m.NextBucketID
	}
	return 0
}

func (m *SuperBlockInfo) GetMagicNumber() int32 {
	if m != nil {
		return m.MagicNumber
	}
	return 0
}

func (m *SuperBlockInfo) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type BucketInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	BucketID             int32    `protobuf:"varint,2,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	Policy               int32    `protobuf:"varint,3,opt,name=Policy,proto3" json:"Policy,omitempty"`
	DataCount            int32    `protobuf:"varint,4,opt,name=DataCount,proto3" json:"DataCount,omitempty"`
	ParityCount          int32    `protobuf:"varint,5,opt,name=ParityCount,proto3" json:"ParityCount,omitempty"`
	CurStripe            int64    `protobuf:"varint,6,opt,name=CurStripe,proto3" json:"CurStripe,omitempty"`
	NextOffset           int64    `protobuf:"varint,7,opt,name=NextOffset,proto3" json:"NextOffset,omitempty"`
	ObjectsBlockSize     int64    `protobuf:"varint,8,opt,name=ObjectsBlockSize,proto3" json:"ObjectsBlockSize,omitempty"`
	SegmentSize          int32    `protobuf:"varint,9,opt,name=SegmentSize,proto3" json:"SegmentSize,omitempty"`
	TagFlag              int32    `protobuf:"varint,10,opt,name=TagFlag,proto3" json:"TagFlag,omitempty"`
	Ctime                int64    `protobuf:"varint,11,opt,name=Ctime,proto3" json:"Ctime,omitempty"`
	LastModified         int64    `protobuf:"varint,12,opt,name=LastModified,proto3" json:"LastModified,omitempty"`
	Deletion             bool     `protobuf:"varint,13,opt,name=Deletion,proto3" json:"Deletion,omitempty"`
	Encryption           bool     `protobuf:"varint,14,opt,name=Encryption,proto3" json:"Encryption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketInfo) Reset()         { *m = BucketInfo{} }
func (m *BucketInfo) String() string { return proto.CompactTextString(m) }
func (*BucketInfo) ProtoMessage()    {}
func (*BucketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3f13cde69be66c, []int{1}
}
func (m *BucketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketInfo.Unmarshal(m, b)
}
func (m *BucketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketInfo.Marshal(b, m, deterministic)
}
func (m *BucketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketInfo.Merge(m, src)
}
func (m *BucketInfo) XXX_Size() int {
	return xxx_messageInfo_BucketInfo.Size(m)
}
func (m *BucketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BucketInfo proto.InternalMessageInfo

func (m *BucketInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BucketInfo) GetBucketID() int32 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *BucketInfo) GetPolicy() int32 {
	if m != nil {
		return m.Policy
	}
	return 0
}

func (m *BucketInfo) GetDataCount() int32 {
	if m != nil {
		return m.DataCount
	}
	return 0
}

func (m *BucketInfo) GetParityCount() int32 {
	if m != nil {
		return m.ParityCount
	}
	return 0
}

func (m *BucketInfo) GetCurStripe() int64 {
	if m != nil {
		return m.CurStripe
	}
	return 0
}

func (m *BucketInfo) GetNextOffset() int64 {
	if m != nil {
		return m.NextOffset
	}
	return 0
}

func (m *BucketInfo) GetObjectsBlockSize() int64 {
	if m != nil {
		return m.ObjectsBlockSize
	}
	return 0
}

func (m *BucketInfo) GetSegmentSize() int32 {
	if m != nil {
		return m.SegmentSize
	}
	return 0
}

func (m *BucketInfo) GetTagFlag() int32 {
	if m != nil {
		return m.TagFlag
	}
	return 0
}

func (m *BucketInfo) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *BucketInfo) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

func (m *BucketInfo) GetDeletion() bool {
	if m != nil {
		return m.Deletion
	}
	return false
}

func (m *BucketInfo) GetEncryption() bool {
	if m != nil {
		return m.Encryption
	}
	return false
}

type ObjectInfo struct {
	Name                 string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	BucketID             int32             `protobuf:"varint,2,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	Length               int64             `protobuf:"varint,3,opt,name=Length,proto3" json:"Length,omitempty"`
	StripeStart          int64             `protobuf:"varint,4,opt,name=StripeStart,proto3" json:"StripeStart,omitempty"`
	Offset               int64             `protobuf:"varint,5,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Ctime                int64             `protobuf:"varint,6,opt,name=Ctime,proto3" json:"Ctime,omitempty"`
	ContentType          string            `protobuf:"bytes,7,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	ETag                 string            `protobuf:"bytes,8,opt,name=ETag,proto3" json:"ETag,omitempty"`
	Deletion             bool              `protobuf:"varint,9,opt,name=Deletion,proto3" json:"Deletion,omitempty"`
	Dir                  bool              `protobuf:"varint,10,opt,name=Dir,proto3" json:"Dir,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,11,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NextPart             string            `protobuf:"bytes,12,opt,name=NextPart,proto3" json:"NextPart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ObjectInfo) Reset()         { *m = ObjectInfo{} }
func (m *ObjectInfo) String() string { return proto.CompactTextString(m) }
func (*ObjectInfo) ProtoMessage()    {}
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3f13cde69be66c, []int{2}
}
func (m *ObjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectInfo.Unmarshal(m, b)
}
func (m *ObjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectInfo.Marshal(b, m, deterministic)
}
func (m *ObjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectInfo.Merge(m, src)
}
func (m *ObjectInfo) XXX_Size() int {
	return xxx_messageInfo_ObjectInfo.Size(m)
}
func (m *ObjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectInfo proto.InternalMessageInfo

func (m *ObjectInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectInfo) GetBucketID() int32 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *ObjectInfo) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ObjectInfo) GetStripeStart() int64 {
	if m != nil {
		return m.StripeStart
	}
	return 0
}

func (m *ObjectInfo) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ObjectInfo) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *ObjectInfo) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *ObjectInfo) GetETag() string {
	if m != nil {
		return m.ETag
	}
	return ""
}

func (m *ObjectInfo) GetDeletion() bool {
	if m != nil {
		return m.Deletion
	}
	return false
}

func (m *ObjectInfo) GetDir() bool {
	if m != nil {
		return m.Dir
	}
	return false
}

func (m *ObjectInfo) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ObjectInfo) GetNextPart() string {
	if m != nil {
		return m.NextPart
	}
	return ""
}

func init() {
	proto.RegisterType((*SuperBlockInfo)(nil), "proto.SuperBlockInfo")
	proto.RegisterType((*BucketInfo)(nil), "proto.BucketInfo")
	proto.RegisterType((*ObjectInfo)(nil), "proto.ObjectInfo")
	proto.RegisterMapType((map[string]string)(nil), "proto.ObjectInfo.MetadataEntry")
}

func init() { proto.RegisterFile("lfs.proto", fileDescriptor_9a3f13cde69be66c) }

var fileDescriptor_9a3f13cde69be66c = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xeb, 0x26, 0x8d, 0x37, 0x6d, 0xa9, 0x56, 0x08, 0xad, 0x2a, 0x04, 0x56, 0x4e, 0x16,
	0x87, 0x1e, 0xe0, 0x82, 0xe8, 0x2d, 0x1f, 0x48, 0x95, 0x9a, 0x34, 0x5a, 0x47, 0xdc, 0x37, 0xce,
	0xc4, 0x98, 0x38, 0xb6, 0xb5, 0x1e, 0x23, 0xcc, 0x8f, 0xe1, 0x37, 0x70, 0xe6, 0xd7, 0xa1, 0x9d,
	0x75, 0x1c, 0xa7, 0xdc, 0x38, 0x65, 0xdf, 0x9b, 0x99, 0xec, 0x9b, 0xf7, 0xbc, 0xcc, 0x4b, 0xb7,
	0xe5, 0x5d, 0xa1, 0x73, 0xcc, 0x79, 0x8f, 0x7e, 0x46, 0x7f, 0x1c, 0x76, 0x1d, 0x56, 0x05, 0xe8,
	0x71, 0x9a, 0x47, 0xbb, 0x87, 0x6c, 0x9b, 0xf3, 0x37, 0x8c, 0x8d, 0xab, 0x68, 0x07, 0x58, 0x86,
	0x80, 0xc2, 0xf1, 0xdd, 0xe0, 0x5c, 0x76, 0x18, 0x1e, 0xb0, 0x17, 0x73, 0x40, 0x35, 0x56, 0xd1,
	0xae, 0x2a, 0x26, 0x79, 0x95, 0xa1, 0x38, 0xf3, 0x9d, 0xa0, 0x27, 0x9f, 0xd3, 0x7c, 0xc4, 0x2e,
	0x17, 0xf0, 0x03, 0xed, 0xec, 0xc3, 0x54, 0xb8, 0xd4, 0x76, 0xc2, 0x71, 0x9f, 0x0d, 0xe7, 0x2a,
	0x4e, 0xa2, 0x45, 0xb5, 0x5f, 0x83, 0x16, 0xe7, 0xd4, 0xd2, 0xa5, 0xb8, 0x60, 0x17, 0x5f, 0x40,
	0x97, 0x49, 0x9e, 0x89, 0x1e, 0x55, 0x0f, 0x70, 0xf4, 0xdb, 0x3d, 0x48, 0x25, 0xe1, 0x9c, 0x9d,
	0x2f, 0xd4, 0x1e, 0x84, 0xe3, 0x3b, 0x81, 0x27, 0xe9, 0xcc, 0x6f, 0xd9, 0xa0, 0xbd, 0xde, 0xaa,
	0x6c, 0x31, 0x7f, 0xc5, 0xfa, 0xcb, 0x3c, 0x4d, 0xa2, 0xba, 0x11, 0xd6, 0x20, 0xfe, 0x9a, 0x79,
	0x53, 0x85, 0xca, 0xae, 0x66, 0x05, 0x1d, 0x09, 0x23, 0x78, 0xa9, 0x74, 0x82, 0xb5, 0xad, 0x5b,
	0x49, 0x5d, 0xca, 0xcc, 0x4f, 0x2a, 0x1d, 0xa2, 0x4e, 0x0a, 0x10, 0x7d, 0xdf, 0x09, 0x5c, 0x79,
	0x24, 0x8c, 0xbd, 0xc6, 0x80, 0xa7, 0xed, 0xb6, 0x04, 0x14, 0x17, 0x54, 0xee, 0x30, 0xfc, 0x1d,
	0xbb, 0x79, 0x5a, 0x7f, 0x83, 0x08, 0x4b, 0x8a, 0x24, 0x4c, 0x7e, 0x82, 0x18, 0x50, 0xd7, 0x3f,
	0xbc, 0xd1, 0x12, 0x42, 0xbc, 0x87, 0x0c, 0xa9, 0xcd, 0xb3, 0x5a, 0x3a, 0x94, 0x31, 0x6f, 0xa5,
	0xe2, 0xcf, 0xa9, 0x8a, 0x05, 0xb3, 0xe6, 0x35, 0x90, 0xbf, 0x64, 0xbd, 0x09, 0x26, 0x7b, 0x10,
	0x43, 0xfa, 0x73, 0x0b, 0x4c, 0x64, 0x8f, 0xaa, 0xc4, 0x79, 0xbe, 0x49, 0xb6, 0x09, 0x6c, 0xc4,
	0x25, 0x15, 0x4f, 0x38, 0xe3, 0xe9, 0x14, 0x52, 0x40, 0x93, 0xc8, 0x95, 0xef, 0x04, 0x03, 0xd9,
	0x62, 0xb3, 0xdd, 0x2c, 0x8b, 0x74, 0x5d, 0x50, 0xf5, 0x9a, 0xaa, 0x1d, 0x66, 0xf4, 0xcb, 0x65,
	0xcc, 0xae, 0xf1, 0xbf, 0x91, 0x3d, 0x42, 0x16, 0xe3, 0x57, 0x8a, 0xcc, 0x95, 0x0d, 0x22, 0x23,
	0xc8, 0xde, 0x10, 0x95, 0xb6, 0xa1, 0xb9, 0xb2, 0x4b, 0x99, 0xc9, 0xc6, 0xf2, 0x9e, 0x9d, 0x6c,
	0xec, 0x6e, 0x6d, 0xe8, 0x77, 0x6d, 0xf0, 0xd9, 0x70, 0x92, 0x67, 0x08, 0x19, 0xae, 0xea, 0x02,
	0x28, 0x25, 0x4f, 0x76, 0x29, 0xa3, 0x7c, 0xb6, 0x52, 0x31, 0x45, 0xe3, 0x49, 0x3a, 0x9f, 0x18,
	0xe3, 0x3d, 0x33, 0xe6, 0x86, 0xb9, 0xd3, 0x44, 0x53, 0x08, 0x03, 0x69, 0x8e, 0xfc, 0x9e, 0x0d,
	0xcc, 0x83, 0xd9, 0x28, 0x54, 0x62, 0xe8, 0xbb, 0xc1, 0xf0, 0xfd, 0x5b, 0xfb, 0x36, 0xef, 0x8e,
	0x06, 0xdd, 0x1d, 0x3a, 0x66, 0x19, 0xea, 0x5a, 0xb6, 0x03, 0xe6, 0x2a, 0xf3, 0xcd, 0x2c, 0xcd,
	0xb6, 0x97, 0x24, 0xa1, 0xc5, 0xb7, 0xf7, 0xec, 0xea, 0x64, 0xcc, 0xdc, 0xbd, 0x83, 0xba, 0x31,
	0xd9, 0x1c, 0xcd, 0xd6, 0xdf, 0x55, 0x5a, 0x01, 0x19, 0xec, 0x49, 0x0b, 0x3e, 0x9d, 0x7d, 0x74,
	0xd6, 0x7d, 0x92, 0xf0, 0xe1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x5a, 0x77, 0x93, 0x2b,
	0x04, 0x00, 0x00,
}
