// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mefs.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OpType int32

const (
	OpType_BroadCast OpType = 0
	OpType_Put       OpType = 1
	OpType_Get       OpType = 2
	OpType_Append    OpType = 3
	OpType_Delete    OpType = 4
)

var OpType_name = map[int32]string{
	0: "BroadCast",
	1: "Put",
	2: "Get",
	3: "Append",
	4: "Delete",
}

var OpType_value = map[string]int32{
	"BroadCast": 0,
	"Put":       1,
	"Get":       2,
	"Append":    3,
	"Delete":    4,
}

func (x OpType) String() string {
	return proto.EnumName(OpType_name, int32(x))
}

func (OpType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{0}
}

type KeyType int32

const (
	KeyType_Wrong           KeyType = 0
	KeyType_Role            KeyType = 1
	KeyType_PublicKey       KeyType = 2
	KeyType_Config          KeyType = 3
	KeyType_LFS             KeyType = 4
	KeyType_Users           KeyType = 5
	KeyType_Keepers         KeyType = 6
	KeyType_Providers       KeyType = 7
	KeyType_Block           KeyType = 10
	KeyType_BlockPos        KeyType = 11
	KeyType_ChalTime        KeyType = 12
	KeyType_Pos             KeyType = 13
	KeyType_HeartBeat       KeyType = 20
	KeyType_UserInit        KeyType = 21
	KeyType_UserNotify      KeyType = 22
	KeyType_UserStart       KeyType = 23
	KeyType_UserStop        KeyType = 24
	KeyType_Challenge       KeyType = 25
	KeyType_Repair          KeyType = 26
	KeyType_ExternalAddress KeyType = 27
	KeyType_Storage         KeyType = 28
	KeyType_Query           KeyType = 30
	KeyType_Offer           KeyType = 31
	KeyType_UpKeeping       KeyType = 32
	KeyType_Channel         KeyType = 33
	KeyType_ChalPay         KeyType = 40
	KeyType_LastPay         KeyType = 41
	KeyType_PosMeta         KeyType = 42
)

var KeyType_name = map[int32]string{
	0:  "Wrong",
	1:  "Role",
	2:  "PublicKey",
	3:  "Config",
	4:  "LFS",
	5:  "Users",
	6:  "Keepers",
	7:  "Providers",
	10: "Block",
	11: "BlockPos",
	12: "ChalTime",
	13: "Pos",
	20: "HeartBeat",
	21: "UserInit",
	22: "UserNotify",
	23: "UserStart",
	24: "UserStop",
	25: "Challenge",
	26: "Repair",
	27: "ExternalAddress",
	28: "Storage",
	30: "Query",
	31: "Offer",
	32: "UpKeeping",
	33: "Channel",
	40: "ChalPay",
	41: "LastPay",
	42: "PosMeta",
}

var KeyType_value = map[string]int32{
	"Wrong":           0,
	"Role":            1,
	"PublicKey":       2,
	"Config":          3,
	"LFS":             4,
	"Users":           5,
	"Keepers":         6,
	"Providers":       7,
	"Block":           10,
	"BlockPos":        11,
	"ChalTime":        12,
	"Pos":             13,
	"HeartBeat":       20,
	"UserInit":        21,
	"UserNotify":      22,
	"UserStart":       23,
	"UserStop":        24,
	"Challenge":       25,
	"Repair":          26,
	"ExternalAddress": 27,
	"Storage":         28,
	"Query":           30,
	"Offer":           31,
	"UpKeeping":       32,
	"Channel":         33,
	"ChalPay":         40,
	"LastPay":         41,
	"PosMeta":         42,
}

func (x KeyType) String() string {
	return proto.EnumName(KeyType_name, int32(x))
}

func (KeyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{1}
}

type KeyMeta struct {
	Version              int32    `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	KType                KeyType  `protobuf:"varint,2,opt,name=KType,proto3,enum=proto.KeyType" json:"KType,omitempty"`
	Mid                  string   `protobuf:"bytes,3,opt,name=Mid,proto3" json:"Mid,omitempty"`
	Options              []string `protobuf:"bytes,4,rep,name=Options,proto3" json:"Options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyMeta) Reset()         { *m = KeyMeta{} }
func (m *KeyMeta) String() string { return proto.CompactTextString(m) }
func (*KeyMeta) ProtoMessage()    {}
func (*KeyMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{0}
}
func (m *KeyMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyMeta.Unmarshal(m, b)
}
func (m *KeyMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyMeta.Marshal(b, m, deterministic)
}
func (m *KeyMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyMeta.Merge(m, src)
}
func (m *KeyMeta) XXX_Size() int {
	return xxx_messageInfo_KeyMeta.Size(m)
}
func (m *KeyMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyMeta.DiscardUnknown(m)
}

var xxx_messageInfo_KeyMeta proto.InternalMessageInfo

func (m *KeyMeta) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *KeyMeta) GetKType() KeyType {
	if m != nil {
		return m.KType
	}
	return KeyType_Wrong
}

func (m *KeyMeta) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *KeyMeta) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

type UserBLS12Config struct {
	PubkeyBls            []byte   `protobuf:"bytes,2,opt,name=pubkeyBls,proto3" json:"pubkeyBls,omitempty"`
	PubkeyG              []byte   `protobuf:"bytes,3,opt,name=pubkeyG,proto3" json:"pubkeyG,omitempty"`
	PubkeyU              [][]byte `protobuf:"bytes,4,rep,name=pubkeyU,proto3" json:"pubkeyU,omitempty"`
	PubkeyW              [][]byte `protobuf:"bytes,5,rep,name=pubkeyW,proto3" json:"pubkeyW,omitempty"`
	PrikeyBls            []byte   `protobuf:"bytes,6,opt,name=prikeyBls,proto3" json:"prikeyBls,omitempty"`
	X                    []byte   `protobuf:"bytes,7,opt,name=X,proto3" json:"X,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBLS12Config) Reset()         { *m = UserBLS12Config{} }
func (m *UserBLS12Config) String() string { return proto.CompactTextString(m) }
func (*UserBLS12Config) ProtoMessage()    {}
func (*UserBLS12Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{1}
}
func (m *UserBLS12Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBLS12Config.Unmarshal(m, b)
}
func (m *UserBLS12Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBLS12Config.Marshal(b, m, deterministic)
}
func (m *UserBLS12Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBLS12Config.Merge(m, src)
}
func (m *UserBLS12Config) XXX_Size() int {
	return xxx_messageInfo_UserBLS12Config.Size(m)
}
func (m *UserBLS12Config) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBLS12Config.DiscardUnknown(m)
}

var xxx_messageInfo_UserBLS12Config proto.InternalMessageInfo

func (m *UserBLS12Config) GetPubkeyBls() []byte {
	if m != nil {
		return m.PubkeyBls
	}
	return nil
}

func (m *UserBLS12Config) GetPubkeyG() []byte {
	if m != nil {
		return m.PubkeyG
	}
	return nil
}

func (m *UserBLS12Config) GetPubkeyU() [][]byte {
	if m != nil {
		return m.PubkeyU
	}
	return nil
}

func (m *UserBLS12Config) GetPubkeyW() [][]byte {
	if m != nil {
		return m.PubkeyW
	}
	return nil
}

func (m *UserBLS12Config) GetPrikeyBls() []byte {
	if m != nil {
		return m.PrikeyBls
	}
	return nil
}

func (m *UserBLS12Config) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

type BucketRoot struct {
	BucketID             int64    `protobuf:"varint,1,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	ObjectCount          int64    `protobuf:"varint,2,opt,name=ObjectCount,proto3" json:"ObjectCount,omitempty"`
	Root                 []byte   `protobuf:"bytes,3,opt,name=Root,proto3" json:"Root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketRoot) Reset()         { *m = BucketRoot{} }
func (m *BucketRoot) String() string { return proto.CompactTextString(m) }
func (*BucketRoot) ProtoMessage()    {}
func (*BucketRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{2}
}
func (m *BucketRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketRoot.Unmarshal(m, b)
}
func (m *BucketRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketRoot.Marshal(b, m, deterministic)
}
func (m *BucketRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketRoot.Merge(m, src)
}
func (m *BucketRoot) XXX_Size() int {
	return xxx_messageInfo_BucketRoot.Size(m)
}
func (m *BucketRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketRoot.DiscardUnknown(m)
}

var xxx_messageInfo_BucketRoot proto.InternalMessageInfo

func (m *BucketRoot) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *BucketRoot) GetObjectCount() int64 {
	if m != nil {
		return m.ObjectCount
	}
	return 0
}

func (m *BucketRoot) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

type LfsRoot struct {
	CTime                int64         `protobuf:"varint,1,opt,name=CTime,proto3" json:"CTime,omitempty"`
	Root                 []byte        `protobuf:"bytes,2,opt,name=Root,proto3" json:"Root,omitempty"`
	BRoots               []*BucketRoot `protobuf:"bytes,3,rep,name=BRoots,proto3" json:"BRoots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LfsRoot) Reset()         { *m = LfsRoot{} }
func (m *LfsRoot) String() string { return proto.CompactTextString(m) }
func (*LfsRoot) ProtoMessage()    {}
func (*LfsRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{3}
}
func (m *LfsRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LfsRoot.Unmarshal(m, b)
}
func (m *LfsRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LfsRoot.Marshal(b, m, deterministic)
}
func (m *LfsRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LfsRoot.Merge(m, src)
}
func (m *LfsRoot) XXX_Size() int {
	return xxx_messageInfo_LfsRoot.Size(m)
}
func (m *LfsRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_LfsRoot.DiscardUnknown(m)
}

var xxx_messageInfo_LfsRoot proto.InternalMessageInfo

func (m *LfsRoot) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *LfsRoot) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *LfsRoot) GetBRoots() []*BucketRoot {
	if m != nil {
		return m.BRoots
	}
	return nil
}

type SuperBlockInfo struct {
	Version              int32      `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	MetaBackupCount      int32      `protobuf:"varint,2,opt,name=MetaBackupCount,proto3" json:"MetaBackupCount,omitempty"`
	CTime                int64      `protobuf:"varint,3,opt,name=CTime,proto3" json:"CTime,omitempty"`
	NextBucketID         int64      `protobuf:"varint,4,opt,name=NextBucketID,proto3" json:"NextBucketID,omitempty"`
	LRoot                []*LfsRoot `protobuf:"bytes,7,rep,name=LRoot,proto3" json:"LRoot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SuperBlockInfo) Reset()         { *m = SuperBlockInfo{} }
func (m *SuperBlockInfo) String() string { return proto.CompactTextString(m) }
func (*SuperBlockInfo) ProtoMessage()    {}
func (*SuperBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{4}
}
func (m *SuperBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperBlockInfo.Unmarshal(m, b)
}
func (m *SuperBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperBlockInfo.Marshal(b, m, deterministic)
}
func (m *SuperBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperBlockInfo.Merge(m, src)
}
func (m *SuperBlockInfo) XXX_Size() int {
	return xxx_messageInfo_SuperBlockInfo.Size(m)
}
func (m *SuperBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SuperBlockInfo proto.InternalMessageInfo

func (m *SuperBlockInfo) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SuperBlockInfo) GetMetaBackupCount() int32 {
	if m != nil {
		return m.MetaBackupCount
	}
	return 0
}

func (m *SuperBlockInfo) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *SuperBlockInfo) GetNextBucketID() int64 {
	if m != nil {
		return m.NextBucketID
	}
	return 0
}

func (m *SuperBlockInfo) GetLRoot() []*LfsRoot {
	if m != nil {
		return m.LRoot
	}
	return nil
}

type BucketOptions struct {
	Version              int32    `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Policy               int32    `protobuf:"varint,2,opt,name=Policy,proto3" json:"Policy,omitempty"`
	DataCount            int32    `protobuf:"varint,3,opt,name=DataCount,proto3" json:"DataCount,omitempty"`
	ParityCount          int32    `protobuf:"varint,4,opt,name=ParityCount,proto3" json:"ParityCount,omitempty"`
	TagFlag              int32    `protobuf:"varint,5,opt,name=TagFlag,proto3" json:"TagFlag,omitempty"`
	SegmentSize          int32    `protobuf:"varint,6,opt,name=SegmentSize,proto3" json:"SegmentSize,omitempty"`
	SegmentCount         int32    `protobuf:"varint,7,opt,name=SegmentCount,proto3" json:"SegmentCount,omitempty"`
	Encryption           int32    `protobuf:"varint,8,opt,name=Encryption,proto3" json:"Encryption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketOptions) Reset()         { *m = BucketOptions{} }
func (m *BucketOptions) String() string { return proto.CompactTextString(m) }
func (*BucketOptions) ProtoMessage()    {}
func (*BucketOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{5}
}
func (m *BucketOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketOptions.Unmarshal(m, b)
}
func (m *BucketOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketOptions.Marshal(b, m, deterministic)
}
func (m *BucketOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketOptions.Merge(m, src)
}
func (m *BucketOptions) XXX_Size() int {
	return xxx_messageInfo_BucketOptions.Size(m)
}
func (m *BucketOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BucketOptions proto.InternalMessageInfo

func (m *BucketOptions) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BucketOptions) GetPolicy() int32 {
	if m != nil {
		return m.Policy
	}
	return 0
}

func (m *BucketOptions) GetDataCount() int32 {
	if m != nil {
		return m.DataCount
	}
	return 0
}

func (m *BucketOptions) GetParityCount() int32 {
	if m != nil {
		return m.ParityCount
	}
	return 0
}

func (m *BucketOptions) GetTagFlag() int32 {
	if m != nil {
		return m.TagFlag
	}
	return 0
}

func (m *BucketOptions) GetSegmentSize() int32 {
	if m != nil {
		return m.SegmentSize
	}
	return 0
}

func (m *BucketOptions) GetSegmentCount() int32 {
	if m != nil {
		return m.SegmentCount
	}
	return 0
}

func (m *BucketOptions) GetEncryption() int32 {
	if m != nil {
		return m.Encryption
	}
	return 0
}

type BucketInfo struct {
	Name                 string         `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	BucketID             int64          `protobuf:"varint,2,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	Ctime                int64          `protobuf:"varint,3,opt,name=Ctime,proto3" json:"Ctime,omitempty"`
	BOpts                *BucketOptions `protobuf:"bytes,4,opt,name=BOpts,proto3" json:"BOpts,omitempty"`
	CurStripe            int64          `protobuf:"varint,5,opt,name=CurStripe,proto3" json:"CurStripe,omitempty"`
	NextSeg              int64          `protobuf:"varint,6,opt,name=NextSeg,proto3" json:"NextSeg,omitempty"`
	MTime                int64          `protobuf:"varint,7,opt,name=MTime,proto3" json:"MTime,omitempty"`
	ObjectsBlockSize     int64          `protobuf:"varint,8,opt,name=ObjectsBlockSize,proto3" json:"ObjectsBlockSize,omitempty"`
	Deletion             bool           `protobuf:"varint,9,opt,name=Deletion,proto3" json:"Deletion,omitempty"`
	NextObjectID         int64          `protobuf:"varint,10,opt,name=NextObjectID,proto3" json:"NextObjectID,omitempty"`
	Root                 []byte         `protobuf:"bytes,11,opt,name=Root,proto3" json:"Root,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BucketInfo) Reset()         { *m = BucketInfo{} }
func (m *BucketInfo) String() string { return proto.CompactTextString(m) }
func (*BucketInfo) ProtoMessage()    {}
func (*BucketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{6}
}
func (m *BucketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketInfo.Unmarshal(m, b)
}
func (m *BucketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketInfo.Marshal(b, m, deterministic)
}
func (m *BucketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketInfo.Merge(m, src)
}
func (m *BucketInfo) XXX_Size() int {
	return xxx_messageInfo_BucketInfo.Size(m)
}
func (m *BucketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BucketInfo proto.InternalMessageInfo

func (m *BucketInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BucketInfo) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *BucketInfo) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *BucketInfo) GetBOpts() *BucketOptions {
	if m != nil {
		return m.BOpts
	}
	return nil
}

func (m *BucketInfo) GetCurStripe() int64 {
	if m != nil {
		return m.CurStripe
	}
	return 0
}

func (m *BucketInfo) GetNextSeg() int64 {
	if m != nil {
		return m.NextSeg
	}
	return 0
}

func (m *BucketInfo) GetMTime() int64 {
	if m != nil {
		return m.MTime
	}
	return 0
}

func (m *BucketInfo) GetObjectsBlockSize() int64 {
	if m != nil {
		return m.ObjectsBlockSize
	}
	return 0
}

func (m *BucketInfo) GetDeletion() bool {
	if m != nil {
		return m.Deletion
	}
	return false
}

func (m *BucketInfo) GetNextObjectID() int64 {
	if m != nil {
		return m.NextObjectID
	}
	return 0
}

func (m *BucketInfo) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

type ObjectInfo struct {
	BucketID             int64             `protobuf:"varint,1,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	Ctime                int64             `protobuf:"varint,2,opt,name=Ctime,proto3" json:"Ctime,omitempty"`
	ContentType          string            `protobuf:"bytes,3,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Dir                  bool              `protobuf:"varint,4,opt,name=Dir,proto3" json:"Dir,omitempty"`
	Deletion             bool              `protobuf:"varint,5,opt,name=Deletion,proto3" json:"Deletion,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,6,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ObjectID             int64             `protobuf:"varint,7,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	OPart                *ObjectPart       `protobuf:"bytes,8,opt,name=OPart,proto3" json:"OPart,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ObjectInfo) Reset()         { *m = ObjectInfo{} }
func (m *ObjectInfo) String() string { return proto.CompactTextString(m) }
func (*ObjectInfo) ProtoMessage()    {}
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{7}
}
func (m *ObjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectInfo.Unmarshal(m, b)
}
func (m *ObjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectInfo.Marshal(b, m, deterministic)
}
func (m *ObjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectInfo.Merge(m, src)
}
func (m *ObjectInfo) XXX_Size() int {
	return xxx_messageInfo_ObjectInfo.Size(m)
}
func (m *ObjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectInfo proto.InternalMessageInfo

func (m *ObjectInfo) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *ObjectInfo) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *ObjectInfo) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *ObjectInfo) GetDir() bool {
	if m != nil {
		return m.Dir
	}
	return false
}

func (m *ObjectInfo) GetDeletion() bool {
	if m != nil {
		return m.Deletion
	}
	return false
}

func (m *ObjectInfo) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ObjectInfo) GetObjectID() int64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *ObjectInfo) GetOPart() *ObjectPart {
	if m != nil {
		return m.OPart
	}
	return nil
}

type ObjectPart struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	Length               int64    `protobuf:"varint,3,opt,name=Length,proto3" json:"Length,omitempty"`
	ETag                 string   `protobuf:"bytes,4,opt,name=ETag,proto3" json:"ETag,omitempty"`
	NextPart             string   `protobuf:"bytes,5,opt,name=NextPart,proto3" json:"NextPart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectPart) Reset()         { *m = ObjectPart{} }
func (m *ObjectPart) String() string { return proto.CompactTextString(m) }
func (*ObjectPart) ProtoMessage()    {}
func (*ObjectPart) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{8}
}
func (m *ObjectPart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectPart.Unmarshal(m, b)
}
func (m *ObjectPart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectPart.Marshal(b, m, deterministic)
}
func (m *ObjectPart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectPart.Merge(m, src)
}
func (m *ObjectPart) XXX_Size() int {
	return xxx_messageInfo_ObjectPart.Size(m)
}
func (m *ObjectPart) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectPart.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectPart proto.InternalMessageInfo

func (m *ObjectPart) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectPart) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ObjectPart) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ObjectPart) GetETag() string {
	if m != nil {
		return m.ETag
	}
	return ""
}

func (m *ObjectPart) GetNextPart() string {
	if m != nil {
		return m.NextPart
	}
	return ""
}

type BlockOptions struct {
	Bopts                *BucketOptions `protobuf:"bytes,1,opt,name=Bopts,proto3" json:"Bopts,omitempty"`
	Start                int32          `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	UserID               string         `protobuf:"bytes,11,opt,name=UserID,proto3" json:"UserID,omitempty"`
	QueryID              string         `protobuf:"bytes,12,opt,name=QueryID,proto3" json:"QueryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockOptions) Reset()         { *m = BlockOptions{} }
func (m *BlockOptions) String() string { return proto.CompactTextString(m) }
func (*BlockOptions) ProtoMessage()    {}
func (*BlockOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{9}
}
func (m *BlockOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockOptions.Unmarshal(m, b)
}
func (m *BlockOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockOptions.Marshal(b, m, deterministic)
}
func (m *BlockOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockOptions.Merge(m, src)
}
func (m *BlockOptions) XXX_Size() int {
	return xxx_messageInfo_BlockOptions.Size(m)
}
func (m *BlockOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BlockOptions proto.InternalMessageInfo

func (m *BlockOptions) GetBopts() *BucketOptions {
	if m != nil {
		return m.Bopts
	}
	return nil
}

func (m *BlockOptions) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *BlockOptions) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *BlockOptions) GetQueryID() string {
	if m != nil {
		return m.QueryID
	}
	return ""
}

type ShareLink struct {
	UserID               string         `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	QueryID              string         `protobuf:"bytes,2,opt,name=QueryID,proto3" json:"QueryID,omitempty"`
	BucketName           string         `protobuf:"bytes,3,opt,name=BucketName,proto3" json:"BucketName,omitempty"`
	ObjectName           string         `protobuf:"bytes,4,opt,name=ObjectName,proto3" json:"ObjectName,omitempty"`
	BucketID             int64          `protobuf:"varint,5,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	BOpts                *BucketOptions `protobuf:"bytes,6,opt,name=BOpts,proto3" json:"BOpts,omitempty"`
	OParts               []*ObjectPart  `protobuf:"bytes,7,rep,name=OParts,proto3" json:"OParts,omitempty"`
	DecKey               []byte         `protobuf:"bytes,8,opt,name=DecKey,proto3" json:"DecKey,omitempty"`
	KPs                  string         `protobuf:"bytes,11,opt,name=KPs,proto3" json:"KPs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShareLink) Reset()         { *m = ShareLink{} }
func (m *ShareLink) String() string { return proto.CompactTextString(m) }
func (*ShareLink) ProtoMessage()    {}
func (*ShareLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{10}
}
func (m *ShareLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareLink.Unmarshal(m, b)
}
func (m *ShareLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareLink.Marshal(b, m, deterministic)
}
func (m *ShareLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareLink.Merge(m, src)
}
func (m *ShareLink) XXX_Size() int {
	return xxx_messageInfo_ShareLink.Size(m)
}
func (m *ShareLink) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareLink.DiscardUnknown(m)
}

var xxx_messageInfo_ShareLink proto.InternalMessageInfo

func (m *ShareLink) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ShareLink) GetQueryID() string {
	if m != nil {
		return m.QueryID
	}
	return ""
}

func (m *ShareLink) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *ShareLink) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

func (m *ShareLink) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *ShareLink) GetBOpts() *BucketOptions {
	if m != nil {
		return m.BOpts
	}
	return nil
}

func (m *ShareLink) GetOParts() []*ObjectPart {
	if m != nil {
		return m.OParts
	}
	return nil
}

func (m *ShareLink) GetDecKey() []byte {
	if m != nil {
		return m.DecKey
	}
	return nil
}

func (m *ShareLink) GetKPs() string {
	if m != nil {
		return m.KPs
	}
	return ""
}

type ChalInfo struct {
	QueryID              string   `protobuf:"bytes,1,opt,name=QueryID,proto3" json:"QueryID,omitempty"`
	KeeperID             string   `protobuf:"bytes,2,opt,name=KeeperID,proto3" json:"KeeperID,omitempty"`
	ProviderID           string   `protobuf:"bytes,3,opt,name=ProviderID,proto3" json:"ProviderID,omitempty"`
	UserID               string   `protobuf:"bytes,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ChalTime             int64    `protobuf:"varint,5,opt,name=ChalTime,proto3" json:"ChalTime,omitempty"`
	ChalLength           int64    `protobuf:"varint,6,opt,name=ChalLength,proto3" json:"ChalLength,omitempty"`
	SuccessLength        int64    `protobuf:"varint,7,opt,name=SuccessLength,proto3" json:"SuccessLength,omitempty"`
	TotalLength          int64    `protobuf:"varint,8,opt,name=TotalLength,proto3" json:"TotalLength,omitempty"`
	Blocks               []string `protobuf:"bytes,9,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
	FaultBlocks          []string `protobuf:"bytes,10,rep,name=FaultBlocks,proto3" json:"FaultBlocks,omitempty"`
	BlsProof             string   `protobuf:"bytes,11,opt,name=BlsProof,proto3" json:"BlsProof,omitempty"`
	Res                  bool     `protobuf:"varint,12,opt,name=Res,proto3" json:"Res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChalInfo) Reset()         { *m = ChalInfo{} }
func (m *ChalInfo) String() string { return proto.CompactTextString(m) }
func (*ChalInfo) ProtoMessage()    {}
func (*ChalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{11}
}
func (m *ChalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChalInfo.Unmarshal(m, b)
}
func (m *ChalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChalInfo.Marshal(b, m, deterministic)
}
func (m *ChalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChalInfo.Merge(m, src)
}
func (m *ChalInfo) XXX_Size() int {
	return xxx_messageInfo_ChalInfo.Size(m)
}
func (m *ChalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChalInfo proto.InternalMessageInfo

func (m *ChalInfo) GetQueryID() string {
	if m != nil {
		return m.QueryID
	}
	return ""
}

func (m *ChalInfo) GetKeeperID() string {
	if m != nil {
		return m.KeeperID
	}
	return ""
}

func (m *ChalInfo) GetProviderID() string {
	if m != nil {
		return m.ProviderID
	}
	return ""
}

func (m *ChalInfo) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ChalInfo) GetChalTime() int64 {
	if m != nil {
		return m.ChalTime
	}
	return 0
}

func (m *ChalInfo) GetChalLength() int64 {
	if m != nil {
		return m.ChalLength
	}
	return 0
}

func (m *ChalInfo) GetSuccessLength() int64 {
	if m != nil {
		return m.SuccessLength
	}
	return 0
}

func (m *ChalInfo) GetTotalLength() int64 {
	if m != nil {
		return m.TotalLength
	}
	return 0
}

func (m *ChalInfo) GetBlocks() []string {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *ChalInfo) GetFaultBlocks() []string {
	if m != nil {
		return m.FaultBlocks
	}
	return nil
}

func (m *ChalInfo) GetBlsProof() string {
	if m != nil {
		return m.BlsProof
	}
	return ""
}

func (m *ChalInfo) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

type ChannelSign struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Sig                  []byte   `protobuf:"bytes,3,opt,name=Sig,proto3" json:"Sig,omitempty"`
	PubKey               []byte   `protobuf:"bytes,4,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelSign) Reset()         { *m = ChannelSign{} }
func (m *ChannelSign) String() string { return proto.CompactTextString(m) }
func (*ChannelSign) ProtoMessage()    {}
func (*ChannelSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{12}
}
func (m *ChannelSign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelSign.Unmarshal(m, b)
}
func (m *ChannelSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelSign.Marshal(b, m, deterministic)
}
func (m *ChannelSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelSign.Merge(m, src)
}
func (m *ChannelSign) XXX_Size() int {
	return xxx_messageInfo_ChannelSign.Size(m)
}
func (m *ChannelSign) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelSign.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelSign proto.InternalMessageInfo

func (m *ChannelSign) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *ChannelSign) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ChannelSign) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *ChannelSign) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type KVData struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVData) Reset()         { *m = KVData{} }
func (m *KVData) String() string { return proto.CompactTextString(m) }
func (*KVData) ProtoMessage()    {}
func (*KVData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{13}
}
func (m *KVData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVData.Unmarshal(m, b)
}
func (m *KVData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVData.Marshal(b, m, deterministic)
}
func (m *KVData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVData.Merge(m, src)
}
func (m *KVData) XXX_Size() int {
	return xxx_messageInfo_KVData.Size(m)
}
func (m *KVData) XXX_DiscardUnknown() {
	xxx_messageInfo_KVData.DiscardUnknown(m)
}

var xxx_messageInfo_KVData proto.InternalMessageInfo

func (m *KVData) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KVData) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.OpType", OpType_name, OpType_value)
	proto.RegisterEnum("proto.KeyType", KeyType_name, KeyType_value)
	proto.RegisterType((*KeyMeta)(nil), "proto.KeyMeta")
	proto.RegisterType((*UserBLS12Config)(nil), "proto.UserBLS12Config")
	proto.RegisterType((*BucketRoot)(nil), "proto.BucketRoot")
	proto.RegisterType((*LfsRoot)(nil), "proto.LfsRoot")
	proto.RegisterType((*SuperBlockInfo)(nil), "proto.SuperBlockInfo")
	proto.RegisterType((*BucketOptions)(nil), "proto.BucketOptions")
	proto.RegisterType((*BucketInfo)(nil), "proto.BucketInfo")
	proto.RegisterType((*ObjectInfo)(nil), "proto.ObjectInfo")
	proto.RegisterMapType((map[string]string)(nil), "proto.ObjectInfo.MetadataEntry")
	proto.RegisterType((*ObjectPart)(nil), "proto.ObjectPart")
	proto.RegisterType((*BlockOptions)(nil), "proto.BlockOptions")
	proto.RegisterType((*ShareLink)(nil), "proto.ShareLink")
	proto.RegisterType((*ChalInfo)(nil), "proto.ChalInfo")
	proto.RegisterType((*ChannelSign)(nil), "proto.ChannelSign")
	proto.RegisterType((*KVData)(nil), "proto.KVData")
}

func init() { proto.RegisterFile("mefs.proto", fileDescriptor_2b3c77393cf6fe78) }

var fileDescriptor_2b3c77393cf6fe78 = []byte{
	// 1372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x56, 0xcd, 0x92, 0xdb, 0xc4,
	0x13, 0x8f, 0x2c, 0xcb, 0x1f, 0x6d, 0xef, 0x66, 0xfe, 0xfa, 0x2f, 0x41, 0x2c, 0xa9, 0xc4, 0xa8,
	0x52, 0x85, 0xb3, 0x87, 0x14, 0x2c, 0x17, 0x8a, 0x9c, 0x62, 0x7b, 0x13, 0xb6, 0xec, 0x64, 0xcd,
	0x68, 0xf3, 0x71, 0x4a, 0x95, 0xd6, 0x1e, 0x7b, 0x85, 0x15, 0x49, 0x25, 0x8d, 0x52, 0x31, 0x07,
	0xaa, 0xe0, 0x31, 0x78, 0x03, 0xee, 0x3c, 0x06, 0xbc, 0x05, 0x2f, 0xc1, 0x8d, 0xea, 0x9e, 0xd1,
	0x87, 0x97, 0x65, 0x39, 0xb9, 0x7f, 0xdd, 0x33, 0x3d, 0xd3, 0xbf, 0xfe, 0x4d, 0xcb, 0x00, 0xef,
	0xc4, 0x2a, 0x7b, 0x94, 0xa4, 0xb1, 0x8c, 0x6d, 0x8b, 0x7e, 0xdc, 0x1c, 0xda, 0x53, 0xb1, 0x7d,
	0x2e, 0xa4, 0x6f, 0x3b, 0xd0, 0x7e, 0x25, 0xd2, 0x2c, 0x88, 0x23, 0xc7, 0x18, 0x18, 0x43, 0x8b,
	0x17, 0xd0, 0x7e, 0x00, 0xd6, 0xf4, 0x7c, 0x9b, 0x08, 0xa7, 0x31, 0x30, 0x86, 0xfb, 0xc7, 0xfb,
	0x2a, 0xc5, 0xa3, 0xa9, 0xd8, 0xa2, 0x97, 0xab, 0xa0, 0xcd, 0xc0, 0x7c, 0x1e, 0x2c, 0x1d, 0x73,
	0x60, 0x0c, 0xbb, 0x1c, 0x4d, 0xcc, 0x78, 0x96, 0xc8, 0x20, 0x8e, 0x32, 0xa7, 0x39, 0x30, 0x87,
	0x5d, 0x5e, 0x40, 0xf7, 0x57, 0x03, 0x6e, 0xbf, 0xcc, 0x44, 0x3a, 0x9a, 0x79, 0x5f, 0x1e, 0x8f,
	0xe3, 0x68, 0x15, 0xac, 0xed, 0xbb, 0xd0, 0x4d, 0xf2, 0x8b, 0x8d, 0xd8, 0x8e, 0xc2, 0x8c, 0x4e,
	0xea, 0xf3, 0xca, 0x81, 0xb9, 0x14, 0x78, 0x46, 0x27, 0xf4, 0x79, 0x01, 0xab, 0xc8, 0x4b, 0x3a,
	0xa5, 0x8c, 0xbc, 0xac, 0x22, 0xaf, 0x1d, 0xab, 0x1e, 0x79, 0x4d, 0x67, 0xa5, 0x81, 0x3e, 0xab,
	0xa5, 0xcf, 0x2a, 0x1c, 0x76, 0x1f, 0x8c, 0x37, 0x4e, 0x9b, 0xbc, 0xc6, 0x1b, 0xf7, 0x2d, 0xc0,
	0x28, 0x5f, 0x6c, 0x84, 0xe4, 0x71, 0x2c, 0xed, 0x43, 0xe8, 0x28, 0x74, 0x3a, 0x21, 0x9a, 0x4c,
	0x5e, 0x62, 0x7b, 0x00, 0xbd, 0xb3, 0x8b, 0xef, 0xc5, 0x42, 0x8e, 0xe3, 0x3c, 0x92, 0x54, 0x83,
	0xc9, 0xeb, 0x2e, 0xdb, 0x86, 0x26, 0x66, 0xd1, 0x25, 0x90, 0xed, 0xbe, 0x85, 0xf6, 0x6c, 0x95,
	0x51, 0xf2, 0x03, 0xb0, 0xc6, 0xe7, 0xc1, 0x3b, 0xa1, 0x33, 0x2b, 0x50, 0x6e, 0x6a, 0x54, 0x9b,
	0xec, 0x87, 0xd0, 0x1a, 0xa1, 0x91, 0x39, 0xe6, 0xc0, 0x1c, 0xf6, 0x8e, 0xff, 0xa7, 0x7b, 0x52,
	0xdd, 0x94, 0xeb, 0x05, 0xee, 0x6f, 0x06, 0xec, 0x7b, 0x79, 0x22, 0xd2, 0x51, 0x18, 0x2f, 0x36,
	0xa7, 0xd1, 0x2a, 0xbe, 0xa1, 0xd5, 0x43, 0xb8, 0x8d, 0x62, 0x18, 0xf9, 0x8b, 0x4d, 0x9e, 0x54,
	0x65, 0x58, 0xfc, 0xaa, 0xbb, 0xba, 0xab, 0x59, 0xbf, 0xab, 0x0b, 0xfd, 0x17, 0xe2, 0x83, 0x2c,
	0x29, 0x6a, 0x52, 0x70, 0xc7, 0x87, 0x72, 0x9a, 0x51, 0x41, 0x6d, 0xba, 0x7a, 0x21, 0x27, 0x4d,
	0x02, 0x57, 0x41, 0xf7, 0xa7, 0x06, 0xec, 0xa9, 0x2d, 0x5a, 0x34, 0x37, 0xdc, 0xfa, 0x0e, 0xb4,
	0xe6, 0x71, 0x18, 0x2c, 0xb6, 0xfa, 0xb2, 0x1a, 0x61, 0x9b, 0x27, 0xbe, 0xf4, 0x55, 0x1d, 0x26,
	0x85, 0x2a, 0x07, 0xb6, 0x6b, 0xee, 0xa7, 0x81, 0xdc, 0xaa, 0x78, 0x93, 0xe2, 0x75, 0x17, 0x9e,
	0x78, 0xee, 0xaf, 0x9f, 0x86, 0xfe, 0xda, 0xb1, 0xd4, 0x89, 0x1a, 0xe2, 0x5e, 0x4f, 0xac, 0xdf,
	0x89, 0x48, 0x7a, 0xc1, 0x0f, 0x82, 0x24, 0x64, 0xf1, 0xba, 0x0b, 0x99, 0xd0, 0x50, 0xa5, 0x6f,
	0xd3, 0x92, 0x1d, 0x9f, 0x7d, 0x0f, 0xe0, 0x24, 0x5a, 0xa4, 0x5b, 0x2a, 0xd0, 0xe9, 0xd0, 0x8a,
	0x9a, 0xc7, 0xfd, 0xbd, 0x51, 0x68, 0x8f, 0xda, 0x66, 0x43, 0xf3, 0x85, 0xaf, 0xd5, 0xd1, 0xe5,
	0x64, 0xef, 0xe8, 0xb1, 0x71, 0x45, 0x8f, 0xd8, 0x22, 0x59, 0x6f, 0x11, 0x02, 0xfb, 0x08, 0xac,
	0xd1, 0x59, 0x22, 0x33, 0x2a, 0xb8, 0x77, 0x7c, 0xb0, 0xa3, 0x1c, 0xcd, 0x35, 0x57, 0x4b, 0x90,
	0xc0, 0x71, 0x9e, 0x7a, 0x32, 0x0d, 0x12, 0x41, 0x14, 0x98, 0xbc, 0x72, 0x20, 0x3d, 0xd8, 0x58,
	0x4f, 0xac, 0x89, 0x00, 0x93, 0x17, 0x10, 0x4f, 0x7e, 0x4e, 0xe2, 0x68, 0xab, 0x93, 0x09, 0xd8,
	0x47, 0xc0, 0xd4, 0x63, 0xc8, 0x48, 0x8a, 0xc4, 0x5c, 0x87, 0x16, 0xfc, 0xc3, 0x8f, 0x75, 0x4d,
	0x44, 0x28, 0x88, 0x98, 0xee, 0xc0, 0x18, 0x76, 0x78, 0x89, 0x0b, 0x91, 0xa9, 0x3d, 0xa7, 0x13,
	0x07, 0x2a, 0x91, 0x15, 0xbe, 0xf2, 0xd1, 0xf4, 0x6a, 0x2f, 0xed, 0x8f, 0x06, 0x80, 0x5e, 0x80,
	0x74, 0xde, 0xf4, 0x94, 0x4b, 0xea, 0x1a, 0x75, 0xea, 0x06, 0xd0, 0x1b, 0xc7, 0x91, 0x14, 0x91,
	0xa4, 0x71, 0xa8, 0x46, 0x5d, 0xdd, 0x85, 0x43, 0x70, 0x12, 0xa4, 0x44, 0x6d, 0x87, 0xa3, 0xb9,
	0x53, 0x88, 0x75, 0xa5, 0x90, 0xc7, 0xd0, 0xc1, 0x67, 0xb5, 0xf4, 0xa5, 0xef, 0xb4, 0xe8, 0x31,
	0xdc, 0xd7, 0xdd, 0xa8, 0xae, 0xf9, 0xa8, 0x58, 0x71, 0x12, 0xc9, 0x74, 0xcb, 0xcb, 0x0d, 0x98,
	0xb8, 0x64, 0x40, 0xd1, 0x5c, 0x62, 0xfb, 0x73, 0xb0, 0xce, 0xe6, 0x7e, 0x2a, 0x89, 0xde, 0x6a,
	0x3a, 0xa8, 0x38, 0x06, 0xb8, 0x8a, 0x1f, 0x3e, 0x86, 0xbd, 0x9d, 0xfc, 0x58, 0xc0, 0x46, 0x6c,
	0xb5, 0xc4, 0xd0, 0x44, 0x2a, 0xde, 0xfb, 0x61, 0xae, 0xa8, 0xe8, 0x72, 0x05, 0xbe, 0x69, 0x7c,
	0x6d, 0xb8, 0x3f, 0x16, 0x74, 0x62, 0xaa, 0x6b, 0xd5, 0x79, 0x00, 0x96, 0x27, 0xf1, 0x1e, 0x9a,
	0x46, 0x02, 0xf8, 0x5c, 0x67, 0x22, 0x5a, 0xcb, 0x4b, 0x2d, 0x4c, 0x8d, 0x30, 0xc3, 0xc9, 0xb9,
	0xbf, 0x26, 0xf6, 0xba, 0x9c, 0x6c, 0xac, 0x12, 0xfb, 0x4a, 0xc5, 0x58, 0xe4, 0x2f, 0xb1, 0xfb,
	0xb3, 0x01, 0x7d, 0x52, 0x4c, 0x31, 0x21, 0x50, 0xda, 0x31, 0x4a, 0xdb, 0xb8, 0x51, 0xda, 0xb8,
	0x64, 0xf7, 0x6a, 0x56, 0xed, 0x6a, 0xf8, 0x5d, 0x3a, 0x9d, 0x90, 0x70, 0xba, 0x5c, 0x23, 0x94,
	0xfa, 0x77, 0xb9, 0x48, 0xb7, 0xa7, 0x13, 0xa7, 0x4f, 0x81, 0x02, 0xba, 0xbf, 0x34, 0xa0, 0xeb,
	0x5d, 0xfa, 0xa9, 0x98, 0x05, 0xd1, 0xa6, 0xb6, 0xdf, 0xf8, 0xb7, 0xfd, 0x8d, 0x9d, 0xfd, 0x38,
	0x03, 0xd4, 0xfd, 0x88, 0x3c, 0x25, 0xa9, 0x9a, 0x07, 0xe3, 0x8a, 0x64, 0x8a, 0x2b, 0x6a, 0x6a,
	0x9e, 0x1d, 0x15, 0x5b, 0x57, 0x54, 0x5c, 0x3e, 0xf5, 0xd6, 0x7f, 0x3f, 0xf5, 0x87, 0xd0, 0x22,
	0x49, 0x64, 0x7a, 0x2c, 0x5f, 0xa3, 0x19, 0xbd, 0x00, 0x8b, 0x9c, 0x88, 0xc5, 0x54, 0x6c, 0x49,
	0x5e, 0x7d, 0xae, 0x11, 0x6a, 0x67, 0x3a, 0xcf, 0x34, 0x73, 0x68, 0xba, 0x7f, 0x36, 0xa0, 0x33,
	0xbe, 0xf4, 0xc3, 0xe2, 0xab, 0x53, 0x70, 0x60, 0xec, 0x72, 0x70, 0x08, 0x9d, 0xa9, 0x10, 0x09,
	0xf1, 0xa6, 0xe8, 0x29, 0x31, 0xd6, 0x3f, 0x4f, 0xe3, 0xf7, 0xc1, 0x92, 0xa2, 0x9a, 0x9f, 0xca,
	0x53, 0x63, 0xbc, 0xb9, 0xc3, 0xf8, 0xa1, 0x3a, 0x99, 0xa6, 0x90, 0xe6, 0xa5, 0xc0, 0x98, 0x13,
	0x6d, 0x2d, 0x42, 0x35, 0xbb, 0x6a, 0x1e, 0xfb, 0x01, 0xec, 0x79, 0xf9, 0x62, 0x21, 0xb2, 0x4c,
	0x2f, 0x51, 0xef, 0x6b, 0xd7, 0x89, 0xd3, 0xe0, 0x3c, 0x96, 0x65, 0x1a, 0x35, 0xc9, 0xea, 0x2e,
	0xbc, 0x1b, 0xe9, 0x33, 0x73, 0xba, 0xf4, 0xff, 0x47, 0x23, 0xdc, 0xf9, 0xd4, 0xcf, 0x43, 0xa9,
	0x83, 0x40, 0xc1, 0xba, 0x8b, 0xba, 0x1a, 0x66, 0xf3, 0x34, 0x8e, 0x57, 0x9a, 0xcf, 0x12, 0x23,
	0xcd, 0x5c, 0x64, 0xa4, 0xc3, 0x0e, 0x47, 0xd3, 0xdd, 0x40, 0x6f, 0x7c, 0xe9, 0x47, 0x91, 0x08,
	0xbd, 0x60, 0x1d, 0xd1, 0xd4, 0x56, 0xb0, 0xa4, 0xba, 0x72, 0xa0, 0xf0, 0x5f, 0x95, 0xef, 0xb9,
	0xcf, 0x15, 0xc0, 0xa4, 0x5e, 0xb0, 0xd6, 0x7f, 0x4c, 0xd0, 0xa4, 0x8f, 0x6a, 0x7e, 0x81, 0x5d,
	0x6e, 0xaa, 0x2e, 0x2b, 0xe4, 0x7e, 0x01, 0xad, 0xe9, 0x2b, 0xfc, 0x8a, 0x52, 0xbf, 0xf5, 0xac,
	0xe8, 0x73, 0x34, 0xaf, 0xcf, 0x7d, 0xf4, 0x04, 0x5a, 0x67, 0x09, 0x8d, 0xc7, 0x3d, 0xe8, 0x8e,
	0xd2, 0xd8, 0x5f, 0x8e, 0xfd, 0x4c, 0xb2, 0x5b, 0x76, 0x1b, 0xcc, 0x79, 0x2e, 0x99, 0x81, 0xc6,
	0x33, 0x21, 0x59, 0xc3, 0x06, 0x68, 0x3d, 0x49, 0x12, 0x11, 0x2d, 0x99, 0x89, 0x36, 0x4d, 0x4a,
	0xc1, 0x9a, 0x47, 0x7f, 0x35, 0xe8, 0x8f, 0x2a, 0x25, 0xe9, 0x82, 0xf5, 0x3a, 0x8d, 0xa3, 0x35,
	0xbb, 0x65, 0x77, 0x70, 0xca, 0x87, 0x82, 0x19, 0x98, 0x79, 0x9e, 0x5f, 0x84, 0x01, 0x0a, 0x51,
	0xe5, 0x51, 0x7f, 0x2b, 0x99, 0x89, 0xc9, 0x67, 0x4f, 0x3d, 0xd6, 0xc4, 0x8d, 0x28, 0x8e, 0x8c,
	0x59, 0x76, 0x0f, 0xd3, 0xa1, 0xc2, 0x32, 0xd6, 0xa2, 0xbd, 0x5a, 0x50, 0x19, 0x6b, 0xe3, 0x32,
	0xea, 0x02, 0x03, 0xbb, 0x8f, 0x6d, 0x88, 0x17, 0x9b, 0x79, 0x9c, 0xb1, 0x1e, 0xa2, 0x42, 0x42,
	0xac, 0x4f, 0x97, 0x8f, 0x33, 0xb6, 0x87, 0xdb, 0xbf, 0x15, 0x7e, 0x2a, 0x47, 0xc2, 0x97, 0xec,
	0x00, 0x57, 0x91, 0x04, 0xa3, 0x40, 0xb2, 0x8f, 0xec, 0x7d, 0x00, 0x44, 0x2f, 0x62, 0x19, 0xac,
	0xb6, 0xec, 0x0e, 0x2e, 0x46, 0x4c, 0xd3, 0x86, 0x7d, 0x5c, 0x2c, 0xf6, 0x64, 0x9c, 0x30, 0x07,
	0x83, 0x78, 0x40, 0x28, 0xa2, 0xb5, 0x60, 0x9f, 0x60, 0x11, 0x5c, 0x24, 0x7e, 0x90, 0xb2, 0x43,
	0xfb, 0xff, 0x70, 0xfb, 0xe4, 0x83, 0x14, 0x69, 0xe4, 0x87, 0x4f, 0x96, 0xcb, 0x54, 0x64, 0x19,
	0xfb, 0x14, 0xab, 0xf0, 0x64, 0x9c, 0xfa, 0x6b, 0xc1, 0xee, 0xe2, 0xb5, 0xe9, 0x3d, 0xb1, 0x7b,
	0x68, 0x9e, 0xad, 0x56, 0x22, 0x65, 0xf7, 0xe9, 0xbc, 0x04, 0x4b, 0x0d, 0xa2, 0x35, 0x1b, 0xe0,
	0x0e, 0xad, 0x04, 0xf6, 0x99, 0x06, 0xe1, 0xdc, 0xdf, 0xb2, 0x21, 0x82, 0x99, 0x9f, 0x49, 0x04,
	0x0f, 0x11, 0xcc, 0xe3, 0x0c, 0xbf, 0x0c, 0xec, 0xe8, 0xa2, 0x45, 0x83, 0xe0, 0xab, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x19, 0xde, 0xe0, 0xe9, 0x3f, 0x0c, 0x00, 0x00,
}
