// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mefs.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OpType int32

const (
	OpType_BroadCast OpType = 0
	OpType_Put       OpType = 1
	OpType_Get       OpType = 2
	OpType_Append    OpType = 3
	OpType_Delete    OpType = 4
)

var OpType_name = map[int32]string{
	0: "BroadCast",
	1: "Put",
	2: "Get",
	3: "Append",
	4: "Delete",
}

var OpType_value = map[string]int32{
	"BroadCast": 0,
	"Put":       1,
	"Get":       2,
	"Append":    3,
	"Delete":    4,
}

func (x OpType) String() string {
	return proto.EnumName(OpType_name, int32(x))
}

func (OpType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{0}
}

type KeyType int32

const (
	KeyType_Wrong           KeyType = 0
	KeyType_Role            KeyType = 1
	KeyType_PublicKey       KeyType = 2
	KeyType_Config          KeyType = 3
	KeyType_LFS             KeyType = 4
	KeyType_Users           KeyType = 5
	KeyType_Keepers         KeyType = 6
	KeyType_Providers       KeyType = 7
	KeyType_Block           KeyType = 10
	KeyType_BlockPos        KeyType = 11
	KeyType_ChalTime        KeyType = 12
	KeyType_Pos             KeyType = 13
	KeyType_Bucket          KeyType = 14
	KeyType_Session         KeyType = 15
	KeyType_HeartBeat       KeyType = 20
	KeyType_UserInit        KeyType = 21
	KeyType_UserNotify      KeyType = 22
	KeyType_UserStart       KeyType = 23
	KeyType_UserStop        KeyType = 24
	KeyType_Challenge       KeyType = 25
	KeyType_Repair          KeyType = 26
	KeyType_ExternalAddress KeyType = 27
	KeyType_Storage         KeyType = 28
	KeyType_Query           KeyType = 30
	KeyType_Offer           KeyType = 31
	KeyType_UpKeeping       KeyType = 32
	KeyType_Channel         KeyType = 33
	KeyType_ChalPay         KeyType = 40
	KeyType_LastPay         KeyType = 41
	KeyType_PosMeta         KeyType = 42
	KeyType_Sign            KeyType = 43
)

var KeyType_name = map[int32]string{
	0:  "Wrong",
	1:  "Role",
	2:  "PublicKey",
	3:  "Config",
	4:  "LFS",
	5:  "Users",
	6:  "Keepers",
	7:  "Providers",
	10: "Block",
	11: "BlockPos",
	12: "ChalTime",
	13: "Pos",
	14: "Bucket",
	15: "Session",
	20: "HeartBeat",
	21: "UserInit",
	22: "UserNotify",
	23: "UserStart",
	24: "UserStop",
	25: "Challenge",
	26: "Repair",
	27: "ExternalAddress",
	28: "Storage",
	30: "Query",
	31: "Offer",
	32: "UpKeeping",
	33: "Channel",
	40: "ChalPay",
	41: "LastPay",
	42: "PosMeta",
	43: "Sign",
}

var KeyType_value = map[string]int32{
	"Wrong":           0,
	"Role":            1,
	"PublicKey":       2,
	"Config":          3,
	"LFS":             4,
	"Users":           5,
	"Keepers":         6,
	"Providers":       7,
	"Block":           10,
	"BlockPos":        11,
	"ChalTime":        12,
	"Pos":             13,
	"Bucket":          14,
	"Session":         15,
	"HeartBeat":       20,
	"UserInit":        21,
	"UserNotify":      22,
	"UserStart":       23,
	"UserStop":        24,
	"Challenge":       25,
	"Repair":          26,
	"ExternalAddress": 27,
	"Storage":         28,
	"Query":           30,
	"Offer":           31,
	"UpKeeping":       32,
	"Channel":         33,
	"ChalPay":         40,
	"LastPay":         41,
	"PosMeta":         42,
	"Sign":            43,
}

func (x KeyType) String() string {
	return proto.EnumName(KeyType_name, int32(x))
}

func (KeyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{1}
}

type LfsOp int32

const (
	LfsOp_OpErr    LfsOp = 0
	LfsOp_OpAdd    LfsOp = 1
	LfsOp_OpAppend LfsOp = 2
	LfsOp_OpDelete LfsOp = 3
	LfsOp_OpCancel LfsOp = 4
)

var LfsOp_name = map[int32]string{
	0: "OpErr",
	1: "OpAdd",
	2: "OpAppend",
	3: "OpDelete",
	4: "OpCancel",
}

var LfsOp_value = map[string]int32{
	"OpErr":    0,
	"OpAdd":    1,
	"OpAppend": 2,
	"OpDelete": 3,
	"OpCancel": 4,
}

func (x LfsOp) String() string {
	return proto.EnumName(LfsOp_name, int32(x))
}

func (LfsOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{2}
}

type KeyMeta struct {
	Version              int32    `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	KType                KeyType  `protobuf:"varint,2,opt,name=KType,proto3,enum=proto.KeyType" json:"KType,omitempty"`
	Mid                  string   `protobuf:"bytes,3,opt,name=Mid,proto3" json:"Mid,omitempty"`
	Options              []string `protobuf:"bytes,4,rep,name=Options,proto3" json:"Options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyMeta) Reset()         { *m = KeyMeta{} }
func (m *KeyMeta) String() string { return proto.CompactTextString(m) }
func (*KeyMeta) ProtoMessage()    {}
func (*KeyMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{0}
}
func (m *KeyMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyMeta.Unmarshal(m, b)
}
func (m *KeyMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyMeta.Marshal(b, m, deterministic)
}
func (m *KeyMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyMeta.Merge(m, src)
}
func (m *KeyMeta) XXX_Size() int {
	return xxx_messageInfo_KeyMeta.Size(m)
}
func (m *KeyMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyMeta.DiscardUnknown(m)
}

var xxx_messageInfo_KeyMeta proto.InternalMessageInfo

func (m *KeyMeta) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *KeyMeta) GetKType() KeyType {
	if m != nil {
		return m.KType
	}
	return KeyType_Wrong
}

func (m *KeyMeta) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *KeyMeta) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

type UserBLS12Config struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PubkeyBls            []byte   `protobuf:"bytes,2,opt,name=pubkeyBls,proto3" json:"pubkeyBls,omitempty"`
	PubkeyG              []byte   `protobuf:"bytes,3,opt,name=pubkeyG,proto3" json:"pubkeyG,omitempty"`
	PubkeyU              [][]byte `protobuf:"bytes,4,rep,name=pubkeyU,proto3" json:"pubkeyU,omitempty"`
	PubkeyW              [][]byte `protobuf:"bytes,5,rep,name=pubkeyW,proto3" json:"pubkeyW,omitempty"`
	PrikeyBls            []byte   `protobuf:"bytes,6,opt,name=prikeyBls,proto3" json:"prikeyBls,omitempty"`
	X                    []byte   `protobuf:"bytes,7,opt,name=X,proto3" json:"X,omitempty"`
	Count                int32    `protobuf:"varint,10,opt,name=count,proto3" json:"count,omitempty"`
	TagCount             int32    `protobuf:"varint,11,opt,name=tagCount,proto3" json:"tagCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBLS12Config) Reset()         { *m = UserBLS12Config{} }
func (m *UserBLS12Config) String() string { return proto.CompactTextString(m) }
func (*UserBLS12Config) ProtoMessage()    {}
func (*UserBLS12Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{1}
}
func (m *UserBLS12Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBLS12Config.Unmarshal(m, b)
}
func (m *UserBLS12Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBLS12Config.Marshal(b, m, deterministic)
}
func (m *UserBLS12Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBLS12Config.Merge(m, src)
}
func (m *UserBLS12Config) XXX_Size() int {
	return xxx_messageInfo_UserBLS12Config.Size(m)
}
func (m *UserBLS12Config) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBLS12Config.DiscardUnknown(m)
}

var xxx_messageInfo_UserBLS12Config proto.InternalMessageInfo

func (m *UserBLS12Config) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UserBLS12Config) GetPubkeyBls() []byte {
	if m != nil {
		return m.PubkeyBls
	}
	return nil
}

func (m *UserBLS12Config) GetPubkeyG() []byte {
	if m != nil {
		return m.PubkeyG
	}
	return nil
}

func (m *UserBLS12Config) GetPubkeyU() [][]byte {
	if m != nil {
		return m.PubkeyU
	}
	return nil
}

func (m *UserBLS12Config) GetPubkeyW() [][]byte {
	if m != nil {
		return m.PubkeyW
	}
	return nil
}

func (m *UserBLS12Config) GetPrikeyBls() []byte {
	if m != nil {
		return m.PrikeyBls
	}
	return nil
}

func (m *UserBLS12Config) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *UserBLS12Config) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *UserBLS12Config) GetTagCount() int32 {
	if m != nil {
		return m.TagCount
	}
	return 0
}

type BucketRoot struct {
	BucketID             int64    `protobuf:"varint,1,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	OpCount              int64    `protobuf:"varint,2,opt,name=OpCount,proto3" json:"OpCount,omitempty"`
	Root                 []byte   `protobuf:"bytes,3,opt,name=Root,proto3" json:"Root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketRoot) Reset()         { *m = BucketRoot{} }
func (m *BucketRoot) String() string { return proto.CompactTextString(m) }
func (*BucketRoot) ProtoMessage()    {}
func (*BucketRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{2}
}
func (m *BucketRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketRoot.Unmarshal(m, b)
}
func (m *BucketRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketRoot.Marshal(b, m, deterministic)
}
func (m *BucketRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketRoot.Merge(m, src)
}
func (m *BucketRoot) XXX_Size() int {
	return xxx_messageInfo_BucketRoot.Size(m)
}
func (m *BucketRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketRoot.DiscardUnknown(m)
}

var xxx_messageInfo_BucketRoot proto.InternalMessageInfo

func (m *BucketRoot) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *BucketRoot) GetOpCount() int64 {
	if m != nil {
		return m.OpCount
	}
	return 0
}

func (m *BucketRoot) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

type LfsRoot struct {
	CTime                int64         `protobuf:"varint,1,opt,name=CTime,proto3" json:"CTime,omitempty"`
	Root                 []byte        `protobuf:"bytes,2,opt,name=Root,proto3" json:"Root,omitempty"`
	BRoots               []*BucketRoot `protobuf:"bytes,3,rep,name=BRoots,proto3" json:"BRoots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LfsRoot) Reset()         { *m = LfsRoot{} }
func (m *LfsRoot) String() string { return proto.CompactTextString(m) }
func (*LfsRoot) ProtoMessage()    {}
func (*LfsRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{3}
}
func (m *LfsRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LfsRoot.Unmarshal(m, b)
}
func (m *LfsRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LfsRoot.Marshal(b, m, deterministic)
}
func (m *LfsRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LfsRoot.Merge(m, src)
}
func (m *LfsRoot) XXX_Size() int {
	return xxx_messageInfo_LfsRoot.Size(m)
}
func (m *LfsRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_LfsRoot.DiscardUnknown(m)
}

var xxx_messageInfo_LfsRoot proto.InternalMessageInfo

func (m *LfsRoot) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *LfsRoot) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *LfsRoot) GetBRoots() []*BucketRoot {
	if m != nil {
		return m.BRoots
	}
	return nil
}

type SuperBlockInfo struct {
	Version              int32      `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	MetaBackupCount      int32      `protobuf:"varint,2,opt,name=MetaBackupCount,proto3" json:"MetaBackupCount,omitempty"`
	CTime                int64      `protobuf:"varint,3,opt,name=CTime,proto3" json:"CTime,omitempty"`
	NextBucketID         int64      `protobuf:"varint,4,opt,name=NextBucketID,proto3" json:"NextBucketID,omitempty"`
	LRoot                []*LfsRoot `protobuf:"bytes,7,rep,name=LRoot,proto3" json:"LRoot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SuperBlockInfo) Reset()         { *m = SuperBlockInfo{} }
func (m *SuperBlockInfo) String() string { return proto.CompactTextString(m) }
func (*SuperBlockInfo) ProtoMessage()    {}
func (*SuperBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{4}
}
func (m *SuperBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperBlockInfo.Unmarshal(m, b)
}
func (m *SuperBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperBlockInfo.Marshal(b, m, deterministic)
}
func (m *SuperBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperBlockInfo.Merge(m, src)
}
func (m *SuperBlockInfo) XXX_Size() int {
	return xxx_messageInfo_SuperBlockInfo.Size(m)
}
func (m *SuperBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SuperBlockInfo proto.InternalMessageInfo

func (m *SuperBlockInfo) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SuperBlockInfo) GetMetaBackupCount() int32 {
	if m != nil {
		return m.MetaBackupCount
	}
	return 0
}

func (m *SuperBlockInfo) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *SuperBlockInfo) GetNextBucketID() int64 {
	if m != nil {
		return m.NextBucketID
	}
	return 0
}

func (m *SuperBlockInfo) GetLRoot() []*LfsRoot {
	if m != nil {
		return m.LRoot
	}
	return nil
}

type BucketOptions struct {
	Version              int32    `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Policy               int32    `protobuf:"varint,2,opt,name=Policy,proto3" json:"Policy,omitempty"`
	DataCount            int32    `protobuf:"varint,3,opt,name=DataCount,proto3" json:"DataCount,omitempty"`
	ParityCount          int32    `protobuf:"varint,4,opt,name=ParityCount,proto3" json:"ParityCount,omitempty"`
	TagFlag              int32    `protobuf:"varint,5,opt,name=TagFlag,proto3" json:"TagFlag,omitempty"`
	SegmentSize          int32    `protobuf:"varint,6,opt,name=SegmentSize,proto3" json:"SegmentSize,omitempty"`
	SegmentCount         int32    `protobuf:"varint,7,opt,name=SegmentCount,proto3" json:"SegmentCount,omitempty"`
	Encryption           int32    `protobuf:"varint,8,opt,name=Encryption,proto3" json:"Encryption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketOptions) Reset()         { *m = BucketOptions{} }
func (m *BucketOptions) String() string { return proto.CompactTextString(m) }
func (*BucketOptions) ProtoMessage()    {}
func (*BucketOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{5}
}
func (m *BucketOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketOptions.Unmarshal(m, b)
}
func (m *BucketOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketOptions.Marshal(b, m, deterministic)
}
func (m *BucketOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketOptions.Merge(m, src)
}
func (m *BucketOptions) XXX_Size() int {
	return xxx_messageInfo_BucketOptions.Size(m)
}
func (m *BucketOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BucketOptions proto.InternalMessageInfo

func (m *BucketOptions) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BucketOptions) GetPolicy() int32 {
	if m != nil {
		return m.Policy
	}
	return 0
}

func (m *BucketOptions) GetDataCount() int32 {
	if m != nil {
		return m.DataCount
	}
	return 0
}

func (m *BucketOptions) GetParityCount() int32 {
	if m != nil {
		return m.ParityCount
	}
	return 0
}

func (m *BucketOptions) GetTagFlag() int32 {
	if m != nil {
		return m.TagFlag
	}
	return 0
}

func (m *BucketOptions) GetSegmentSize() int32 {
	if m != nil {
		return m.SegmentSize
	}
	return 0
}

func (m *BucketOptions) GetSegmentCount() int32 {
	if m != nil {
		return m.SegmentCount
	}
	return 0
}

func (m *BucketOptions) GetEncryption() int32 {
	if m != nil {
		return m.Encryption
	}
	return 0
}

type BucketInfo struct {
	Name                 string         `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	BucketID             int64          `protobuf:"varint,2,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	CTime                int64          `protobuf:"varint,3,opt,name=CTime,proto3" json:"CTime,omitempty"`
	BOpts                *BucketOptions `protobuf:"bytes,4,opt,name=BOpts,proto3" json:"BOpts,omitempty"`
	Length               int64          `protobuf:"varint,5,opt,name=Length,proto3" json:"Length,omitempty"`
	MTime                int64          `protobuf:"varint,7,opt,name=MTime,proto3" json:"MTime,omitempty"`
	ObjectsBlockSize     int64          `protobuf:"varint,8,opt,name=ObjectsBlockSize,proto3" json:"ObjectsBlockSize,omitempty"`
	Deletion             bool           `protobuf:"varint,9,opt,name=Deletion,proto3" json:"Deletion,omitempty"`
	NextObjectID         int64          `protobuf:"varint,10,opt,name=NextObjectID,proto3" json:"NextObjectID,omitempty"`
	NextOpID             int64          `protobuf:"varint,11,opt,name=NextOpID,proto3" json:"NextOpID,omitempty"`
	Root                 []byte         `protobuf:"bytes,12,opt,name=Root,proto3" json:"Root,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BucketInfo) Reset()         { *m = BucketInfo{} }
func (m *BucketInfo) String() string { return proto.CompactTextString(m) }
func (*BucketInfo) ProtoMessage()    {}
func (*BucketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{6}
}
func (m *BucketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketInfo.Unmarshal(m, b)
}
func (m *BucketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketInfo.Marshal(b, m, deterministic)
}
func (m *BucketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketInfo.Merge(m, src)
}
func (m *BucketInfo) XXX_Size() int {
	return xxx_messageInfo_BucketInfo.Size(m)
}
func (m *BucketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BucketInfo proto.InternalMessageInfo

func (m *BucketInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BucketInfo) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *BucketInfo) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *BucketInfo) GetBOpts() *BucketOptions {
	if m != nil {
		return m.BOpts
	}
	return nil
}

func (m *BucketInfo) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *BucketInfo) GetMTime() int64 {
	if m != nil {
		return m.MTime
	}
	return 0
}

func (m *BucketInfo) GetObjectsBlockSize() int64 {
	if m != nil {
		return m.ObjectsBlockSize
	}
	return 0
}

func (m *BucketInfo) GetDeletion() bool {
	if m != nil {
		return m.Deletion
	}
	return false
}

func (m *BucketInfo) GetNextObjectID() int64 {
	if m != nil {
		return m.NextObjectID
	}
	return 0
}

func (m *BucketInfo) GetNextOpID() int64 {
	if m != nil {
		return m.NextOpID
	}
	return 0
}

func (m *BucketInfo) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

//总共构建出ObjectInfo
type ObjectInfo struct {
	Info                 *Object       `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	Length               int64         `protobuf:"varint,2,opt,name=Length,proto3" json:"Length,omitempty"`
	CTime                int64         `protobuf:"varint,3,opt,name=CTime,proto3" json:"CTime,omitempty"`
	MTime                int64         `protobuf:"varint,4,opt,name=MTime,proto3" json:"MTime,omitempty"`
	PartCount            int64         `protobuf:"varint,5,opt,name=PartCount,proto3" json:"PartCount,omitempty"`
	ETag                 string        `protobuf:"bytes,6,opt,name=ETag,proto3" json:"ETag,omitempty"`
	Deletion             bool          `protobuf:"varint,7,opt,name=Deletion,proto3" json:"Deletion,omitempty"`
	Parts                []*ObjectPart `protobuf:"bytes,10,rep,name=Parts,proto3" json:"Parts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ObjectInfo) Reset()         { *m = ObjectInfo{} }
func (m *ObjectInfo) String() string { return proto.CompactTextString(m) }
func (*ObjectInfo) ProtoMessage()    {}
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{7}
}
func (m *ObjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectInfo.Unmarshal(m, b)
}
func (m *ObjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectInfo.Marshal(b, m, deterministic)
}
func (m *ObjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectInfo.Merge(m, src)
}
func (m *ObjectInfo) XXX_Size() int {
	return xxx_messageInfo_ObjectInfo.Size(m)
}
func (m *ObjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectInfo proto.InternalMessageInfo

func (m *ObjectInfo) GetInfo() *Object {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ObjectInfo) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ObjectInfo) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *ObjectInfo) GetMTime() int64 {
	if m != nil {
		return m.MTime
	}
	return 0
}

func (m *ObjectInfo) GetPartCount() int64 {
	if m != nil {
		return m.PartCount
	}
	return 0
}

func (m *ObjectInfo) GetETag() string {
	if m != nil {
		return m.ETag
	}
	return ""
}

func (m *ObjectInfo) GetDeletion() bool {
	if m != nil {
		return m.Deletion
	}
	return false
}

func (m *ObjectInfo) GetParts() []*ObjectPart {
	if m != nil {
		return m.Parts
	}
	return nil
}

//在add object的时候加入，
type Object struct {
	Name                 string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	BucketID             int64             `protobuf:"varint,2,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	CTime                int64             `protobuf:"varint,3,opt,name=CTime,proto3" json:"CTime,omitempty"`
	ObjectID             int64             `protobuf:"varint,4,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	Dir                  bool              `protobuf:"varint,5,opt,name=Dir,proto3" json:"Dir,omitempty"`
	ContentType          string            `protobuf:"bytes,9,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,10,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{8}
}
func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Object) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *Object) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *Object) GetObjectID() int64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *Object) GetDir() bool {
	if m != nil {
		return m.Dir
	}
	return false
}

func (m *Object) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Object) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

//在add object及append object的时候会加入
type ObjectPart struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ObjectID             int64    `protobuf:"varint,2,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	PartID               int64    `protobuf:"varint,3,opt,name=PartID,proto3" json:"PartID,omitempty"`
	Start                int64    `protobuf:"varint,4,opt,name=Start,proto3" json:"Start,omitempty"`
	Length               int64    `protobuf:"varint,5,opt,name=Length,proto3" json:"Length,omitempty"`
	CTime                int64    `protobuf:"varint,6,opt,name=CTime,proto3" json:"CTime,omitempty"`
	ETag                 string   `protobuf:"bytes,7,opt,name=ETag,proto3" json:"ETag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectPart) Reset()         { *m = ObjectPart{} }
func (m *ObjectPart) String() string { return proto.CompactTextString(m) }
func (*ObjectPart) ProtoMessage()    {}
func (*ObjectPart) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{9}
}
func (m *ObjectPart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectPart.Unmarshal(m, b)
}
func (m *ObjectPart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectPart.Marshal(b, m, deterministic)
}
func (m *ObjectPart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectPart.Merge(m, src)
}
func (m *ObjectPart) XXX_Size() int {
	return xxx_messageInfo_ObjectPart.Size(m)
}
func (m *ObjectPart) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectPart.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectPart proto.InternalMessageInfo

func (m *ObjectPart) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectPart) GetObjectID() int64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *ObjectPart) GetPartID() int64 {
	if m != nil {
		return m.PartID
	}
	return 0
}

func (m *ObjectPart) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ObjectPart) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ObjectPart) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *ObjectPart) GetETag() string {
	if m != nil {
		return m.ETag
	}
	return ""
}

type DeleteObject struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ObjectID             int64    `protobuf:"varint,2,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteObject) Reset()         { *m = DeleteObject{} }
func (m *DeleteObject) String() string { return proto.CompactTextString(m) }
func (*DeleteObject) ProtoMessage()    {}
func (*DeleteObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{10}
}
func (m *DeleteObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteObject.Unmarshal(m, b)
}
func (m *DeleteObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteObject.Marshal(b, m, deterministic)
}
func (m *DeleteObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteObject.Merge(m, src)
}
func (m *DeleteObject) XXX_Size() int {
	return xxx_messageInfo_DeleteObject.Size(m)
}
func (m *DeleteObject) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteObject.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteObject proto.InternalMessageInfo

func (m *DeleteObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteObject) GetObjectID() int64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *DeleteObject) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type CancelOp struct {
	OpType               LfsOp    `protobuf:"varint,1,opt,name=OpType,proto3,enum=proto.LfsOp" json:"OpType,omitempty"`
	OpID                 int64    `protobuf:"varint,2,opt,name=OpID,proto3" json:"OpID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOp) Reset()         { *m = CancelOp{} }
func (m *CancelOp) String() string { return proto.CompactTextString(m) }
func (*CancelOp) ProtoMessage()    {}
func (*CancelOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{11}
}
func (m *CancelOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOp.Unmarshal(m, b)
}
func (m *CancelOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOp.Marshal(b, m, deterministic)
}
func (m *CancelOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOp.Merge(m, src)
}
func (m *CancelOp) XXX_Size() int {
	return xxx_messageInfo_CancelOp.Size(m)
}
func (m *CancelOp) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOp.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOp proto.InternalMessageInfo

func (m *CancelOp) GetOpType() LfsOp {
	if m != nil {
		return m.OpType
	}
	return LfsOp_OpErr
}

func (m *CancelOp) GetOpID() int64 {
	if m != nil {
		return m.OpID
	}
	return 0
}

//OpRecord 元数据最终存储的格式是一串可压缩的操作记录
type OpRecord struct {
	OpType               LfsOp    `protobuf:"varint,1,opt,name=OpType,proto3,enum=proto.LfsOp" json:"OpType,omitempty"`
	OpID                 int64    `protobuf:"varint,2,opt,name=OpID,proto3" json:"OpID,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpRecord) Reset()         { *m = OpRecord{} }
func (m *OpRecord) String() string { return proto.CompactTextString(m) }
func (*OpRecord) ProtoMessage()    {}
func (*OpRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{12}
}
func (m *OpRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpRecord.Unmarshal(m, b)
}
func (m *OpRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpRecord.Marshal(b, m, deterministic)
}
func (m *OpRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpRecord.Merge(m, src)
}
func (m *OpRecord) XXX_Size() int {
	return xxx_messageInfo_OpRecord.Size(m)
}
func (m *OpRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_OpRecord.DiscardUnknown(m)
}

var xxx_messageInfo_OpRecord proto.InternalMessageInfo

func (m *OpRecord) GetOpType() LfsOp {
	if m != nil {
		return m.OpType
	}
	return LfsOp_OpErr
}

func (m *OpRecord) GetOpID() int64 {
	if m != nil {
		return m.OpID
	}
	return 0
}

func (m *OpRecord) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type BlockOptions struct {
	Bopts                *BucketOptions `protobuf:"bytes,1,opt,name=Bopts,proto3" json:"Bopts,omitempty"`
	Start                int32          `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	UserID               string         `protobuf:"bytes,11,opt,name=UserID,proto3" json:"UserID,omitempty"`
	QueryID              string         `protobuf:"bytes,12,opt,name=QueryID,proto3" json:"QueryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockOptions) Reset()         { *m = BlockOptions{} }
func (m *BlockOptions) String() string { return proto.CompactTextString(m) }
func (*BlockOptions) ProtoMessage()    {}
func (*BlockOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{13}
}
func (m *BlockOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockOptions.Unmarshal(m, b)
}
func (m *BlockOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockOptions.Marshal(b, m, deterministic)
}
func (m *BlockOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockOptions.Merge(m, src)
}
func (m *BlockOptions) XXX_Size() int {
	return xxx_messageInfo_BlockOptions.Size(m)
}
func (m *BlockOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BlockOptions proto.InternalMessageInfo

func (m *BlockOptions) GetBopts() *BucketOptions {
	if m != nil {
		return m.Bopts
	}
	return nil
}

func (m *BlockOptions) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *BlockOptions) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *BlockOptions) GetQueryID() string {
	if m != nil {
		return m.QueryID
	}
	return ""
}

type ShareLink struct {
	UserID               string         `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	QueryID              string         `protobuf:"bytes,2,opt,name=QueryID,proto3" json:"QueryID,omitempty"`
	BucketName           string         `protobuf:"bytes,3,opt,name=BucketName,proto3" json:"BucketName,omitempty"`
	ObjectName           string         `protobuf:"bytes,4,opt,name=ObjectName,proto3" json:"ObjectName,omitempty"`
	BucketID             int64          `protobuf:"varint,5,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	BOpts                *BucketOptions `protobuf:"bytes,6,opt,name=BOpts,proto3" json:"BOpts,omitempty"`
	OParts               []*ObjectPart  `protobuf:"bytes,7,rep,name=OParts,proto3" json:"OParts,omitempty"`
	DecKey               []byte         `protobuf:"bytes,8,opt,name=DecKey,proto3" json:"DecKey,omitempty"`
	KPs                  string         `protobuf:"bytes,11,opt,name=KPs,proto3" json:"KPs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShareLink) Reset()         { *m = ShareLink{} }
func (m *ShareLink) String() string { return proto.CompactTextString(m) }
func (*ShareLink) ProtoMessage()    {}
func (*ShareLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{14}
}
func (m *ShareLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareLink.Unmarshal(m, b)
}
func (m *ShareLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareLink.Marshal(b, m, deterministic)
}
func (m *ShareLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareLink.Merge(m, src)
}
func (m *ShareLink) XXX_Size() int {
	return xxx_messageInfo_ShareLink.Size(m)
}
func (m *ShareLink) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareLink.DiscardUnknown(m)
}

var xxx_messageInfo_ShareLink proto.InternalMessageInfo

func (m *ShareLink) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ShareLink) GetQueryID() string {
	if m != nil {
		return m.QueryID
	}
	return ""
}

func (m *ShareLink) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *ShareLink) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

func (m *ShareLink) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *ShareLink) GetBOpts() *BucketOptions {
	if m != nil {
		return m.BOpts
	}
	return nil
}

func (m *ShareLink) GetOParts() []*ObjectPart {
	if m != nil {
		return m.OParts
	}
	return nil
}

func (m *ShareLink) GetDecKey() []byte {
	if m != nil {
		return m.DecKey
	}
	return nil
}

func (m *ShareLink) GetKPs() string {
	if m != nil {
		return m.KPs
	}
	return ""
}

type ChalInfo struct {
	QueryID              string   `protobuf:"bytes,1,opt,name=QueryID,proto3" json:"QueryID,omitempty"`
	KeeperID             string   `protobuf:"bytes,2,opt,name=KeeperID,proto3" json:"KeeperID,omitempty"`
	ProviderID           string   `protobuf:"bytes,3,opt,name=ProviderID,proto3" json:"ProviderID,omitempty"`
	UserID               string   `protobuf:"bytes,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ChalTime             int64    `protobuf:"varint,5,opt,name=ChalTime,proto3" json:"ChalTime,omitempty"`
	ChalLength           int64    `protobuf:"varint,6,opt,name=ChalLength,proto3" json:"ChalLength,omitempty"`
	SuccessLength        int64    `protobuf:"varint,7,opt,name=SuccessLength,proto3" json:"SuccessLength,omitempty"`
	TotalLength          int64    `protobuf:"varint,8,opt,name=TotalLength,proto3" json:"TotalLength,omitempty"`
	Blocks               []string `protobuf:"bytes,9,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
	FaultBlocks          []string `protobuf:"bytes,10,rep,name=FaultBlocks,proto3" json:"FaultBlocks,omitempty"`
	BlsProof             string   `protobuf:"bytes,11,opt,name=BlsProof,proto3" json:"BlsProof,omitempty"`
	Res                  bool     `protobuf:"varint,12,opt,name=Res,proto3" json:"Res,omitempty"`
	RootTime             int64    `protobuf:"varint,19,opt,name=RootTime,proto3" json:"RootTime,omitempty"`
	Policy               string   `protobuf:"bytes,20,opt,name=Policy,proto3" json:"Policy,omitempty"`
	BucketNum            int64    `protobuf:"varint,21,opt,name=BucketNum,proto3" json:"BucketNum,omitempty"`
	StripeNum            []int64  `protobuf:"varint,22,rep,packed,name=StripeNum,proto3" json:"StripeNum,omitempty"`
	ChunkNum             []int32  `protobuf:"varint,23,rep,packed,name=ChunkNum,proto3" json:"ChunkNum,omitempty"`
	ChunkMap             []byte   `protobuf:"bytes,24,opt,name=ChunkMap,proto3" json:"ChunkMap,omitempty"`
	FailMap              []byte   `protobuf:"bytes,25,opt,name=FailMap,proto3" json:"FailMap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChalInfo) Reset()         { *m = ChalInfo{} }
func (m *ChalInfo) String() string { return proto.CompactTextString(m) }
func (*ChalInfo) ProtoMessage()    {}
func (*ChalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{15}
}
func (m *ChalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChalInfo.Unmarshal(m, b)
}
func (m *ChalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChalInfo.Marshal(b, m, deterministic)
}
func (m *ChalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChalInfo.Merge(m, src)
}
func (m *ChalInfo) XXX_Size() int {
	return xxx_messageInfo_ChalInfo.Size(m)
}
func (m *ChalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChalInfo proto.InternalMessageInfo

func (m *ChalInfo) GetQueryID() string {
	if m != nil {
		return m.QueryID
	}
	return ""
}

func (m *ChalInfo) GetKeeperID() string {
	if m != nil {
		return m.KeeperID
	}
	return ""
}

func (m *ChalInfo) GetProviderID() string {
	if m != nil {
		return m.ProviderID
	}
	return ""
}

func (m *ChalInfo) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ChalInfo) GetChalTime() int64 {
	if m != nil {
		return m.ChalTime
	}
	return 0
}

func (m *ChalInfo) GetChalLength() int64 {
	if m != nil {
		return m.ChalLength
	}
	return 0
}

func (m *ChalInfo) GetSuccessLength() int64 {
	if m != nil {
		return m.SuccessLength
	}
	return 0
}

func (m *ChalInfo) GetTotalLength() int64 {
	if m != nil {
		return m.TotalLength
	}
	return 0
}

func (m *ChalInfo) GetBlocks() []string {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *ChalInfo) GetFaultBlocks() []string {
	if m != nil {
		return m.FaultBlocks
	}
	return nil
}

func (m *ChalInfo) GetBlsProof() string {
	if m != nil {
		return m.BlsProof
	}
	return ""
}

func (m *ChalInfo) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

func (m *ChalInfo) GetRootTime() int64 {
	if m != nil {
		return m.RootTime
	}
	return 0
}

func (m *ChalInfo) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *ChalInfo) GetBucketNum() int64 {
	if m != nil {
		return m.BucketNum
	}
	return 0
}

func (m *ChalInfo) GetStripeNum() []int64 {
	if m != nil {
		return m.StripeNum
	}
	return nil
}

func (m *ChalInfo) GetChunkNum() []int32 {
	if m != nil {
		return m.ChunkNum
	}
	return nil
}

func (m *ChalInfo) GetChunkMap() []byte {
	if m != nil {
		return m.ChunkMap
	}
	return nil
}

func (m *ChalInfo) GetFailMap() []byte {
	if m != nil {
		return m.FailMap
	}
	return nil
}

type ChannelSign struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Sig                  []byte   `protobuf:"bytes,3,opt,name=Sig,proto3" json:"Sig,omitempty"`
	PubKey               []byte   `protobuf:"bytes,4,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelSign) Reset()         { *m = ChannelSign{} }
func (m *ChannelSign) String() string { return proto.CompactTextString(m) }
func (*ChannelSign) ProtoMessage()    {}
func (*ChannelSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{16}
}
func (m *ChannelSign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelSign.Unmarshal(m, b)
}
func (m *ChannelSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelSign.Marshal(b, m, deterministic)
}
func (m *ChannelSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelSign.Merge(m, src)
}
func (m *ChannelSign) XXX_Size() int {
	return xxx_messageInfo_ChannelSign.Size(m)
}
func (m *ChannelSign) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelSign.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelSign proto.InternalMessageInfo

func (m *ChannelSign) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *ChannelSign) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ChannelSign) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *ChannelSign) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type STValue struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	Length               int64    `protobuf:"varint,3,opt,name=Length,proto3" json:"Length,omitempty"`
	Value                []byte   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	Root                 []byte   `protobuf:"bytes,5,opt,name=Root,proto3" json:"Root,omitempty"`
	Share                []int64  `protobuf:"varint,6,rep,packed,name=Share,proto3" json:"Share,omitempty"`
	Sign                 [][]byte `protobuf:"bytes,7,rep,name=Sign,proto3" json:"Sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *STValue) Reset()         { *m = STValue{} }
func (m *STValue) String() string { return proto.CompactTextString(m) }
func (*STValue) ProtoMessage()    {}
func (*STValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{17}
}
func (m *STValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_STValue.Unmarshal(m, b)
}
func (m *STValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_STValue.Marshal(b, m, deterministic)
}
func (m *STValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_STValue.Merge(m, src)
}
func (m *STValue) XXX_Size() int {
	return xxx_messageInfo_STValue.Size(m)
}
func (m *STValue) XXX_DiscardUnknown() {
	xxx_messageInfo_STValue.DiscardUnknown(m)
}

var xxx_messageInfo_STValue proto.InternalMessageInfo

func (m *STValue) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *STValue) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *STValue) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *STValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *STValue) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *STValue) GetShare() []int64 {
	if m != nil {
		return m.Share
	}
	return nil
}

func (m *STValue) GetSign() [][]byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type KVData struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVData) Reset()         { *m = KVData{} }
func (m *KVData) String() string { return proto.CompactTextString(m) }
func (*KVData) ProtoMessage()    {}
func (*KVData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{18}
}
func (m *KVData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVData.Unmarshal(m, b)
}
func (m *KVData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVData.Marshal(b, m, deterministic)
}
func (m *KVData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVData.Merge(m, src)
}
func (m *KVData) XXX_Size() int {
	return xxx_messageInfo_KVData.Size(m)
}
func (m *KVData) XXX_DiscardUnknown() {
	xxx_messageInfo_KVData.DiscardUnknown(m)
}

var xxx_messageInfo_KVData proto.InternalMessageInfo

func (m *KVData) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KVData) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.OpType", OpType_name, OpType_value)
	proto.RegisterEnum("proto.KeyType", KeyType_name, KeyType_value)
	proto.RegisterEnum("proto.LfsOp", LfsOp_name, LfsOp_value)
	proto.RegisterType((*KeyMeta)(nil), "proto.KeyMeta")
	proto.RegisterType((*UserBLS12Config)(nil), "proto.UserBLS12Config")
	proto.RegisterType((*BucketRoot)(nil), "proto.BucketRoot")
	proto.RegisterType((*LfsRoot)(nil), "proto.LfsRoot")
	proto.RegisterType((*SuperBlockInfo)(nil), "proto.SuperBlockInfo")
	proto.RegisterType((*BucketOptions)(nil), "proto.BucketOptions")
	proto.RegisterType((*BucketInfo)(nil), "proto.BucketInfo")
	proto.RegisterType((*ObjectInfo)(nil), "proto.ObjectInfo")
	proto.RegisterType((*Object)(nil), "proto.Object")
	proto.RegisterMapType((map[string]string)(nil), "proto.Object.MetadataEntry")
	proto.RegisterType((*ObjectPart)(nil), "proto.ObjectPart")
	proto.RegisterType((*DeleteObject)(nil), "proto.DeleteObject")
	proto.RegisterType((*CancelOp)(nil), "proto.CancelOp")
	proto.RegisterType((*OpRecord)(nil), "proto.OpRecord")
	proto.RegisterType((*BlockOptions)(nil), "proto.BlockOptions")
	proto.RegisterType((*ShareLink)(nil), "proto.ShareLink")
	proto.RegisterType((*ChalInfo)(nil), "proto.ChalInfo")
	proto.RegisterType((*ChannelSign)(nil), "proto.ChannelSign")
	proto.RegisterType((*STValue)(nil), "proto.STValue")
	proto.RegisterType((*KVData)(nil), "proto.KVData")
}

func init() { proto.RegisterFile("mefs.proto", fileDescriptor_2b3c77393cf6fe78) }

var fileDescriptor_2b3c77393cf6fe78 = []byte{
	// 1693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcd, 0x8e, 0xdb, 0xc8,
	0x11, 0x36, 0x45, 0x52, 0x3f, 0x25, 0xcd, 0xb8, 0xc3, 0x9d, 0xf5, 0x72, 0x67, 0x8d, 0x8d, 0x96,
	0x30, 0x10, 0x79, 0x02, 0x18, 0xc9, 0xe4, 0x90, 0x20, 0x39, 0x59, 0xd2, 0xd8, 0x19, 0xcc, 0x8c,
	0xa5, 0xb4, 0xc6, 0xf6, 0x9e, 0x16, 0xe8, 0x91, 0x5a, 0x32, 0x23, 0x9a, 0x24, 0xc8, 0xa6, 0xb1,
	0xca, 0x2d, 0x79, 0x86, 0x9c, 0x82, 0xdc, 0x02, 0xe4, 0x94, 0x63, 0x1e, 0x22, 0xcf, 0x92, 0x7b,
	0xee, 0x41, 0x55, 0x37, 0x7f, 0xa4, 0xd8, 0x13, 0x20, 0xc8, 0x49, 0xfd, 0x55, 0x75, 0x55, 0x57,
	0x7d, 0x5d, 0x55, 0x6c, 0x01, 0xbc, 0x97, 0xeb, 0xfc, 0x59, 0x9a, 0x25, 0x2a, 0xf1, 0x5c, 0xfa,
	0x09, 0x0a, 0xe8, 0x5c, 0xc9, 0xdd, 0x8d, 0x54, 0xc2, 0xf3, 0xa1, 0xf3, 0x46, 0x66, 0x79, 0x98,
	0xc4, 0xbe, 0x35, 0xb4, 0x46, 0x2e, 0x2f, 0xa1, 0xf7, 0x04, 0xdc, 0xab, 0xdb, 0x5d, 0x2a, 0xfd,
	0xd6, 0xd0, 0x1a, 0x1d, 0x9f, 0x1f, 0x6b, 0x17, 0xcf, 0xae, 0xe4, 0x0e, 0xa5, 0x5c, 0x2b, 0x3d,
	0x06, 0xf6, 0x4d, 0xb8, 0xf2, 0xed, 0xa1, 0x35, 0xea, 0x71, 0x5c, 0xa2, 0xc7, 0x59, 0xaa, 0xc2,
	0x24, 0xce, 0x7d, 0x67, 0x68, 0x8f, 0x7a, 0xbc, 0x84, 0xc1, 0xbf, 0x2c, 0x78, 0xf8, 0x3a, 0x97,
	0xd9, 0xf8, 0x7a, 0xf1, 0xd3, 0xf3, 0x49, 0x12, 0xaf, 0xc3, 0x0d, 0xee, 0xfe, 0xb0, 0x7f, 0xbe,
	0x81, 0xde, 0x63, 0xe8, 0xa5, 0xc5, 0xdd, 0x56, 0xee, 0xc6, 0x51, 0x4e, 0x31, 0x0c, 0x78, 0x2d,
	0x40, 0x3b, 0x0d, 0x5e, 0xd2, 0xd9, 0x03, 0x5e, 0xc2, 0x5a, 0xf3, 0x9a, 0xce, 0xaf, 0x34, 0xaf,
	0x6b, 0xcd, 0x5b, 0xdf, 0x6d, 0x6a, 0xde, 0xd2, 0x59, 0x59, 0x68, 0xce, 0x6a, 0x9b, 0xb3, 0x4a,
	0x81, 0x37, 0x00, 0xeb, 0x5b, 0xbf, 0x43, 0x52, 0xeb, 0x5b, 0xef, 0x04, 0xdc, 0x65, 0x52, 0xc4,
	0xca, 0x07, 0x8a, 0x57, 0x03, 0xef, 0x14, 0xba, 0x4a, 0x6c, 0x26, 0xa4, 0xe8, 0x93, 0xa2, 0xc2,
	0xc1, 0x1b, 0x80, 0x71, 0xb1, 0xdc, 0x4a, 0xc5, 0x93, 0x84, 0x76, 0x6a, 0x74, 0x39, 0xa5, 0x94,
	0x6d, 0x5e, 0x61, 0xcd, 0x9d, 0x76, 0xd2, 0x22, 0x55, 0x09, 0x3d, 0x0f, 0x1c, 0xb4, 0x36, 0xc9,
	0xd2, 0x3a, 0xf8, 0x0e, 0x3a, 0xd7, 0xeb, 0x9c, 0x9c, 0x9e, 0x80, 0x3b, 0xb9, 0x0d, 0xdf, 0x4b,
	0xe3, 0x51, 0x83, 0xca, 0xa8, 0x55, 0x1b, 0x79, 0x4f, 0xa1, 0x3d, 0xc6, 0x45, 0xee, 0xdb, 0x43,
	0x7b, 0xd4, 0x3f, 0xff, 0x81, 0xb9, 0xd7, 0x3a, 0x42, 0x6e, 0x36, 0x04, 0x7f, 0xb7, 0xe0, 0x78,
	0x51, 0xa4, 0x32, 0x1b, 0x47, 0xc9, 0x72, 0x7b, 0x19, 0xaf, 0x93, 0x7b, 0xca, 0x65, 0x04, 0x0f,
	0xb1, 0xa0, 0xc6, 0x62, 0xb9, 0x2d, 0x1a, 0x29, 0xb8, 0xfc, 0x50, 0x5c, 0xc7, 0x6a, 0x37, 0x63,
	0x0d, 0x60, 0xf0, 0x4a, 0x7e, 0xaf, 0x2a, 0x6a, 0x1c, 0x52, 0xee, 0xc9, 0xb0, 0x24, 0xaf, 0x29,
	0xa1, 0x0e, 0x85, 0x5e, 0x96, 0xa4, 0x21, 0x81, 0x6b, 0x65, 0xf0, 0xfb, 0x16, 0x1c, 0x69, 0x13,
	0x53, 0x78, 0xf7, 0x44, 0xfd, 0x08, 0xda, 0xf3, 0x24, 0x0a, 0x97, 0x3b, 0x13, 0xac, 0x41, 0x58,
	0x10, 0x53, 0xa1, 0x84, 0xce, 0xc3, 0x26, 0x55, 0x2d, 0xf0, 0x86, 0xd0, 0x9f, 0x8b, 0x2c, 0x54,
	0x3b, 0xad, 0x77, 0x48, 0xdf, 0x14, 0xe1, 0x89, 0xb7, 0x62, 0xf3, 0x22, 0x12, 0x1b, 0xdf, 0xd5,
	0x27, 0x1a, 0x88, 0xb6, 0x0b, 0xb9, 0x79, 0x2f, 0x63, 0xb5, 0x08, 0x7f, 0x27, 0xa9, 0xd8, 0x5c,
	0xde, 0x14, 0x21, 0x13, 0x06, 0x6a, 0xf7, 0x1d, 0xda, 0xb2, 0x27, 0xf3, 0xbe, 0x06, 0xb8, 0x88,
	0x97, 0xd9, 0x8e, 0x12, 0xf4, 0xbb, 0xb4, 0xa3, 0x21, 0x09, 0xfe, 0xd1, 0x2a, 0x6b, 0x8e, 0xae,
	0xcd, 0x03, 0xe7, 0x95, 0x30, 0xd5, 0xd1, 0xe3, 0xb4, 0xde, 0xab, 0xc3, 0xd6, 0x41, 0x1d, 0x7e,
	0xfc, 0x8a, 0xce, 0xc0, 0x1d, 0xcf, 0x52, 0x95, 0x53, 0xc2, 0xfd, 0xf3, 0x93, 0xbd, 0xca, 0x31,
	0x5c, 0x73, 0xbd, 0x05, 0x89, 0xbd, 0x96, 0xf1, 0x46, 0xbd, 0xa3, 0xfc, 0x6d, 0x6e, 0x10, 0x7a,
	0xbe, 0x21, 0xcf, 0x1d, 0xed, 0xf9, 0xc6, 0x78, 0x66, 0xb3, 0xbb, 0xdf, 0xca, 0xa5, 0xca, 0xa9,
	0xd4, 0x88, 0x99, 0x2e, 0x6d, 0xf8, 0x0f, 0x39, 0xc6, 0x3d, 0x95, 0x91, 0xa4, 0xc4, 0x7b, 0x43,
	0x6b, 0xd4, 0xe5, 0x15, 0x2e, 0x8b, 0x48, 0xdb, 0x5c, 0x4e, 0xa9, 0x45, 0x4d, 0x11, 0x95, 0x32,
	0xb4, 0x27, 0x9c, 0x5e, 0x4e, 0xa9, 0x53, 0x6d, 0x5e, 0xe1, 0xaa, 0x61, 0x06, 0x8d, 0x2e, 0xfb,
	0xa7, 0x05, 0x60, 0x8c, 0x91, 0xca, 0x6f, 0xc0, 0xc1, 0x5f, 0xa2, 0xb2, 0x7f, 0x7e, 0x64, 0x38,
	0xd0, 0x1b, 0x38, 0xa9, 0x1a, 0xb9, 0xb7, 0x0e, 0x73, 0xff, 0x08, 0xab, 0x15, 0x23, 0x4e, 0x93,
	0x91, 0xc7, 0xd0, 0x9b, 0x8b, 0xcc, 0x54, 0x80, 0xa6, 0xb0, 0x16, 0x60, 0x9c, 0x17, 0xb7, 0x62,
	0x43, 0xd5, 0xd3, 0xe3, 0xb4, 0xde, 0xe3, 0xa5, 0x73, 0xc0, 0xcb, 0x8f, 0xc0, 0x45, 0xe3, 0xdc,
	0x87, 0xbd, 0x9e, 0xd7, 0x51, 0xa3, 0x86, 0x6b, 0x7d, 0xf0, 0xc7, 0x16, 0xb4, 0xb5, 0xf4, 0xff,
	0x54, 0x33, 0xa7, 0xd0, 0xad, 0x6e, 0x43, 0x27, 0x58, 0x61, 0xfc, 0x76, 0x4c, 0xc3, 0x8c, 0xb2,
	0xeb, 0x72, 0x5c, 0x62, 0x73, 0x4c, 0x92, 0x58, 0xc9, 0x58, 0xd1, 0x97, 0xa7, 0x47, 0x47, 0x37,
	0x45, 0xde, 0xcf, 0xa1, 0x8b, 0xf3, 0x64, 0x25, 0x94, 0x30, 0xc9, 0x7c, 0xb5, 0x97, 0xcc, 0xb3,
	0x52, 0x7b, 0x11, 0xab, 0x6c, 0xc7, 0xab, 0xcd, 0xa7, 0xbf, 0x82, 0xa3, 0x3d, 0x15, 0x9e, 0xbe,
	0x95, 0x3b, 0x93, 0x1e, 0x2e, 0x31, 0x83, 0x0f, 0x22, 0x2a, 0xf4, 0x17, 0xaf, 0xc7, 0x35, 0xf8,
	0x65, 0xeb, 0x17, 0x56, 0xf0, 0xb7, 0xaa, 0x06, 0x90, 0xa6, 0x4f, 0x51, 0x53, 0x25, 0xda, 0x3a,
	0x48, 0x14, 0xa7, 0x8c, 0xc8, 0x50, 0xa3, 0xb9, 0x31, 0x08, 0x0f, 0x5c, 0x28, 0x91, 0xa9, 0xf2,
	0xea, 0x09, 0xdc, 0xd7, 0x3a, 0x9a, 0xe0, 0xf6, 0xc1, 0x8c, 0xa7, 0x52, 0xe8, 0xd4, 0xa5, 0x10,
	0x70, 0x18, 0xd0, 0xd5, 0xcb, 0xfb, 0xaf, 0xf2, 0x93, 0xf1, 0x7a, 0xe0, 0x34, 0x6e, 0x92, 0xd6,
	0xc1, 0x14, 0xba, 0x13, 0x11, 0x2f, 0x65, 0x34, 0x4b, 0xbd, 0x27, 0xd0, 0x9e, 0xa5, 0x74, 0x43,
	0x16, 0xbd, 0x0d, 0x06, 0xf5, 0x20, 0x9e, 0xa5, 0xdc, 0xe8, 0xd0, 0x0b, 0x35, 0x99, 0xf6, 0x4e,
	0xeb, 0xe0, 0x3b, 0xe8, 0xce, 0x52, 0x2e, 0x97, 0x49, 0xb6, 0xfa, 0xdf, 0xbd, 0xe0, 0x74, 0x9d,
	0x8b, 0x5d, 0x94, 0x88, 0x55, 0xf9, 0xf1, 0x37, 0x30, 0xf8, 0x83, 0x05, 0x03, 0x1a, 0x15, 0xe5,
	0xe8, 0xc7, 0x99, 0x95, 0xe0, 0xcc, 0xb2, 0xee, 0x9d, 0x59, 0xb8, 0xa5, 0xbe, 0x0e, 0xfd, 0x2d,
	0xa8, 0xaf, 0x03, 0x1f, 0x2d, 0x66, 0x5a, 0xf4, 0xb8, 0x41, 0x18, 0xc4, 0x6f, 0x0a, 0x99, 0xed,
	0x2e, 0xa7, 0x34, 0x2e, 0x7a, 0xbc, 0x84, 0xc1, 0x9f, 0x5a, 0xd0, 0x5b, 0xbc, 0x13, 0x99, 0xbc,
	0x0e, 0xe3, 0x6d, 0xc3, 0xde, 0xfa, 0x94, 0x7d, 0x6b, 0xcf, 0x1e, 0x87, 0xbb, 0x8e, 0x8f, 0x2e,
	0x4d, 0x3f, 0xad, 0x1a, 0x12, 0xd4, 0xeb, 0xab, 0x22, 0xbd, 0xa3, 0xf5, 0xb5, 0x64, 0xaf, 0x4b,
	0xdd, 0x83, 0x2e, 0xad, 0x66, 0x78, 0xfb, 0xbf, 0xcf, 0xf0, 0xa7, 0xd0, 0x9e, 0xe9, 0xb1, 0xd1,
	0xf9, 0xd4, 0xd8, 0x30, 0x1b, 0x30, 0xc9, 0xa9, 0x5c, 0x5e, 0xc9, 0x1d, 0x8d, 0xed, 0x01, 0x37,
	0x08, 0x9b, 0xec, 0x6a, 0x9e, 0x1b, 0xe6, 0x70, 0x19, 0xfc, 0xd5, 0x81, 0xee, 0xe4, 0x9d, 0x88,
	0xca, 0xe7, 0x44, 0xc9, 0x81, 0xb5, 0xcf, 0xc1, 0x29, 0x74, 0xaf, 0xa4, 0x4c, 0x89, 0x37, 0x4d,
	0x4f, 0x85, 0x31, 0xff, 0x79, 0x96, 0x7c, 0x08, 0x57, 0xa4, 0x35, 0xfc, 0xd4, 0x92, 0x06, 0xe3,
	0xce, 0x1e, 0xe3, 0xa7, 0xfa, 0x64, 0x2a, 0x6d, 0xc3, 0x4b, 0x89, 0xd1, 0x27, 0xae, 0x4d, 0xe3,
	0xe9, 0x0e, 0x6b, 0x48, 0xbc, 0x27, 0x70, 0xb4, 0x28, 0x96, 0x4b, 0x99, 0xe7, 0x66, 0x8b, 0xfe,
	0x7e, 0xed, 0x0b, 0x71, 0x7e, 0xdd, 0x26, 0xaa, 0x72, 0xa3, 0x3f, 0x61, 0x4d, 0x11, 0xc6, 0x46,
	0xf5, 0x99, 0xfb, 0x3d, 0x7a, 0x1c, 0x1b, 0x84, 0x96, 0x2f, 0x44, 0x11, 0x29, 0xa3, 0x04, 0x52,
	0x36, 0x45, 0x74, 0xab, 0x51, 0x3e, 0xcf, 0x92, 0x64, 0x6d, 0xf8, 0xac, 0x30, 0xd2, 0xcc, 0x65,
	0x4e, 0x75, 0xd8, 0xe5, 0xb8, 0xc4, 0xdd, 0xf8, 0xf5, 0xa2, 0x5c, 0x3f, 0xd3, 0xb9, 0x96, 0xb8,
	0xf1, 0xe8, 0x39, 0xd1, 0xfc, 0xd4, 0x8f, 0x1e, 0x53, 0x65, 0xc5, 0x7b, 0xff, 0x73, 0xfd, 0xcd,
	0xa9, 0x04, 0xa8, 0x5d, 0xa8, 0x2c, 0x4c, 0x25, 0x6a, 0x1f, 0x0d, 0x6d, 0xd4, 0x56, 0x02, 0xcd,
	0x6d, 0x11, 0x6f, 0x51, 0xf9, 0xc5, 0xd0, 0xc6, 0xf7, 0x6f, 0x89, 0x2b, 0xdd, 0x8d, 0x48, 0x7d,
	0x9f, 0xca, 0xa3, 0xc2, 0x58, 0x01, 0x2f, 0x44, 0x18, 0xa1, 0xea, 0x4b, 0xdd, 0xca, 0x06, 0x06,
	0x5b, 0xe8, 0x4f, 0xde, 0x89, 0x38, 0x96, 0xd1, 0x22, 0xdc, 0xd0, 0xdf, 0x01, 0x03, 0xab, 0x62,
	0xa9, 0x05, 0xd8, 0xba, 0x6f, 0xaa, 0xd1, 0x3d, 0xe0, 0x1a, 0x20, 0x2d, 0x8b, 0x70, 0x63, 0x66,
	0x04, 0x2e, 0x29, 0xf5, 0xe2, 0x0e, 0xeb, 0xd4, 0xd1, 0x75, 0xaa, 0x51, 0xf0, 0x17, 0x0b, 0x3a,
	0x8b, 0x5b, 0x6d, 0xf5, 0x08, 0xda, 0x0b, 0x25, 0x54, 0x91, 0x9b, 0xc7, 0xa2, 0x41, 0xfb, 0xe3,
	0xe1, 0x23, 0xd3, 0xda, 0x3e, 0x9c, 0xd6, 0x3a, 0x22, 0xa7, 0x19, 0x51, 0xf9, 0xc0, 0x70, 0x1b,
	0x2f, 0x72, 0xf4, 0x8b, 0xd3, 0xc2, 0x6f, 0x13, 0xa9, 0x1a, 0xe0, 0x4e, 0xcc, 0x9b, 0x5a, 0x6f,
	0xc0, 0x69, 0x1d, 0xfc, 0x04, 0xda, 0x57, 0x6f, 0xf0, 0x19, 0x4a, 0x7d, 0x65, 0x3e, 0x5e, 0x03,
	0x8e, 0xcb, 0x8f, 0x33, 0x70, 0xf6, 0xbc, 0x9c, 0xb1, 0xde, 0x11, 0xf4, 0xc6, 0x59, 0x22, 0x56,
	0x13, 0x91, 0x2b, 0xf6, 0xc0, 0xeb, 0x80, 0x3d, 0x2f, 0x14, 0xb3, 0x70, 0xf1, 0x52, 0x2a, 0xd6,
	0xf2, 0x00, 0xda, 0xcf, 0xd3, 0x54, 0xc6, 0x2b, 0x66, 0xe3, 0x5a, 0x7f, 0x40, 0x98, 0x73, 0xf6,
	0x67, 0x9b, 0xfe, 0x2d, 0x92, 0x93, 0x1e, 0xb8, 0x6f, 0xb3, 0x24, 0xde, 0xb0, 0x07, 0x5e, 0x17,
	0x33, 0x89, 0x24, 0xb3, 0xd0, 0xf3, 0xbc, 0xb8, 0x8b, 0x42, 0x6c, 0x78, 0xed, 0x47, 0xff, 0xb7,
	0x63, 0x36, 0x3a, 0xbf, 0x7e, 0xb1, 0x60, 0x0e, 0x1a, 0x62, 0x13, 0xe6, 0xcc, 0xf5, 0xfa, 0xe8,
	0x0e, 0x3b, 0x39, 0x67, 0x6d, 0xb2, 0x35, 0x8d, 0x9b, 0xb3, 0x0e, 0x6e, 0xa3, 0x6a, 0x67, 0xe0,
	0x0d, 0xb0, 0xdc, 0x93, 0xe5, 0x76, 0x9e, 0xe4, 0xac, 0x8f, 0xa8, 0x6c, 0x55, 0x36, 0xa0, 0xe0,
	0x93, 0x9c, 0x1d, 0xe1, 0x59, 0xba, 0x40, 0xd9, 0x31, 0xfa, 0x5d, 0xc8, 0x1c, 0x5f, 0xf5, 0xec,
	0x21, 0xfa, 0xfd, 0xb5, 0x14, 0x99, 0x1a, 0x4b, 0xa1, 0xd8, 0x09, 0x9a, 0xd3, 0x0c, 0x88, 0x43,
	0xc5, 0x3e, 0xf7, 0x8e, 0x01, 0x10, 0xbd, 0x4a, 0x54, 0xb8, 0xde, 0xb1, 0x47, 0xb8, 0x19, 0x31,
	0xdd, 0x27, 0xfb, 0xa2, 0xdc, 0xbc, 0x50, 0x49, 0xca, 0x7c, 0x54, 0xe2, 0xc9, 0x91, 0x8c, 0x37,
	0x92, 0x7d, 0x89, 0x27, 0x72, 0x99, 0x8a, 0x30, 0x63, 0xa7, 0xde, 0x67, 0xf0, 0xf0, 0xe2, 0x7b,
	0x25, 0xb3, 0x58, 0x44, 0xcf, 0x57, 0xab, 0x4c, 0xe6, 0x39, 0xfb, 0x8a, 0xc2, 0x50, 0x49, 0x26,
	0x36, 0x92, 0x3d, 0xc6, 0x7c, 0x68, 0xa0, 0xb1, 0xaf, 0x71, 0x39, 0x5b, 0xaf, 0x65, 0xc6, 0x7e,
	0x48, 0xe7, 0xa5, 0xc8, 0x41, 0x18, 0x6f, 0xd8, 0x10, 0x2d, 0x4c, 0x21, 0xb3, 0x6f, 0x0c, 0x88,
	0xe6, 0x62, 0xc7, 0x46, 0x08, 0xae, 0x45, 0xae, 0x10, 0x3c, 0x45, 0x30, 0x4f, 0x72, 0x7c, 0xc3,
	0xb0, 0x33, 0x64, 0x1f, 0x2b, 0x82, 0xfd, 0xf8, 0xec, 0x25, 0xb8, 0xf4, 0xc1, 0xa4, 0x03, 0xd2,
	0x8b, 0x2c, 0x63, 0x0f, 0xf4, 0xf2, 0xf9, 0x6a, 0xc5, 0x2c, 0x4c, 0x66, 0x96, 0x9a, 0x7b, 0x6d,
	0x69, 0x64, 0x6e, 0xd6, 0xd6, 0x48, 0x7f, 0xd4, 0x99, 0x73, 0xd7, 0xa6, 0xe1, 0xfe, 0xb3, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xf6, 0xa1, 0x90, 0x30, 0x10, 0x00, 0x00,
}
