// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sign.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ChannelSign struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Sig                  []byte   `protobuf:"bytes,3,opt,name=Sig,proto3" json:"Sig,omitempty"`
	PubKey               []byte   `protobuf:"bytes,4,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelSign) Reset()         { *m = ChannelSign{} }
func (m *ChannelSign) String() string { return proto.CompactTextString(m) }
func (*ChannelSign) ProtoMessage()    {}
func (*ChannelSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_3feb3e12a3dc7fb1, []int{0}
}
func (m *ChannelSign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelSign.Unmarshal(m, b)
}
func (m *ChannelSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelSign.Marshal(b, m, deterministic)
}
func (m *ChannelSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelSign.Merge(m, src)
}
func (m *ChannelSign) XXX_Size() int {
	return xxx_messageInfo_ChannelSign.Size(m)
}
func (m *ChannelSign) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelSign.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelSign proto.InternalMessageInfo

func (m *ChannelSign) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *ChannelSign) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ChannelSign) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *ChannelSign) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func init() {
	proto.RegisterType((*ChannelSign)(nil), "proto.ChannelSign")
}

func init() { proto.RegisterFile("sign.proto", fileDescriptor_3feb3e12a3dc7fb1) }

var fileDescriptor_3feb3e12a3dc7fb1 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xce, 0x4c, 0xcf,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xd9, 0x5c, 0xdc, 0xce, 0x19,
	0x89, 0x79, 0x79, 0xa9, 0x39, 0xc1, 0x99, 0xe9, 0x79, 0x42, 0x32, 0x5c, 0x9c, 0x50, 0xae, 0xa7,
	0x8b, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x42, 0x40, 0x48, 0x84, 0x8b, 0x35, 0x2c, 0x31,
	0xa7, 0x34, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x27, 0x08, 0xc2, 0x11, 0x12, 0xe0, 0x62, 0x0e,
	0xce, 0x4c, 0x97, 0x60, 0x06, 0x8b, 0x81, 0x98, 0x42, 0x62, 0x5c, 0x6c, 0x01, 0xa5, 0x49, 0xde,
	0xa9, 0x95, 0x12, 0x2c, 0x60, 0x41, 0x28, 0x2f, 0x89, 0x0d, 0x6c, 0xa7, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x08, 0xa6, 0xf2, 0x78, 0x88, 0x00, 0x00, 0x00,
}
