// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mefs.proto

package mefs_pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// operation type
type OpType int32

const (
	OpType_BroadCast OpType = 0
	OpType_Put       OpType = 1
	OpType_Get       OpType = 2
	OpType_Append    OpType = 3
	OpType_Delete    OpType = 4
)

var OpType_name = map[int32]string{
	0: "BroadCast",
	1: "Put",
	2: "Get",
	3: "Append",
	4: "Delete",
}

var OpType_value = map[string]int32{
	"BroadCast": 0,
	"Put":       1,
	"Get":       2,
	"Append":    3,
	"Delete":    4,
}

func (x OpType) String() string {
	return proto.EnumName(OpType_name, int32(x))
}

func (OpType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{0}
}

// meta key type indicates: operate which type of key;
// or record which type of key
type KeyType int32

const (
	KeyType_Wrong           KeyType = 0
	KeyType_Role            KeyType = 1
	KeyType_PublicKey       KeyType = 2
	KeyType_Config          KeyType = 3
	KeyType_LFS             KeyType = 4
	KeyType_Users           KeyType = 5
	KeyType_Keepers         KeyType = 6
	KeyType_Providers       KeyType = 7
	KeyType_Block           KeyType = 10
	KeyType_BlockPos        KeyType = 11
	KeyType_ChalTime        KeyType = 12
	KeyType_Pos             KeyType = 13
	KeyType_Bucket          KeyType = 14
	KeyType_StPaySign       KeyType = 15
	KeyType_ProAddSign      KeyType = 16
	KeyType_HeartBeat       KeyType = 20
	KeyType_UserInit        KeyType = 21
	KeyType_UserNotify      KeyType = 22
	KeyType_UserStart       KeyType = 23
	KeyType_UserStop        KeyType = 24
	KeyType_Challenge       KeyType = 25
	KeyType_Repair          KeyType = 26
	KeyType_ExternalAddress KeyType = 27
	KeyType_Storage         KeyType = 28
	KeyType_Query           KeyType = 30
	KeyType_Offer           KeyType = 31
	KeyType_UpKeeping       KeyType = 32
	KeyType_Channel         KeyType = 33
	KeyType_Income          KeyType = 39
	KeyType_ChalPay         KeyType = 40
	KeyType_LastPay         KeyType = 41
	KeyType_PosMeta         KeyType = 42
	KeyType_Session         KeyType = 43
	KeyType_BucketStripes   KeyType = 44
)

var KeyType_name = map[int32]string{
	0:  "Wrong",
	1:  "Role",
	2:  "PublicKey",
	3:  "Config",
	4:  "LFS",
	5:  "Users",
	6:  "Keepers",
	7:  "Providers",
	10: "Block",
	11: "BlockPos",
	12: "ChalTime",
	13: "Pos",
	14: "Bucket",
	15: "StPaySign",
	16: "ProAddSign",
	20: "HeartBeat",
	21: "UserInit",
	22: "UserNotify",
	23: "UserStart",
	24: "UserStop",
	25: "Challenge",
	26: "Repair",
	27: "ExternalAddress",
	28: "Storage",
	30: "Query",
	31: "Offer",
	32: "UpKeeping",
	33: "Channel",
	39: "Income",
	40: "ChalPay",
	41: "LastPay",
	42: "PosMeta",
	43: "Session",
	44: "BucketStripes",
}

var KeyType_value = map[string]int32{
	"Wrong":           0,
	"Role":            1,
	"PublicKey":       2,
	"Config":          3,
	"LFS":             4,
	"Users":           5,
	"Keepers":         6,
	"Providers":       7,
	"Block":           10,
	"BlockPos":        11,
	"ChalTime":        12,
	"Pos":             13,
	"Bucket":          14,
	"StPaySign":       15,
	"ProAddSign":      16,
	"HeartBeat":       20,
	"UserInit":        21,
	"UserNotify":      22,
	"UserStart":       23,
	"UserStop":        24,
	"Challenge":       25,
	"Repair":          26,
	"ExternalAddress": 27,
	"Storage":         28,
	"Query":           30,
	"Offer":           31,
	"UpKeeping":       32,
	"Channel":         33,
	"Income":          39,
	"ChalPay":         40,
	"LastPay":         41,
	"PosMeta":         42,
	"Session":         43,
	"BucketStripes":   44,
}

func (x KeyType) String() string {
	return proto.EnumName(KeyType_name, int32(x))
}

func (KeyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{1}
}

type LfsOp int32

const (
	LfsOp_OpErr    LfsOp = 0
	LfsOp_OpAdd    LfsOp = 1
	LfsOp_OpAppend LfsOp = 2
	LfsOp_OpDelete LfsOp = 3
	LfsOp_OpCancel LfsOp = 4
)

var LfsOp_name = map[int32]string{
	0: "OpErr",
	1: "OpAdd",
	2: "OpAppend",
	3: "OpDelete",
	4: "OpCancel",
}

var LfsOp_value = map[string]int32{
	"OpErr":    0,
	"OpAdd":    1,
	"OpAppend": 2,
	"OpDelete": 3,
	"OpCancel": 4,
}

func (x LfsOp) String() string {
	return proto.EnumName(LfsOp_name, int32(x))
}

func (LfsOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{2}
}

// record key meta
type KeyMeta struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	KeyType              KeyType  `protobuf:"varint,2,opt,name=keyType,proto3,enum=mefs.pb.KeyType" json:"keyType,omitempty"`
	MainID               string   `protobuf:"bytes,3,opt,name=mainID,proto3" json:"mainID,omitempty"`
	Options              []string `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyMeta) Reset()         { *m = KeyMeta{} }
func (m *KeyMeta) String() string { return proto.CompactTextString(m) }
func (*KeyMeta) ProtoMessage()    {}
func (*KeyMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{0}
}
func (m *KeyMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyMeta.Unmarshal(m, b)
}
func (m *KeyMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyMeta.Marshal(b, m, deterministic)
}
func (m *KeyMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyMeta.Merge(m, src)
}
func (m *KeyMeta) XXX_Size() int {
	return xxx_messageInfo_KeyMeta.Size(m)
}
func (m *KeyMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyMeta.DiscardUnknown(m)
}

var xxx_messageInfo_KeyMeta proto.InternalMessageInfo

func (m *KeyMeta) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *KeyMeta) GetKeyType() KeyType {
	if m != nil {
		return m.KeyType
	}
	return KeyType_Wrong
}

func (m *KeyMeta) GetMainID() string {
	if m != nil {
		return m.MainID
	}
	return ""
}

func (m *KeyMeta) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

// value stored in localdb
type Record struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{1}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Record) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Record) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// bls12 config information
type UserBLS12Config struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PubkeyBls            []byte   `protobuf:"bytes,2,opt,name=pubkeyBls,proto3" json:"pubkeyBls,omitempty"`
	PubkeyG              []byte   `protobuf:"bytes,3,opt,name=pubkeyG,proto3" json:"pubkeyG,omitempty"`
	PubkeyU              [][]byte `protobuf:"bytes,4,rep,name=pubkeyU,proto3" json:"pubkeyU,omitempty"`
	PubkeyW              [][]byte `protobuf:"bytes,5,rep,name=pubkeyW,proto3" json:"pubkeyW,omitempty"`
	PrikeyBls            []byte   `protobuf:"bytes,6,opt,name=prikeyBls,proto3" json:"prikeyBls,omitempty"`
	X                    []byte   `protobuf:"bytes,7,opt,name=X,proto3" json:"X,omitempty"`
	Count                int32    `protobuf:"varint,10,opt,name=count,proto3" json:"count,omitempty"`
	TagCount             int32    `protobuf:"varint,11,opt,name=tagCount,proto3" json:"tagCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBLS12Config) Reset()         { *m = UserBLS12Config{} }
func (m *UserBLS12Config) String() string { return proto.CompactTextString(m) }
func (*UserBLS12Config) ProtoMessage()    {}
func (*UserBLS12Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{2}
}
func (m *UserBLS12Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBLS12Config.Unmarshal(m, b)
}
func (m *UserBLS12Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBLS12Config.Marshal(b, m, deterministic)
}
func (m *UserBLS12Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBLS12Config.Merge(m, src)
}
func (m *UserBLS12Config) XXX_Size() int {
	return xxx_messageInfo_UserBLS12Config.Size(m)
}
func (m *UserBLS12Config) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBLS12Config.DiscardUnknown(m)
}

var xxx_messageInfo_UserBLS12Config proto.InternalMessageInfo

func (m *UserBLS12Config) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UserBLS12Config) GetPubkeyBls() []byte {
	if m != nil {
		return m.PubkeyBls
	}
	return nil
}

func (m *UserBLS12Config) GetPubkeyG() []byte {
	if m != nil {
		return m.PubkeyG
	}
	return nil
}

func (m *UserBLS12Config) GetPubkeyU() [][]byte {
	if m != nil {
		return m.PubkeyU
	}
	return nil
}

func (m *UserBLS12Config) GetPubkeyW() [][]byte {
	if m != nil {
		return m.PubkeyW
	}
	return nil
}

func (m *UserBLS12Config) GetPrikeyBls() []byte {
	if m != nil {
		return m.PrikeyBls
	}
	return nil
}

func (m *UserBLS12Config) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *UserBLS12Config) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *UserBLS12Config) GetTagCount() int32 {
	if m != nil {
		return m.TagCount
	}
	return 0
}

// bucket merkle root of bucket ops
type BucketRoot struct {
	BucketID             int64    `protobuf:"varint,1,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	OpCount              int64    `protobuf:"varint,2,opt,name=OpCount,proto3" json:"OpCount,omitempty"`
	Root                 []byte   `protobuf:"bytes,3,opt,name=Root,proto3" json:"Root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketRoot) Reset()         { *m = BucketRoot{} }
func (m *BucketRoot) String() string { return proto.CompactTextString(m) }
func (*BucketRoot) ProtoMessage()    {}
func (*BucketRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{3}
}
func (m *BucketRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketRoot.Unmarshal(m, b)
}
func (m *BucketRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketRoot.Marshal(b, m, deterministic)
}
func (m *BucketRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketRoot.Merge(m, src)
}
func (m *BucketRoot) XXX_Size() int {
	return xxx_messageInfo_BucketRoot.Size(m)
}
func (m *BucketRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketRoot.DiscardUnknown(m)
}

var xxx_messageInfo_BucketRoot proto.InternalMessageInfo

func (m *BucketRoot) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *BucketRoot) GetOpCount() int64 {
	if m != nil {
		return m.OpCount
	}
	return 0
}

func (m *BucketRoot) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

// lfs merkle root of buckets' merkle root
type LfsRoot struct {
	CTime                int64         `protobuf:"varint,1,opt,name=CTime,proto3" json:"CTime,omitempty"`
	Root                 []byte        `protobuf:"bytes,2,opt,name=Root,proto3" json:"Root,omitempty"`
	BRoots               []*BucketRoot `protobuf:"bytes,3,rep,name=BRoots,proto3" json:"BRoots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LfsRoot) Reset()         { *m = LfsRoot{} }
func (m *LfsRoot) String() string { return proto.CompactTextString(m) }
func (*LfsRoot) ProtoMessage()    {}
func (*LfsRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{4}
}
func (m *LfsRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LfsRoot.Unmarshal(m, b)
}
func (m *LfsRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LfsRoot.Marshal(b, m, deterministic)
}
func (m *LfsRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LfsRoot.Merge(m, src)
}
func (m *LfsRoot) XXX_Size() int {
	return xxx_messageInfo_LfsRoot.Size(m)
}
func (m *LfsRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_LfsRoot.DiscardUnknown(m)
}

var xxx_messageInfo_LfsRoot proto.InternalMessageInfo

func (m *LfsRoot) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *LfsRoot) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *LfsRoot) GetBRoots() []*BucketRoot {
	if m != nil {
		return m.BRoots
	}
	return nil
}

// lfs superBlock information
type SuperBlockInfo struct {
	Version              int32      `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	MetaBackupCount      int32      `protobuf:"varint,2,opt,name=MetaBackupCount,proto3" json:"MetaBackupCount,omitempty"`
	CTime                int64      `protobuf:"varint,3,opt,name=CTime,proto3" json:"CTime,omitempty"`
	NextBucketID         int64      `protobuf:"varint,4,opt,name=NextBucketID,proto3" json:"NextBucketID,omitempty"`
	LRoot                []*LfsRoot `protobuf:"bytes,7,rep,name=LRoot,proto3" json:"LRoot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SuperBlockInfo) Reset()         { *m = SuperBlockInfo{} }
func (m *SuperBlockInfo) String() string { return proto.CompactTextString(m) }
func (*SuperBlockInfo) ProtoMessage()    {}
func (*SuperBlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{5}
}
func (m *SuperBlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperBlockInfo.Unmarshal(m, b)
}
func (m *SuperBlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperBlockInfo.Marshal(b, m, deterministic)
}
func (m *SuperBlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperBlockInfo.Merge(m, src)
}
func (m *SuperBlockInfo) XXX_Size() int {
	return xxx_messageInfo_SuperBlockInfo.Size(m)
}
func (m *SuperBlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperBlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SuperBlockInfo proto.InternalMessageInfo

func (m *SuperBlockInfo) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SuperBlockInfo) GetMetaBackupCount() int32 {
	if m != nil {
		return m.MetaBackupCount
	}
	return 0
}

func (m *SuperBlockInfo) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *SuperBlockInfo) GetNextBucketID() int64 {
	if m != nil {
		return m.NextBucketID
	}
	return 0
}

func (m *SuperBlockInfo) GetLRoot() []*LfsRoot {
	if m != nil {
		return m.LRoot
	}
	return nil
}

// lfs bucket options
type BucketOptions struct {
	Version              int32    `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Policy               int32    `protobuf:"varint,2,opt,name=Policy,proto3" json:"Policy,omitempty"`
	DataCount            int32    `protobuf:"varint,3,opt,name=DataCount,proto3" json:"DataCount,omitempty"`
	ParityCount          int32    `protobuf:"varint,4,opt,name=ParityCount,proto3" json:"ParityCount,omitempty"`
	TagFlag              int32    `protobuf:"varint,5,opt,name=TagFlag,proto3" json:"TagFlag,omitempty"`
	SegmentSize          int32    `protobuf:"varint,6,opt,name=SegmentSize,proto3" json:"SegmentSize,omitempty"`
	SegmentCount         int32    `protobuf:"varint,7,opt,name=SegmentCount,proto3" json:"SegmentCount,omitempty"`
	Encryption           int32    `protobuf:"varint,8,opt,name=Encryption,proto3" json:"Encryption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketOptions) Reset()         { *m = BucketOptions{} }
func (m *BucketOptions) String() string { return proto.CompactTextString(m) }
func (*BucketOptions) ProtoMessage()    {}
func (*BucketOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{6}
}
func (m *BucketOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketOptions.Unmarshal(m, b)
}
func (m *BucketOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketOptions.Marshal(b, m, deterministic)
}
func (m *BucketOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketOptions.Merge(m, src)
}
func (m *BucketOptions) XXX_Size() int {
	return xxx_messageInfo_BucketOptions.Size(m)
}
func (m *BucketOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BucketOptions proto.InternalMessageInfo

func (m *BucketOptions) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BucketOptions) GetPolicy() int32 {
	if m != nil {
		return m.Policy
	}
	return 0
}

func (m *BucketOptions) GetDataCount() int32 {
	if m != nil {
		return m.DataCount
	}
	return 0
}

func (m *BucketOptions) GetParityCount() int32 {
	if m != nil {
		return m.ParityCount
	}
	return 0
}

func (m *BucketOptions) GetTagFlag() int32 {
	if m != nil {
		return m.TagFlag
	}
	return 0
}

func (m *BucketOptions) GetSegmentSize() int32 {
	if m != nil {
		return m.SegmentSize
	}
	return 0
}

func (m *BucketOptions) GetSegmentCount() int32 {
	if m != nil {
		return m.SegmentCount
	}
	return 0
}

func (m *BucketOptions) GetEncryption() int32 {
	if m != nil {
		return m.Encryption
	}
	return 0
}

// lfs bucket information
type BucketInfo struct {
	Name                 string         `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	BucketID             int64          `protobuf:"varint,2,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	CTime                int64          `protobuf:"varint,3,opt,name=CTime,proto3" json:"CTime,omitempty"`
	BOpts                *BucketOptions `protobuf:"bytes,4,opt,name=BOpts,proto3" json:"BOpts,omitempty"`
	Length               int64          `protobuf:"varint,5,opt,name=Length,proto3" json:"Length,omitempty"`
	MTime                int64          `protobuf:"varint,7,opt,name=MTime,proto3" json:"MTime,omitempty"`
	ObjectsBlockSize     int64          `protobuf:"varint,8,opt,name=ObjectsBlockSize,proto3" json:"ObjectsBlockSize,omitempty"`
	Deletion             bool           `protobuf:"varint,9,opt,name=Deletion,proto3" json:"Deletion,omitempty"`
	NextObjectID         int64          `protobuf:"varint,10,opt,name=NextObjectID,proto3" json:"NextObjectID,omitempty"`
	NextOpID             int64          `protobuf:"varint,11,opt,name=NextOpID,proto3" json:"NextOpID,omitempty"`
	Root                 []byte         `protobuf:"bytes,12,opt,name=Root,proto3" json:"Root,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BucketInfo) Reset()         { *m = BucketInfo{} }
func (m *BucketInfo) String() string { return proto.CompactTextString(m) }
func (*BucketInfo) ProtoMessage()    {}
func (*BucketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{7}
}
func (m *BucketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketInfo.Unmarshal(m, b)
}
func (m *BucketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketInfo.Marshal(b, m, deterministic)
}
func (m *BucketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketInfo.Merge(m, src)
}
func (m *BucketInfo) XXX_Size() int {
	return xxx_messageInfo_BucketInfo.Size(m)
}
func (m *BucketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BucketInfo proto.InternalMessageInfo

func (m *BucketInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BucketInfo) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *BucketInfo) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *BucketInfo) GetBOpts() *BucketOptions {
	if m != nil {
		return m.BOpts
	}
	return nil
}

func (m *BucketInfo) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *BucketInfo) GetMTime() int64 {
	if m != nil {
		return m.MTime
	}
	return 0
}

func (m *BucketInfo) GetObjectsBlockSize() int64 {
	if m != nil {
		return m.ObjectsBlockSize
	}
	return 0
}

func (m *BucketInfo) GetDeletion() bool {
	if m != nil {
		return m.Deletion
	}
	return false
}

func (m *BucketInfo) GetNextObjectID() int64 {
	if m != nil {
		return m.NextObjectID
	}
	return 0
}

func (m *BucketInfo) GetNextOpID() int64 {
	if m != nil {
		return m.NextOpID
	}
	return 0
}

func (m *BucketInfo) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

// lfs object plus part information
type ObjectInfo struct {
	Info                 *Object       `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	Length               int64         `protobuf:"varint,2,opt,name=Length,proto3" json:"Length,omitempty"`
	CTime                int64         `protobuf:"varint,3,opt,name=CTime,proto3" json:"CTime,omitempty"`
	MTime                int64         `protobuf:"varint,4,opt,name=MTime,proto3" json:"MTime,omitempty"`
	PartCount            int64         `protobuf:"varint,5,opt,name=PartCount,proto3" json:"PartCount,omitempty"`
	ETag                 string        `protobuf:"bytes,6,opt,name=ETag,proto3" json:"ETag,omitempty"`
	Deletion             bool          `protobuf:"varint,7,opt,name=Deletion,proto3" json:"Deletion,omitempty"`
	Parts                []*ObjectPart `protobuf:"bytes,10,rep,name=Parts,proto3" json:"Parts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ObjectInfo) Reset()         { *m = ObjectInfo{} }
func (m *ObjectInfo) String() string { return proto.CompactTextString(m) }
func (*ObjectInfo) ProtoMessage()    {}
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{8}
}
func (m *ObjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectInfo.Unmarshal(m, b)
}
func (m *ObjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectInfo.Marshal(b, m, deterministic)
}
func (m *ObjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectInfo.Merge(m, src)
}
func (m *ObjectInfo) XXX_Size() int {
	return xxx_messageInfo_ObjectInfo.Size(m)
}
func (m *ObjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectInfo proto.InternalMessageInfo

func (m *ObjectInfo) GetInfo() *Object {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ObjectInfo) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ObjectInfo) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *ObjectInfo) GetMTime() int64 {
	if m != nil {
		return m.MTime
	}
	return 0
}

func (m *ObjectInfo) GetPartCount() int64 {
	if m != nil {
		return m.PartCount
	}
	return 0
}

func (m *ObjectInfo) GetETag() string {
	if m != nil {
		return m.ETag
	}
	return ""
}

func (m *ObjectInfo) GetDeletion() bool {
	if m != nil {
		return m.Deletion
	}
	return false
}

func (m *ObjectInfo) GetParts() []*ObjectPart {
	if m != nil {
		return m.Parts
	}
	return nil
}

// object information
// insert into objectInfo when create a new object
type Object struct {
	Name                 string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	BucketID             int64             `protobuf:"varint,2,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	CTime                int64             `protobuf:"varint,3,opt,name=CTime,proto3" json:"CTime,omitempty"`
	ObjectID             int64             `protobuf:"varint,4,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	Dir                  bool              `protobuf:"varint,5,opt,name=Dir,proto3" json:"Dir,omitempty"`
	ContentType          string            `protobuf:"bytes,9,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,10,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{9}
}
func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Object) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *Object) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *Object) GetObjectID() int64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *Object) GetDir() bool {
	if m != nil {
		return m.Dir
	}
	return false
}

func (m *Object) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Object) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// lfs object part informations
// insert into objectInfo when add data to an existing object
type ObjectPart struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ObjectID             int64    `protobuf:"varint,2,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	PartID               int64    `protobuf:"varint,3,opt,name=PartID,proto3" json:"PartID,omitempty"`
	Start                int64    `protobuf:"varint,4,opt,name=Start,proto3" json:"Start,omitempty"`
	Length               int64    `protobuf:"varint,5,opt,name=Length,proto3" json:"Length,omitempty"`
	CTime                int64    `protobuf:"varint,6,opt,name=CTime,proto3" json:"CTime,omitempty"`
	ETag                 string   `protobuf:"bytes,7,opt,name=ETag,proto3" json:"ETag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectPart) Reset()         { *m = ObjectPart{} }
func (m *ObjectPart) String() string { return proto.CompactTextString(m) }
func (*ObjectPart) ProtoMessage()    {}
func (*ObjectPart) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{10}
}
func (m *ObjectPart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectPart.Unmarshal(m, b)
}
func (m *ObjectPart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectPart.Marshal(b, m, deterministic)
}
func (m *ObjectPart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectPart.Merge(m, src)
}
func (m *ObjectPart) XXX_Size() int {
	return xxx_messageInfo_ObjectPart.Size(m)
}
func (m *ObjectPart) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectPart.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectPart proto.InternalMessageInfo

func (m *ObjectPart) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectPart) GetObjectID() int64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *ObjectPart) GetPartID() int64 {
	if m != nil {
		return m.PartID
	}
	return 0
}

func (m *ObjectPart) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ObjectPart) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ObjectPart) GetCTime() int64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *ObjectPart) GetETag() string {
	if m != nil {
		return m.ETag
	}
	return ""
}

type DeleteObject struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ObjectID             int64    `protobuf:"varint,2,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteObject) Reset()         { *m = DeleteObject{} }
func (m *DeleteObject) String() string { return proto.CompactTextString(m) }
func (*DeleteObject) ProtoMessage()    {}
func (*DeleteObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{11}
}
func (m *DeleteObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteObject.Unmarshal(m, b)
}
func (m *DeleteObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteObject.Marshal(b, m, deterministic)
}
func (m *DeleteObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteObject.Merge(m, src)
}
func (m *DeleteObject) XXX_Size() int {
	return xxx_messageInfo_DeleteObject.Size(m)
}
func (m *DeleteObject) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteObject.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteObject proto.InternalMessageInfo

func (m *DeleteObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteObject) GetObjectID() int64 {
	if m != nil {
		return m.ObjectID
	}
	return 0
}

func (m *DeleteObject) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

//objects元数据最终存储的格式是一串可压缩的操作记录
type OpRecord struct {
	OpType               LfsOp    `protobuf:"varint,1,opt,name=OpType,proto3,enum=mefs.pb.LfsOp" json:"OpType,omitempty"`
	OpID                 int64    `protobuf:"varint,2,opt,name=OpID,proto3" json:"OpID,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpRecord) Reset()         { *m = OpRecord{} }
func (m *OpRecord) String() string { return proto.CompactTextString(m) }
func (*OpRecord) ProtoMessage()    {}
func (*OpRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{12}
}
func (m *OpRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpRecord.Unmarshal(m, b)
}
func (m *OpRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpRecord.Marshal(b, m, deterministic)
}
func (m *OpRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpRecord.Merge(m, src)
}
func (m *OpRecord) XXX_Size() int {
	return xxx_messageInfo_OpRecord.Size(m)
}
func (m *OpRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_OpRecord.DiscardUnknown(m)
}

var xxx_messageInfo_OpRecord proto.InternalMessageInfo

func (m *OpRecord) GetOpType() LfsOp {
	if m != nil {
		return m.OpType
	}
	return LfsOp_OpErr
}

func (m *OpRecord) GetOpID() int64 {
	if m != nil {
		return m.OpID
	}
	return 0
}

func (m *OpRecord) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CancelOp struct {
	OpType               LfsOp    `protobuf:"varint,1,opt,name=OpType,proto3,enum=mefs.pb.LfsOp" json:"OpType,omitempty"`
	OpID                 int64    `protobuf:"varint,2,opt,name=OpID,proto3" json:"OpID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOp) Reset()         { *m = CancelOp{} }
func (m *CancelOp) String() string { return proto.CompactTextString(m) }
func (*CancelOp) ProtoMessage()    {}
func (*CancelOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{13}
}
func (m *CancelOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOp.Unmarshal(m, b)
}
func (m *CancelOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOp.Marshal(b, m, deterministic)
}
func (m *CancelOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOp.Merge(m, src)
}
func (m *CancelOp) XXX_Size() int {
	return xxx_messageInfo_CancelOp.Size(m)
}
func (m *CancelOp) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOp.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOp proto.InternalMessageInfo

func (m *CancelOp) GetOpType() LfsOp {
	if m != nil {
		return m.OpType
	}
	return LfsOp_OpErr
}

func (m *CancelOp) GetOpID() int64 {
	if m != nil {
		return m.OpID
	}
	return 0
}

// data block's option
type BlockOptions struct {
	Bopts                *BucketOptions `protobuf:"bytes,1,opt,name=Bopts,proto3" json:"Bopts,omitempty"`
	Start                int32          `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	UserID               string         `protobuf:"bytes,11,opt,name=UserID,proto3" json:"UserID,omitempty"`
	QueryID              string         `protobuf:"bytes,12,opt,name=QueryID,proto3" json:"QueryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockOptions) Reset()         { *m = BlockOptions{} }
func (m *BlockOptions) String() string { return proto.CompactTextString(m) }
func (*BlockOptions) ProtoMessage()    {}
func (*BlockOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{14}
}
func (m *BlockOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockOptions.Unmarshal(m, b)
}
func (m *BlockOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockOptions.Marshal(b, m, deterministic)
}
func (m *BlockOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockOptions.Merge(m, src)
}
func (m *BlockOptions) XXX_Size() int {
	return xxx_messageInfo_BlockOptions.Size(m)
}
func (m *BlockOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BlockOptions proto.InternalMessageInfo

func (m *BlockOptions) GetBopts() *BucketOptions {
	if m != nil {
		return m.Bopts
	}
	return nil
}

func (m *BlockOptions) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *BlockOptions) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *BlockOptions) GetQueryID() string {
	if m != nil {
		return m.QueryID
	}
	return ""
}

// share link information
type ShareLink struct {
	UserID               string         `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	QueryID              string         `protobuf:"bytes,2,opt,name=QueryID,proto3" json:"QueryID,omitempty"`
	BucketName           string         `protobuf:"bytes,3,opt,name=BucketName,proto3" json:"BucketName,omitempty"`
	ObjectName           string         `protobuf:"bytes,4,opt,name=ObjectName,proto3" json:"ObjectName,omitempty"`
	BucketID             int64          `protobuf:"varint,5,opt,name=BucketID,proto3" json:"BucketID,omitempty"`
	BOpts                *BucketOptions `protobuf:"bytes,6,opt,name=BOpts,proto3" json:"BOpts,omitempty"`
	OParts               []*ObjectPart  `protobuf:"bytes,7,rep,name=OParts,proto3" json:"OParts,omitempty"`
	DecKey               []byte         `protobuf:"bytes,8,opt,name=DecKey,proto3" json:"DecKey,omitempty"`
	KPs                  string         `protobuf:"bytes,11,opt,name=KPs,proto3" json:"KPs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShareLink) Reset()         { *m = ShareLink{} }
func (m *ShareLink) String() string { return proto.CompactTextString(m) }
func (*ShareLink) ProtoMessage()    {}
func (*ShareLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{15}
}
func (m *ShareLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareLink.Unmarshal(m, b)
}
func (m *ShareLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareLink.Marshal(b, m, deterministic)
}
func (m *ShareLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareLink.Merge(m, src)
}
func (m *ShareLink) XXX_Size() int {
	return xxx_messageInfo_ShareLink.Size(m)
}
func (m *ShareLink) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareLink.DiscardUnknown(m)
}

var xxx_messageInfo_ShareLink proto.InternalMessageInfo

func (m *ShareLink) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ShareLink) GetQueryID() string {
	if m != nil {
		return m.QueryID
	}
	return ""
}

func (m *ShareLink) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *ShareLink) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

func (m *ShareLink) GetBucketID() int64 {
	if m != nil {
		return m.BucketID
	}
	return 0
}

func (m *ShareLink) GetBOpts() *BucketOptions {
	if m != nil {
		return m.BOpts
	}
	return nil
}

func (m *ShareLink) GetOParts() []*ObjectPart {
	if m != nil {
		return m.OParts
	}
	return nil
}

func (m *ShareLink) GetDecKey() []byte {
	if m != nil {
		return m.DecKey
	}
	return nil
}

func (m *ShareLink) GetKPs() string {
	if m != nil {
		return m.KPs
	}
	return ""
}

type BucketContent struct {
	ChunkNum             int32    `protobuf:"varint,1,opt,name=ChunkNum,proto3" json:"ChunkNum,omitempty"`
	SegSize              int32    `protobuf:"varint,2,opt,name=SegSize,proto3" json:"SegSize,omitempty"`
	SegCount             int32    `protobuf:"varint,3,opt,name=SegCount,proto3" json:"SegCount,omitempty"`
	StripeNum            int64    `protobuf:"varint,4,opt,name=StripeNum,proto3" json:"StripeNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketContent) Reset()         { *m = BucketContent{} }
func (m *BucketContent) String() string { return proto.CompactTextString(m) }
func (*BucketContent) ProtoMessage()    {}
func (*BucketContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{16}
}
func (m *BucketContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketContent.Unmarshal(m, b)
}
func (m *BucketContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketContent.Marshal(b, m, deterministic)
}
func (m *BucketContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketContent.Merge(m, src)
}
func (m *BucketContent) XXX_Size() int {
	return xxx_messageInfo_BucketContent.Size(m)
}
func (m *BucketContent) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketContent.DiscardUnknown(m)
}

var xxx_messageInfo_BucketContent proto.InternalMessageInfo

func (m *BucketContent) GetChunkNum() int32 {
	if m != nil {
		return m.ChunkNum
	}
	return 0
}

func (m *BucketContent) GetSegSize() int32 {
	if m != nil {
		return m.SegSize
	}
	return 0
}

func (m *BucketContent) GetSegCount() int32 {
	if m != nil {
		return m.SegCount
	}
	return 0
}

func (m *BucketContent) GetStripeNum() int64 {
	if m != nil {
		return m.StripeNum
	}
	return 0
}

// challenge information
type ChalInfo struct {
	QueryID              string           `protobuf:"bytes,1,opt,name=QueryID,proto3" json:"QueryID,omitempty"`
	KeeperID             string           `protobuf:"bytes,2,opt,name=KeeperID,proto3" json:"KeeperID,omitempty"`
	ProviderID           string           `protobuf:"bytes,3,opt,name=ProviderID,proto3" json:"ProviderID,omitempty"`
	UserID               string           `protobuf:"bytes,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ChalTime             int64            `protobuf:"varint,5,opt,name=ChalTime,proto3" json:"ChalTime,omitempty"`
	ChalLength           int64            `protobuf:"varint,6,opt,name=ChalLength,proto3" json:"ChalLength,omitempty"`
	SuccessLength        int64            `protobuf:"varint,7,opt,name=SuccessLength,proto3" json:"SuccessLength,omitempty"`
	TotalLength          int64            `protobuf:"varint,8,opt,name=TotalLength,proto3" json:"TotalLength,omitempty"`
	Blocks               []string         `protobuf:"bytes,9,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
	FaultBlocks          []string         `protobuf:"bytes,10,rep,name=FaultBlocks,proto3" json:"FaultBlocks,omitempty"`
	BlsProof             string           `protobuf:"bytes,11,opt,name=BlsProof,proto3" json:"BlsProof,omitempty"`
	Res                  bool             `protobuf:"varint,12,opt,name=Res,proto3" json:"Res,omitempty"`
	KeeperSign           []byte           `protobuf:"bytes,13,opt,name=keeperSign,proto3" json:"keeperSign,omitempty"`
	ProSign              []byte           `protobuf:"bytes,14,opt,name=proSign,proto3" json:"proSign,omitempty"`
	Policy               string           `protobuf:"bytes,20,opt,name=Policy,proto3" json:"Policy,omitempty"`
	RootTime             int64            `protobuf:"varint,21,opt,name=RootTime,proto3" json:"RootTime,omitempty"`
	Buckets              []*BucketContent `protobuf:"bytes,22,rep,name=Buckets,proto3" json:"Buckets,omitempty"`
	ChunkMap             []byte           `protobuf:"bytes,24,opt,name=ChunkMap,proto3" json:"ChunkMap,omitempty"`
	FailMap              []byte           `protobuf:"bytes,25,opt,name=FailMap,proto3" json:"FailMap,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ChalInfo) Reset()         { *m = ChalInfo{} }
func (m *ChalInfo) String() string { return proto.CompactTextString(m) }
func (*ChalInfo) ProtoMessage()    {}
func (*ChalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{17}
}
func (m *ChalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChalInfo.Unmarshal(m, b)
}
func (m *ChalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChalInfo.Marshal(b, m, deterministic)
}
func (m *ChalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChalInfo.Merge(m, src)
}
func (m *ChalInfo) XXX_Size() int {
	return xxx_messageInfo_ChalInfo.Size(m)
}
func (m *ChalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChalInfo proto.InternalMessageInfo

func (m *ChalInfo) GetQueryID() string {
	if m != nil {
		return m.QueryID
	}
	return ""
}

func (m *ChalInfo) GetKeeperID() string {
	if m != nil {
		return m.KeeperID
	}
	return ""
}

func (m *ChalInfo) GetProviderID() string {
	if m != nil {
		return m.ProviderID
	}
	return ""
}

func (m *ChalInfo) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ChalInfo) GetChalTime() int64 {
	if m != nil {
		return m.ChalTime
	}
	return 0
}

func (m *ChalInfo) GetChalLength() int64 {
	if m != nil {
		return m.ChalLength
	}
	return 0
}

func (m *ChalInfo) GetSuccessLength() int64 {
	if m != nil {
		return m.SuccessLength
	}
	return 0
}

func (m *ChalInfo) GetTotalLength() int64 {
	if m != nil {
		return m.TotalLength
	}
	return 0
}

func (m *ChalInfo) GetBlocks() []string {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *ChalInfo) GetFaultBlocks() []string {
	if m != nil {
		return m.FaultBlocks
	}
	return nil
}

func (m *ChalInfo) GetBlsProof() string {
	if m != nil {
		return m.BlsProof
	}
	return ""
}

func (m *ChalInfo) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

func (m *ChalInfo) GetKeeperSign() []byte {
	if m != nil {
		return m.KeeperSign
	}
	return nil
}

func (m *ChalInfo) GetProSign() []byte {
	if m != nil {
		return m.ProSign
	}
	return nil
}

func (m *ChalInfo) GetPolicy() string {
	if m != nil {
		return m.Policy
	}
	return ""
}

func (m *ChalInfo) GetRootTime() int64 {
	if m != nil {
		return m.RootTime
	}
	return 0
}

func (m *ChalInfo) GetBuckets() []*BucketContent {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *ChalInfo) GetChunkMap() []byte {
	if m != nil {
		return m.ChunkMap
	}
	return nil
}

func (m *ChalInfo) GetFailMap() []byte {
	if m != nil {
		return m.FailMap
	}
	return nil
}

type ChannelSign struct {
	ChannelID            string   `protobuf:"bytes,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Sig                  []byte   `protobuf:"bytes,3,opt,name=Sig,proto3" json:"Sig,omitempty"`
	PubKey               []byte   `protobuf:"bytes,4,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelSign) Reset()         { *m = ChannelSign{} }
func (m *ChannelSign) String() string { return proto.CompactTextString(m) }
func (*ChannelSign) ProtoMessage()    {}
func (*ChannelSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{18}
}
func (m *ChannelSign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelSign.Unmarshal(m, b)
}
func (m *ChannelSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelSign.Marshal(b, m, deterministic)
}
func (m *ChannelSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelSign.Merge(m, src)
}
func (m *ChannelSign) XXX_Size() int {
	return xxx_messageInfo_ChannelSign.Size(m)
}
func (m *ChannelSign) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelSign.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelSign proto.InternalMessageInfo

func (m *ChannelSign) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *ChannelSign) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ChannelSign) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *ChannelSign) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type STValue struct {
	Status               int32    `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	Length               int64    `protobuf:"varint,3,opt,name=Length,proto3" json:"Length,omitempty"`
	Value                []byte   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	Root                 []byte   `protobuf:"bytes,5,opt,name=Root,proto3" json:"Root,omitempty"`
	Share                []int64  `protobuf:"varint,6,rep,packed,name=Share,proto3" json:"Share,omitempty"`
	Sign                 [][]byte `protobuf:"bytes,7,rep,name=Sign,proto3" json:"Sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *STValue) Reset()         { *m = STValue{} }
func (m *STValue) String() string { return proto.CompactTextString(m) }
func (*STValue) ProtoMessage()    {}
func (*STValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{19}
}
func (m *STValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_STValue.Unmarshal(m, b)
}
func (m *STValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_STValue.Marshal(b, m, deterministic)
}
func (m *STValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_STValue.Merge(m, src)
}
func (m *STValue) XXX_Size() int {
	return xxx_messageInfo_STValue.Size(m)
}
func (m *STValue) XXX_DiscardUnknown() {
	xxx_messageInfo_STValue.DiscardUnknown(m)
}

var xxx_messageInfo_STValue proto.InternalMessageInfo

func (m *STValue) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *STValue) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *STValue) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *STValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *STValue) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *STValue) GetShare() []int64 {
	if m != nil {
		return m.Share
	}
	return nil
}

func (m *STValue) GetSign() [][]byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type KVData struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVData) Reset()         { *m = KVData{} }
func (m *KVData) String() string { return proto.CompactTextString(m) }
func (*KVData) ProtoMessage()    {}
func (*KVData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3c77393cf6fe78, []int{20}
}
func (m *KVData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVData.Unmarshal(m, b)
}
func (m *KVData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVData.Marshal(b, m, deterministic)
}
func (m *KVData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVData.Merge(m, src)
}
func (m *KVData) XXX_Size() int {
	return xxx_messageInfo_KVData.Size(m)
}
func (m *KVData) XXX_DiscardUnknown() {
	xxx_messageInfo_KVData.DiscardUnknown(m)
}

var xxx_messageInfo_KVData proto.InternalMessageInfo

func (m *KVData) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KVData) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("mefs.pb.OpType", OpType_name, OpType_value)
	proto.RegisterEnum("mefs.pb.KeyType", KeyType_name, KeyType_value)
	proto.RegisterEnum("mefs.pb.LfsOp", LfsOp_name, LfsOp_value)
	proto.RegisterType((*KeyMeta)(nil), "mefs.pb.KeyMeta")
	proto.RegisterType((*Record)(nil), "mefs.pb.Record")
	proto.RegisterType((*UserBLS12Config)(nil), "mefs.pb.UserBLS12Config")
	proto.RegisterType((*BucketRoot)(nil), "mefs.pb.BucketRoot")
	proto.RegisterType((*LfsRoot)(nil), "mefs.pb.LfsRoot")
	proto.RegisterType((*SuperBlockInfo)(nil), "mefs.pb.SuperBlockInfo")
	proto.RegisterType((*BucketOptions)(nil), "mefs.pb.BucketOptions")
	proto.RegisterType((*BucketInfo)(nil), "mefs.pb.BucketInfo")
	proto.RegisterType((*ObjectInfo)(nil), "mefs.pb.ObjectInfo")
	proto.RegisterType((*Object)(nil), "mefs.pb.Object")
	proto.RegisterMapType((map[string]string)(nil), "mefs.pb.Object.MetadataEntry")
	proto.RegisterType((*ObjectPart)(nil), "mefs.pb.ObjectPart")
	proto.RegisterType((*DeleteObject)(nil), "mefs.pb.DeleteObject")
	proto.RegisterType((*OpRecord)(nil), "mefs.pb.OpRecord")
	proto.RegisterType((*CancelOp)(nil), "mefs.pb.CancelOp")
	proto.RegisterType((*BlockOptions)(nil), "mefs.pb.BlockOptions")
	proto.RegisterType((*ShareLink)(nil), "mefs.pb.ShareLink")
	proto.RegisterType((*BucketContent)(nil), "mefs.pb.BucketContent")
	proto.RegisterType((*ChalInfo)(nil), "mefs.pb.ChalInfo")
	proto.RegisterType((*ChannelSign)(nil), "mefs.pb.ChannelSign")
	proto.RegisterType((*STValue)(nil), "mefs.pb.STValue")
	proto.RegisterType((*KVData)(nil), "mefs.pb.KVData")
}

func init() { proto.RegisterFile("mefs.proto", fileDescriptor_2b3c77393cf6fe78) }

var fileDescriptor_2b3c77393cf6fe78 = []byte{
	// 1819 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcd, 0x73, 0xe3, 0x48,
	0x15, 0x1f, 0x59, 0xb6, 0x65, 0xbd, 0x38, 0x49, 0xa3, 0x9d, 0x0d, 0xda, 0x10, 0x16, 0x23, 0xa8,
	0x25, 0x9b, 0xd9, 0x9a, 0x5a, 0xc2, 0x85, 0x8f, 0x53, 0x1c, 0x27, 0x43, 0x2a, 0x99, 0xd8, 0xb4,
	0x32, 0x33, 0x7b, 0xdc, 0x8e, 0xdd, 0xf6, 0x08, 0x2b, 0x92, 0x4a, 0x6a, 0x4f, 0xad, 0xb9, 0x50,
	0x5b, 0xc5, 0xdf, 0xc0, 0x91, 0x0b, 0x57, 0xce, 0x1c, 0xf8, 0x13, 0x38, 0xf1, 0x97, 0x70, 0xe3,
	0x4e, 0xbd, 0xd7, 0xad, 0x0f, 0x7b, 0x3e, 0xa0, 0x0a, 0x4e, 0xee, 0xdf, 0x7b, 0xdd, 0xaf, 0xdf,
	0xf7, 0x6b, 0x19, 0xe0, 0x41, 0xce, 0x8b, 0xa7, 0x59, 0x9e, 0xaa, 0xd4, 0x73, 0xf4, 0xfa, 0x3e,
	0xf8, 0xd6, 0x02, 0xe7, 0x5a, 0xae, 0x9f, 0x4b, 0x25, 0x3c, 0x1f, 0x9c, 0x37, 0x32, 0x2f, 0xa2,
	0x34, 0xf1, 0xad, 0x81, 0x75, 0xdc, 0xe1, 0x25, 0xf4, 0x4e, 0xc0, 0x59, 0xca, 0xf5, 0xdd, 0x3a,
	0x93, 0x7e, 0x6b, 0x60, 0x1d, 0xef, 0x9d, 0xb2, 0xa7, 0x46, 0xc0, 0xd3, 0x6b, 0x4d, 0xe7, 0xe5,
	0x06, 0xef, 0x00, 0xba, 0x0f, 0x22, 0x4a, 0xae, 0x46, 0xbe, 0x3d, 0xb0, 0x8e, 0x5d, 0x6e, 0x10,
	0x4a, 0x4f, 0x33, 0x15, 0xa5, 0x49, 0xe1, 0xb7, 0x07, 0xf6, 0xb1, 0xcb, 0x4b, 0x18, 0xdc, 0x42,
	0x97, 0xcb, 0x69, 0x9a, 0xcf, 0x3c, 0x06, 0xf6, 0x52, 0xae, 0xe9, 0xf6, 0x3e, 0xc7, 0xa5, 0xf7,
	0x18, 0x3a, 0x6f, 0x44, 0xbc, 0xd2, 0xf7, 0xf6, 0xb9, 0x06, 0xde, 0x11, 0xb8, 0x45, 0xb4, 0x48,
	0x84, 0x5a, 0xe5, 0x92, 0xae, 0xe9, 0xf3, 0x9a, 0x10, 0xfc, 0xcb, 0x82, 0xfd, 0x17, 0x85, 0xcc,
	0x87, 0x37, 0xe1, 0x4f, 0x4f, 0xcf, 0xd3, 0x64, 0x1e, 0x2d, 0x3e, 0x60, 0xdb, 0x11, 0xb8, 0xd9,
	0xea, 0x7e, 0x29, 0xd7, 0xc3, 0xb8, 0x30, 0xb7, 0xd4, 0x04, 0x3c, 0xa7, 0xc1, 0x33, 0x73, 0x4f,
	0x09, 0x6b, 0xce, 0x0b, 0xb2, 0xa7, 0xe2, 0xbc, 0xa8, 0x39, 0xaf, 0xfc, 0x4e, 0x93, 0xf3, 0x8a,
	0xee, 0xca, 0x23, 0x73, 0x57, 0xd7, 0xdc, 0x55, 0x12, 0xbc, 0x3e, 0x58, 0x5f, 0xf9, 0x0e, 0x51,
	0xad, 0xaf, 0xd0, 0xf2, 0x69, 0xba, 0x4a, 0x94, 0x0f, 0xa4, 0xaf, 0x06, 0xde, 0x21, 0xf4, 0x94,
	0x58, 0x9c, 0x13, 0x63, 0x87, 0x18, 0x15, 0x0e, 0x5e, 0x02, 0x0c, 0x57, 0xd3, 0xa5, 0x54, 0x3c,
	0x4d, 0x69, 0xa7, 0x46, 0x57, 0x23, 0x32, 0xd9, 0xe6, 0x15, 0x46, 0x0d, 0xc7, 0x99, 0x16, 0xd2,
	0x22, 0x56, 0x09, 0x3d, 0x0f, 0xda, 0x78, 0xda, 0x18, 0x4b, 0xeb, 0xe0, 0x6b, 0x70, 0x6e, 0xe6,
	0x05, 0x09, 0x7d, 0x0c, 0x9d, 0xf3, 0xbb, 0xe8, 0x41, 0x1a, 0x89, 0x1a, 0x54, 0x87, 0x5a, 0xf5,
	0x21, 0xef, 0x09, 0x74, 0x87, 0xb8, 0x28, 0x7c, 0x7b, 0x60, 0x1f, 0xef, 0x9c, 0x7e, 0x54, 0x65,
	0x4c, 0xad, 0x23, 0x37, 0x5b, 0x82, 0xbf, 0x5a, 0xb0, 0x17, 0xae, 0x32, 0x99, 0x0f, 0xe3, 0x74,
	0xba, 0xbc, 0x4a, 0xe6, 0x29, 0xaa, 0xf8, 0x72, 0x33, 0x60, 0x06, 0x7a, 0xc7, 0xb0, 0x8f, 0xe9,
	0x3a, 0x14, 0xd3, 0xe5, 0xaa, 0x61, 0x44, 0x87, 0x6f, 0x93, 0x6b, 0x6d, 0xed, 0xa6, 0xb6, 0x01,
	0xf4, 0x6f, 0xe5, 0x37, 0xaa, 0x72, 0x4e, 0x9b, 0x98, 0x1b, 0x34, 0xef, 0x33, 0xe8, 0xdc, 0x90,
	0x49, 0x0e, 0x29, 0x5f, 0xa7, 0xbb, 0x71, 0x04, 0xd7, 0xec, 0xe0, 0xdb, 0x16, 0xec, 0xea, 0x43,
	0x63, 0x9d, 0xcc, 0x1f, 0xd0, 0xfb, 0x00, 0xba, 0x93, 0x34, 0x8e, 0xa6, 0x6b, 0xa3, 0xae, 0x41,
	0x98, 0x14, 0x23, 0xa1, 0x84, 0xb6, 0xc4, 0x26, 0x56, 0x4d, 0xf0, 0x06, 0xb0, 0x33, 0x11, 0x79,
	0xa4, 0xd6, 0x9a, 0xdf, 0x26, 0x7e, 0x93, 0x84, 0x37, 0xde, 0x89, 0xc5, 0x65, 0x2c, 0x16, 0x7e,
	0x47, 0xdf, 0x68, 0x20, 0x9e, 0x0d, 0xe5, 0xe2, 0x41, 0x26, 0x2a, 0x8c, 0x7e, 0x27, 0x29, 0xe1,
	0x3a, 0xbc, 0x49, 0x42, 0x5f, 0x18, 0xa8, 0xc5, 0x3b, 0xb4, 0x65, 0x83, 0xe6, 0x7d, 0x0a, 0x70,
	0x91, 0x4c, 0xf3, 0x35, 0x19, 0xe8, 0xf7, 0x68, 0x47, 0x83, 0x12, 0xfc, 0xbd, 0x55, 0xe6, 0x1d,
	0x05, 0xce, 0x83, 0xf6, 0xad, 0x30, 0x19, 0xe2, 0x72, 0x5a, 0x6f, 0xe4, 0x62, 0x6b, 0x2b, 0x17,
	0xdf, 0x1d, 0xa4, 0x2f, 0xa0, 0x33, 0x1c, 0x67, 0xaa, 0x20, 0x83, 0x77, 0x4e, 0x0f, 0xb6, 0xb2,
	0xc7, 0x78, 0x9b, 0xeb, 0x4d, 0xe8, 0xda, 0x1b, 0x99, 0x2c, 0xd4, 0x6b, 0xf2, 0x80, 0xcd, 0x0d,
	0x42, 0xd9, 0xcf, 0x49, 0xb6, 0xa3, 0x65, 0x13, 0xf0, 0x4e, 0x80, 0x8d, 0xef, 0x7f, 0x2b, 0xa7,
	0xaa, 0xa0, 0x74, 0x23, 0xdf, 0xf4, 0x68, 0xc3, 0x5b, 0x74, 0xd4, 0x7c, 0x24, 0x63, 0x49, 0xa6,
	0xbb, 0x03, 0xeb, 0xb8, 0xc7, 0x2b, 0x5c, 0x26, 0x92, 0x3e, 0x73, 0x35, 0xa2, 0x42, 0x35, 0x89,
	0x54, 0xd2, 0xf0, 0x3c, 0xe1, 0xec, 0x6a, 0x44, 0xf5, 0x6a, 0xf3, 0x0a, 0x57, 0x65, 0xd3, 0x6f,
	0xd4, 0xda, 0x3f, 0x2d, 0x00, 0x73, 0x18, 0x9d, 0xf9, 0x23, 0x68, 0xe3, 0x2f, 0x39, 0x73, 0xe7,
	0x74, 0xbf, 0xf2, 0x82, 0xde, 0xc2, 0x89, 0xd9, 0xb0, 0xbe, 0xb5, 0x6d, 0xfd, 0x3b, 0x3c, 0x5b,
	0xf9, 0xa4, 0xdd, 0xf4, 0xc9, 0x11, 0xb8, 0x13, 0x91, 0x9b, 0x2c, 0xd0, 0x4e, 0xac, 0x09, 0xa8,
	0xe9, 0xc5, 0x9d, 0x58, 0x50, 0x06, 0xb9, 0x9c, 0xd6, 0x1b, 0x9e, 0x71, 0xb6, 0x3c, 0xf3, 0x39,
	0x74, 0xf0, 0x70, 0xe1, 0xc3, 0x56, 0xed, 0x6b, 0xbd, 0x91, 0xc7, 0xf5, 0x8e, 0xe0, 0x8f, 0x2d,
	0xe8, 0x6a, 0xea, 0xff, 0x29, 0x73, 0x0e, 0xa1, 0x57, 0x45, 0x44, 0x9b, 0x58, 0x61, 0x9c, 0x2f,
	0xa3, 0x28, 0x27, 0xfb, 0x7a, 0x1c, 0x97, 0x58, 0x22, 0xe7, 0x69, 0xa2, 0x64, 0xa2, 0x68, 0xba,
	0xb9, 0x74, 0x75, 0x93, 0xe4, 0xfd, 0x02, 0x7a, 0xd8, 0x57, 0x66, 0x42, 0x09, 0x63, 0xce, 0xf7,
	0xb7, 0xcc, 0x79, 0x5a, 0xf2, 0x2f, 0x12, 0x95, 0xaf, 0x79, 0xb5, 0xfd, 0xf0, 0x57, 0xb0, 0xbb,
	0xc1, 0x6a, 0xce, 0x37, 0xf7, 0x1d, 0xf3, 0xcd, 0x35, 0xf3, 0xed, 0x97, 0xad, 0x9f, 0x5b, 0xc1,
	0x5f, 0xaa, 0x4c, 0x40, 0x47, 0xbd, 0xcf, 0x39, 0x95, 0xa9, 0xad, 0x2d, 0x53, 0xb1, 0xdb, 0x88,
	0x5c, 0x99, 0x31, 0x6c, 0x73, 0x83, 0xf0, 0xc2, 0x50, 0x89, 0x5c, 0x95, 0xe1, 0x27, 0xf0, 0xa1,
	0x02, 0xd2, 0x2e, 0xee, 0x6e, 0xf5, 0x7b, 0x4a, 0x07, 0xa7, 0x4e, 0x87, 0x80, 0x43, 0x9f, 0xc2,
	0x2f, 0x3f, 0x1c, 0xcc, 0xf7, 0xea, 0xeb, 0x41, 0xbb, 0x11, 0x4b, 0x5a, 0x07, 0x5f, 0x43, 0x6f,
	0x9c, 0x99, 0xa7, 0xc1, 0x67, 0xd0, 0x1d, 0x67, 0x14, 0x23, 0x8b, 0x5e, 0x20, 0x7b, 0xcd, 0x96,
	0x3c, 0xce, 0xb8, 0xe1, 0xa2, 0x1c, 0x2a, 0x36, 0x2d, 0x9f, 0xd6, 0xd8, 0x21, 0x27, 0x62, 0x1d,
	0xa7, 0x62, 0x56, 0x0e, 0x71, 0x03, 0x83, 0x4b, 0xe8, 0x9d, 0x8b, 0x64, 0x2a, 0xe3, 0x71, 0xf6,
	0xbf, 0xdc, 0x10, 0xfc, 0xc1, 0x82, 0x3e, 0x35, 0x8d, 0x72, 0x0c, 0x60, 0xff, 0x4a, 0xb1, 0x7f,
	0x59, 0xff, 0xa1, 0x7f, 0xe1, 0xa6, 0x3a, 0x28, 0x7a, 0x32, 0xd4, 0x41, 0xc1, 0x67, 0x8c, 0xe9,
	0x1c, 0x2e, 0x37, 0x08, 0xcd, 0xf9, 0xcd, 0x4a, 0xe6, 0xeb, 0xab, 0x11, 0xb5, 0x0e, 0x97, 0x97,
	0x30, 0xf8, 0x53, 0x0b, 0xdc, 0xf0, 0xb5, 0xc8, 0xe5, 0x4d, 0x94, 0x2c, 0x1b, 0xe7, 0xad, 0xf7,
	0x9d, 0x6f, 0x6d, 0x9c, 0xc7, 0x56, 0xaf, 0xf5, 0xa3, 0xd0, 0xe9, 0xf7, 0x5b, 0x83, 0x82, 0x7c,
	0x1d, 0x30, 0xe2, 0xb7, 0x35, 0xbf, 0xa6, 0x6c, 0x54, 0x6b, 0x67, 0xab, 0x5a, 0xab, 0x8e, 0xde,
	0xfd, 0x6f, 0x3a, 0xfa, 0x13, 0xe8, 0x8e, 0x75, 0x0b, 0x71, 0xde, 0xdf, 0x42, 0xcc, 0x16, 0x34,
	0x74, 0x24, 0xa7, 0xd7, 0x72, 0x4d, 0x6d, 0xbc, 0xcf, 0x0d, 0xc2, 0x72, 0xbb, 0x9e, 0x14, 0xc6,
	0x7b, 0xb8, 0x0c, 0x7e, 0x5f, 0x8e, 0x6b, 0x53, 0xe1, 0xa8, 0xf1, 0xf9, 0xeb, 0x55, 0xb2, 0xbc,
	0x5d, 0x3d, 0x98, 0x79, 0x5d, 0x61, 0xf4, 0x53, 0x28, 0x17, 0x34, 0x1e, 0x74, 0x5c, 0x4a, 0x88,
	0xa7, 0x42, 0xb9, 0x68, 0x4e, 0xec, 0x0a, 0x63, 0x27, 0x0d, 0x55, 0x1e, 0x65, 0x12, 0x45, 0xea,
	0x22, 0xab, 0x09, 0xc1, 0xdf, 0xda, 0x78, 0xa1, 0x88, 0xcb, 0x37, 0x4e, 0x19, 0x08, 0x6b, 0x33,
	0x10, 0x87, 0xd0, 0xbb, 0x96, 0x32, 0xa3, 0xe0, 0xe9, 0x18, 0x55, 0x18, 0x83, 0x30, 0xc9, 0xd3,
	0x37, 0xd1, 0x8c, 0xb8, 0x26, 0x48, 0x35, 0xa5, 0x11, 0xf6, 0xf6, 0x46, 0xd8, 0x0f, 0xf5, 0xcd,
	0x54, 0x65, 0x26, 0x38, 0x25, 0x46, 0x99, 0xb8, 0x36, 0x3d, 0x40, 0x17, 0x7b, 0x83, 0xe2, 0xfd,
	0x18, 0x76, 0xc3, 0xd5, 0x74, 0x2a, 0x8b, 0xc2, 0x6c, 0xd1, 0x03, 0x75, 0x93, 0x88, 0xcd, 0xf4,
	0x2e, 0x55, 0x95, 0x18, 0x3d, 0x53, 0x9b, 0x24, 0xd4, 0x8d, 0xca, 0xa4, 0xf0, 0x5d, 0xfa, 0x06,
	0x30, 0x08, 0x4f, 0x5e, 0x8a, 0x55, 0xac, 0x0c, 0x13, 0x88, 0xd9, 0x24, 0x51, 0x6a, 0xc5, 0xc5,
	0x24, 0x4f, 0xd3, 0xb9, 0x09, 0x68, 0x85, 0x31, 0xce, 0x5c, 0x16, 0x54, 0x0c, 0x3d, 0x8e, 0x4b,
	0xb4, 0x67, 0x49, 0xfe, 0x0a, 0xa3, 0x45, 0xe2, 0xef, 0x52, 0x56, 0x34, 0x28, 0xf4, 0x44, 0xcf,
	0x53, 0x62, 0xee, 0x99, 0x67, 0xbd, 0x86, 0x8d, 0x57, 0xda, 0x63, 0xed, 0x3d, 0xf3, 0x4a, 0x3b,
	0x84, 0x1e, 0x0e, 0x68, 0xf2, 0xde, 0xc7, 0xda, 0x7b, 0x25, 0xf6, 0xbe, 0x04, 0x47, 0x67, 0x55,
	0xe1, 0x1f, 0x50, 0xb6, 0x6e, 0x27, 0xb7, 0xc9, 0x36, 0x5e, 0x6e, 0xab, 0xd2, 0xee, 0xb9, 0xc8,
	0x7c, 0x9f, 0x14, 0xa8, 0x30, 0xea, 0x76, 0x29, 0xa2, 0x18, 0x59, 0x9f, 0x68, 0xdd, 0x0c, 0x0c,
	0x96, 0xb0, 0x73, 0xfe, 0x5a, 0x24, 0x89, 0x8c, 0x49, 0xd5, 0x23, 0x70, 0x0d, 0xac, 0x12, 0xa8,
	0x26, 0x60, 0x4f, 0x79, 0xd9, 0xfc, 0x72, 0x22, 0x80, 0xae, 0x0a, 0xa3, 0x85, 0x69, 0x83, 0xb8,
	0x24, 0x83, 0x57, 0xf7, 0x58, 0x3c, 0x6d, 0x5d, 0x3c, 0x1a, 0x05, 0x7f, 0xb6, 0xc0, 0x09, 0xef,
	0xf4, 0xa9, 0x03, 0xe8, 0x86, 0x4a, 0xa8, 0x55, 0x61, 0x6a, 0xc4, 0xa0, 0xcd, 0xbe, 0xf5, 0x8e,
	0x61, 0x62, 0x6f, 0x0f, 0x13, 0xad, 0x51, 0xbb, 0xa9, 0x51, 0xf9, 0x0a, 0xea, 0x34, 0x3e, 0x1e,
	0x50, 0x2e, 0xb6, 0x31, 0xbf, 0x3b, 0xb0, 0x49, 0x2e, 0x02, 0xdc, 0x49, 0x11, 0x73, 0xe8, 0xa3,
	0x8a, 0xd6, 0xc1, 0x97, 0xd0, 0xbd, 0x7e, 0x89, 0xaf, 0x65, 0x2a, 0xf6, 0xfa, 0xdb, 0xf1, 0x5a,
	0xcf, 0xd6, 0xb7, 0x3d, 0x70, 0x72, 0x56, 0xb6, 0x79, 0x6f, 0x17, 0xdc, 0x61, 0x9e, 0x8a, 0xd9,
	0xb9, 0x28, 0x14, 0x7b, 0xe4, 0x39, 0x60, 0x4f, 0x56, 0x8a, 0x59, 0xb8, 0x78, 0x26, 0x15, 0x6b,
	0x79, 0x00, 0xdd, 0xb3, 0x2c, 0x93, 0xc9, 0x8c, 0xd9, 0xb8, 0xd6, 0xf3, 0x8d, 0xb5, 0x4f, 0xfe,
	0x61, 0xd3, 0x47, 0x33, 0x09, 0x71, 0xa1, 0xf3, 0x2a, 0x4f, 0x93, 0x05, 0x7b, 0xe4, 0xf5, 0xd0,
	0x92, 0x58, 0x32, 0x0b, 0x25, 0x4f, 0x56, 0xf7, 0x71, 0x84, 0x5d, 0x48, 0xcb, 0xd1, 0x9f, 0xa1,
	0xcc, 0x46, 0xe1, 0x37, 0x97, 0x21, 0x6b, 0xe3, 0x41, 0x2c, 0xcc, 0x82, 0x75, 0xbc, 0x1d, 0x14,
	0x87, 0xb9, 0x59, 0xb0, 0x2e, 0x9d, 0x35, 0xc5, 0x5c, 0x30, 0x07, 0xb7, 0x51, 0x05, 0x30, 0xf0,
	0xfa, 0x58, 0x02, 0xe9, 0x74, 0x39, 0x49, 0x0b, 0xb6, 0x83, 0xa8, 0x2c, 0x5f, 0xd6, 0x27, 0xe5,
	0xd3, 0x82, 0xed, 0xe2, 0x5d, 0x3a, 0xc9, 0xd8, 0x1e, 0x8a, 0x0a, 0xd5, 0x44, 0xac, 0xd1, 0x53,
	0x6c, 0xdf, 0xdb, 0xa3, 0xc6, 0x71, 0x36, 0x9b, 0x11, 0x66, 0xc8, 0xfe, 0xb5, 0x14, 0xb9, 0x1a,
	0x4a, 0xa1, 0xd8, 0x63, 0x14, 0x48, 0x9d, 0x22, 0x89, 0x14, 0xfb, 0x18, 0x37, 0x23, 0xba, 0x4d,
	0x55, 0x34, 0x5f, 0xb3, 0x03, 0xdc, 0x8c, 0x98, 0x22, 0xcc, 0xbe, 0x5b, 0x6e, 0x0e, 0x55, 0x9a,
	0x31, 0x1f, 0x99, 0xa8, 0x4b, 0x2c, 0x93, 0x85, 0x64, 0x9f, 0xa0, 0x0e, 0x5c, 0x66, 0x22, 0xca,
	0xd9, 0xa1, 0xf7, 0x11, 0xec, 0x5f, 0x7c, 0xa3, 0x64, 0x9e, 0x88, 0xf8, 0x6c, 0x36, 0xcb, 0x65,
	0x51, 0xb0, 0xef, 0xa1, 0xc1, 0xa1, 0x4a, 0x73, 0xb1, 0x90, 0xec, 0x08, 0x2d, 0xa4, 0xb6, 0xc7,
	0x3e, 0xc5, 0xe5, 0x78, 0x3e, 0x97, 0x39, 0xfb, 0x01, 0xdd, 0x97, 0xa1, 0x57, 0xa2, 0x64, 0xc1,
	0x06, 0x78, 0xc2, 0xa4, 0x36, 0xfb, 0x21, 0xca, 0xbf, 0x4a, 0xa6, 0xe9, 0x83, 0x64, 0x3f, 0x31,
	0x8c, 0x78, 0x22, 0xd6, 0xec, 0x18, 0xc1, 0x8d, 0x28, 0xd0, 0x64, 0xf6, 0x39, 0x82, 0x49, 0x5a,
	0xe0, 0x03, 0x8c, 0x9d, 0xd0, 0x8d, 0xb2, 0xc0, 0xef, 0x30, 0xf6, 0xc4, 0xfb, 0x4e, 0x39, 0x05,
	0x74, 0x5f, 0x2e, 0xd8, 0x17, 0x27, 0xcf, 0xa0, 0x43, 0x53, 0x9e, 0x54, 0xc8, 0x2e, 0xf2, 0x9c,
	0x3d, 0xd2, 0xcb, 0xb3, 0xd9, 0x8c, 0x59, 0x68, 0xee, 0x38, 0x33, 0xb9, 0xd0, 0xd2, 0xc8, 0x64,
	0x83, 0xad, 0x91, 0x7e, 0x45, 0xb0, 0xf6, 0x7d, 0x97, 0xfe, 0x60, 0xf9, 0xd9, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xf0, 0x6d, 0x00, 0xca, 0x6e, 0x11, 0x00, 0x00,
}
