// Code generated by protoc-gen-go. DO NOT EDIT.
// source: challenge.proto

package role_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Chalnum struct {
	PubC                 int64    `protobuf:"varint,1,opt,name=PubC,proto3" json:"PubC,omitempty"`
	Indices              []string `protobuf:"bytes,2,rep,name=Indices,proto3" json:"Indices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chalnum) Reset()         { *m = Chalnum{} }
func (m *Chalnum) String() string { return proto.CompactTextString(m) }
func (*Chalnum) ProtoMessage()    {}
func (*Chalnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_4819ccc01c0c0a11, []int{0}
}

func (m *Chalnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chalnum.Unmarshal(m, b)
}
func (m *Chalnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chalnum.Marshal(b, m, deterministic)
}
func (m *Chalnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chalnum.Merge(m, src)
}
func (m *Chalnum) XXX_Size() int {
	return xxx_messageInfo_Chalnum.Size(m)
}
func (m *Chalnum) XXX_DiscardUnknown() {
	xxx_messageInfo_Chalnum.DiscardUnknown(m)
}

var xxx_messageInfo_Chalnum proto.InternalMessageInfo

func (m *Chalnum) GetPubC() int64 {
	if m != nil {
		return m.PubC
	}
	return 0
}

func (m *Chalnum) GetIndices() []string {
	if m != nil {
		return m.Indices
	}
	return nil
}

type Pu struct {
	Provider             string   `protobuf:"bytes,1,opt,name=Provider,proto3" json:"Provider,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pu) Reset()         { *m = Pu{} }
func (m *Pu) String() string { return proto.CompactTextString(m) }
func (*Pu) ProtoMessage()    {}
func (*Pu) Descriptor() ([]byte, []int) {
	return fileDescriptor_4819ccc01c0c0a11, []int{1}
}

func (m *Pu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pu.Unmarshal(m, b)
}
func (m *Pu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pu.Marshal(b, m, deterministic)
}
func (m *Pu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pu.Merge(m, src)
}
func (m *Pu) XXX_Size() int {
	return xxx_messageInfo_Pu.Size(m)
}
func (m *Pu) XXX_DiscardUnknown() {
	xxx_messageInfo_Pu.DiscardUnknown(m)
}

var xxx_messageInfo_Pu proto.InternalMessageInfo

func (m *Pu) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Pu) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type Chalin struct {
	Cidin                map[string]*Cidin   `protobuf:"bytes,1,rep,name=Cidin,proto3" json:"Cidin,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Chalres              map[string]*Chalres `protobuf:"bytes,2,rep,name=Chalres,proto3" json:"Chalres,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Maxlength            uint32              `protobuf:"varint,3,opt,name=maxlength,proto3" json:"maxlength,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Chalin) Reset()         { *m = Chalin{} }
func (m *Chalin) String() string { return proto.CompactTextString(m) }
func (*Chalin) ProtoMessage()    {}
func (*Chalin) Descriptor() ([]byte, []int) {
	return fileDescriptor_4819ccc01c0c0a11, []int{2}
}

func (m *Chalin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chalin.Unmarshal(m, b)
}
func (m *Chalin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chalin.Marshal(b, m, deterministic)
}
func (m *Chalin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chalin.Merge(m, src)
}
func (m *Chalin) XXX_Size() int {
	return xxx_messageInfo_Chalin.Size(m)
}
func (m *Chalin) XXX_DiscardUnknown() {
	xxx_messageInfo_Chalin.DiscardUnknown(m)
}

var xxx_messageInfo_Chalin proto.InternalMessageInfo

func (m *Chalin) GetCidin() map[string]*Cidin {
	if m != nil {
		return m.Cidin
	}
	return nil
}

func (m *Chalin) GetChalres() map[string]*Chalres {
	if m != nil {
		return m.Chalres
	}
	return nil
}

func (m *Chalin) GetMaxlength() uint32 {
	if m != nil {
		return m.Maxlength
	}
	return 0
}

type LedgerInfo struct {
	Chalinfo             map[string]*Chalin `protobuf:"bytes,1,rep,name=chalinfo,proto3" json:"chalinfo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LedgerInfo) Reset()         { *m = LedgerInfo{} }
func (m *LedgerInfo) String() string { return proto.CompactTextString(m) }
func (*LedgerInfo) ProtoMessage()    {}
func (*LedgerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4819ccc01c0c0a11, []int{3}
}

func (m *LedgerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LedgerInfo.Unmarshal(m, b)
}
func (m *LedgerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LedgerInfo.Marshal(b, m, deterministic)
}
func (m *LedgerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LedgerInfo.Merge(m, src)
}
func (m *LedgerInfo) XXX_Size() int {
	return xxx_messageInfo_LedgerInfo.Size(m)
}
func (m *LedgerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LedgerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LedgerInfo proto.InternalMessageInfo

func (m *LedgerInfo) GetChalinfo() map[string]*Chalin {
	if m != nil {
		return m.Chalinfo
	}
	return nil
}

type Cidin struct {
	Res                  bool     `protobuf:"varint,1,opt,name=Res,proto3" json:"Res,omitempty"`
	Repair               int32    `protobuf:"varint,2,opt,name=Repair,proto3" json:"Repair,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Avaltime             string   `protobuf:"bytes,4,opt,name=Avaltime,proto3" json:"Avaltime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cidin) Reset()         { *m = Cidin{} }
func (m *Cidin) String() string { return proto.CompactTextString(m) }
func (*Cidin) ProtoMessage()    {}
func (*Cidin) Descriptor() ([]byte, []int) {
	return fileDescriptor_4819ccc01c0c0a11, []int{4}
}

func (m *Cidin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cidin.Unmarshal(m, b)
}
func (m *Cidin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cidin.Marshal(b, m, deterministic)
}
func (m *Cidin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cidin.Merge(m, src)
}
func (m *Cidin) XXX_Size() int {
	return xxx_messageInfo_Cidin.Size(m)
}
func (m *Cidin) XXX_DiscardUnknown() {
	xxx_messageInfo_Cidin.DiscardUnknown(m)
}

var xxx_messageInfo_Cidin proto.InternalMessageInfo

func (m *Cidin) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

func (m *Cidin) GetRepair() int32 {
	if m != nil {
		return m.Repair
	}
	return 0
}

func (m *Cidin) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Cidin) GetAvaltime() string {
	if m != nil {
		return m.Avaltime
	}
	return ""
}

type Chalres struct {
	Keeper               string   `protobuf:"bytes,1,opt,name=Keeper,proto3" json:"Keeper,omitempty"`
	Provider             string   `protobuf:"bytes,2,opt,name=Provider,proto3" json:"Provider,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=User,proto3" json:"User,omitempty"`
	Sum                  uint32   `protobuf:"varint,4,opt,name=Sum,proto3" json:"Sum,omitempty"`
	Length               uint32   `protobuf:"varint,5,opt,name=Length,proto3" json:"Length,omitempty"`
	H                    int64    `protobuf:"varint,6,opt,name=H,proto3" json:"H,omitempty"`
	Res                  bool     `protobuf:"varint,7,opt,name=Res,proto3" json:"Res,omitempty"`
	Proof                string   `protobuf:"bytes,8,opt,name=Proof,proto3" json:"Proof,omitempty"`
	Seed                 string   `protobuf:"bytes,9,opt,name=Seed,proto3" json:"Seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chalres) Reset()         { *m = Chalres{} }
func (m *Chalres) String() string { return proto.CompactTextString(m) }
func (*Chalres) ProtoMessage()    {}
func (*Chalres) Descriptor() ([]byte, []int) {
	return fileDescriptor_4819ccc01c0c0a11, []int{5}
}

func (m *Chalres) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chalres.Unmarshal(m, b)
}
func (m *Chalres) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chalres.Marshal(b, m, deterministic)
}
func (m *Chalres) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chalres.Merge(m, src)
}
func (m *Chalres) XXX_Size() int {
	return xxx_messageInfo_Chalres.Size(m)
}
func (m *Chalres) XXX_DiscardUnknown() {
	xxx_messageInfo_Chalres.DiscardUnknown(m)
}

var xxx_messageInfo_Chalres proto.InternalMessageInfo

func (m *Chalres) GetKeeper() string {
	if m != nil {
		return m.Keeper
	}
	return ""
}

func (m *Chalres) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Chalres) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Chalres) GetSum() uint32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *Chalres) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Chalres) GetH() int64 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *Chalres) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

func (m *Chalres) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

func (m *Chalres) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

type Credit struct {
	Scores               map[string]uint32 `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Credit) Reset()         { *m = Credit{} }
func (m *Credit) String() string { return proto.CompactTextString(m) }
func (*Credit) ProtoMessage()    {}
func (*Credit) Descriptor() ([]byte, []int) {
	return fileDescriptor_4819ccc01c0c0a11, []int{6}
}

func (m *Credit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credit.Unmarshal(m, b)
}
func (m *Credit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credit.Marshal(b, m, deterministic)
}
func (m *Credit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credit.Merge(m, src)
}
func (m *Credit) XXX_Size() int {
	return xxx_messageInfo_Credit.Size(m)
}
func (m *Credit) XXX_DiscardUnknown() {
	xxx_messageInfo_Credit.DiscardUnknown(m)
}

var xxx_messageInfo_Credit proto.InternalMessageInfo

func (m *Credit) GetScores() map[string]uint32 {
	if m != nil {
		return m.Scores
	}
	return nil
}

func init() {
	proto.RegisterType((*Chalnum)(nil), "role.pb.chalnum")
	proto.RegisterType((*Pu)(nil), "role.pb.pu")
	proto.RegisterType((*Chalin)(nil), "role.pb.chalin")
	proto.RegisterMapType((map[string]*Chalres)(nil), "role.pb.chalin.ChalresEntry")
	proto.RegisterMapType((map[string]*Cidin)(nil), "role.pb.chalin.CidinEntry")
	proto.RegisterType((*LedgerInfo)(nil), "role.pb.LedgerInfo")
	proto.RegisterMapType((map[string]*Chalin)(nil), "role.pb.LedgerInfo.ChalinfoEntry")
	proto.RegisterType((*Cidin)(nil), "role.pb.cidin")
	proto.RegisterType((*Chalres)(nil), "role.pb.chalres")
	proto.RegisterType((*Credit)(nil), "role.pb.credit")
	proto.RegisterMapType((map[string]uint32)(nil), "role.pb.credit.ScoresEntry")
}

func init() { proto.RegisterFile("challenge.proto", fileDescriptor_4819ccc01c0c0a11) }

var fileDescriptor_4819ccc01c0c0a11 = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x5d, 0x6a, 0xdb, 0x40,
	0x10, 0x46, 0x52, 0x24, 0xd9, 0xe3, 0xb8, 0x09, 0x4b, 0x28, 0x8b, 0x9a, 0x07, 0x57, 0xb4, 0xc5,
	0x4f, 0xa2, 0x24, 0xa5, 0x7f, 0xd0, 0x87, 0x62, 0x0a, 0x0e, 0x35, 0xd4, 0xac, 0xe9, 0x01, 0x64,
	0x6b, 0x14, 0x8b, 0xca, 0x92, 0x58, 0x49, 0x26, 0x39, 0x4a, 0x6f, 0xd0, 0x8b, 0xf4, 0x5e, 0x65,
	0x67, 0x65, 0x4b, 0x6a, 0xdd, 0xb7, 0x99, 0x9d, 0x99, 0x6f, 0xbe, 0x99, 0xf9, 0x16, 0x2e, 0x36,
	0xdb, 0x30, 0x4d, 0x31, 0xbb, 0xc7, 0xa0, 0x90, 0x79, 0x95, 0x33, 0x57, 0xe6, 0x29, 0x06, 0xc5,
	0xda, 0x7f, 0x07, 0xae, 0x8a, 0x65, 0xf5, 0x8e, 0x31, 0x38, 0x5b, 0xd6, 0xeb, 0x19, 0x37, 0x26,
	0xc6, 0xd4, 0x12, 0x64, 0x33, 0x0e, 0xee, 0x5d, 0x16, 0x25, 0x1b, 0x2c, 0xb9, 0x39, 0xb1, 0xa6,
	0x43, 0x71, 0x70, 0xfd, 0x37, 0x60, 0x16, 0x35, 0xf3, 0x60, 0xb0, 0x94, 0xf9, 0x3e, 0x89, 0x50,
	0x52, 0xdd, 0x50, 0x1c, 0x7d, 0x85, 0xf7, 0xbd, 0x44, 0xc9, 0x4d, 0x7a, 0x27, 0xdb, 0xff, 0x65,
	0x82, 0xa3, 0xfa, 0x25, 0x19, 0x7b, 0x0d, 0xf6, 0x2c, 0x89, 0x92, 0x8c, 0x1b, 0x13, 0x6b, 0x3a,
	0xba, 0xf1, 0x82, 0x86, 0x52, 0xa0, 0xe3, 0x01, 0x05, 0xbf, 0x64, 0x95, 0x7c, 0x14, 0x3a, 0x91,
	0xbd, 0x05, 0x77, 0xb6, 0x0d, 0x53, 0xd9, 0x90, 0x19, 0xdd, 0x5c, 0xff, 0x53, 0xa3, 0xc3, 0xba,
	0xea, 0x90, 0xcc, 0xae, 0x61, 0xb8, 0x0b, 0x1f, 0xd4, 0xf8, 0xd5, 0x96, 0x5b, 0x13, 0x63, 0x3a,
	0x16, 0xed, 0x83, 0x37, 0x07, 0x68, 0x5b, 0xb1, 0x4b, 0xb0, 0x7e, 0xe0, 0x63, 0x33, 0x8b, 0x32,
	0xd9, 0x0b, 0xb0, 0xf7, 0x61, 0x5a, 0x23, 0xcd, 0x31, 0xba, 0x79, 0xd2, 0xf6, 0x54, 0x55, 0x42,
	0x07, 0x3f, 0x9a, 0xef, 0x0d, 0x6f, 0x01, 0xe7, 0x5d, 0x02, 0x27, 0xb0, 0x5e, 0xf5, 0xb1, 0x2e,
	0x7b, 0xfc, 0x25, 0x96, 0x1d, 0x34, 0xff, 0xa7, 0x01, 0xb0, 0xc0, 0xe8, 0x1e, 0xe5, 0x5d, 0x16,
	0xe7, 0xec, 0x13, 0x0c, 0xf4, 0x90, 0x71, 0xde, 0x6c, 0xec, 0xf9, 0xb1, 0xba, 0x4d, 0xa3, 0x0d,
	0xa8, 0x1c, 0xbd, 0x82, 0x63, 0x89, 0xb7, 0x80, 0x71, 0x2f, 0x74, 0x82, 0xdc, 0xcb, 0x3e, 0xb9,
	0x8b, 0xbf, 0x96, 0xdb, 0xe5, 0x86, 0x60, 0xd3, 0xf4, 0x0a, 0x45, 0x60, 0x49, 0x28, 0x03, 0xa1,
	0x4c, 0xf6, 0x14, 0x1c, 0x81, 0x45, 0x98, 0xe8, 0xbb, 0xdb, 0xa2, 0xf1, 0xd4, 0xfb, 0xb7, 0x38,
	0x2e, 0xb1, 0xa2, 0x0b, 0x58, 0xa2, 0xf1, 0x94, 0x82, 0x3e, 0xef, 0xc3, 0xb4, 0x4a, 0x76, 0xc8,
	0xcf, 0xb4, 0x82, 0x0e, 0xbe, 0xff, 0xdb, 0xd0, 0xea, 0x94, 0x1a, 0xf7, 0x2b, 0x62, 0x71, 0xd4,
	0x59, 0xe3, 0xf5, 0x14, 0x68, 0xfe, 0x47, 0x81, 0x56, 0xab, 0x40, 0xc5, 0x78, 0x55, 0xef, 0xa8,
	0xd5, 0x58, 0x28, 0x53, 0x21, 0x2f, 0xb4, 0x36, 0x6c, 0x7a, 0x6c, 0x3c, 0x76, 0x0e, 0xc6, 0x9c,
	0x3b, 0x44, 0xd6, 0x98, 0x1f, 0x26, 0x75, 0xdb, 0x49, 0xaf, 0xc0, 0x5e, 0xca, 0x3c, 0x8f, 0xf9,
	0x80, 0xe0, 0xb5, 0xa3, 0x7a, 0xae, 0x10, 0x23, 0x3e, 0xd4, 0x3d, 0x95, 0xed, 0x3f, 0x80, 0xb3,
	0x91, 0x18, 0x25, 0x15, 0xbb, 0x05, 0xa7, 0xdc, 0xe4, 0x92, 0x56, 0xa6, 0x6e, 0xf8, 0xac, 0x5d,
	0x32, 0x25, 0x04, 0x2b, 0x8a, 0xea, 0xeb, 0x35, 0xa9, 0xde, 0x07, 0x18, 0x75, 0x9e, 0x4f, 0x5c,
	0xee, 0xaa, 0x7b, 0xb9, 0x71, 0xe7, 0x50, 0x6b, 0x87, 0xbe, 0xfb, 0xed, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x88, 0x65, 0x49, 0x2d, 0x01, 0x04, 0x00, 0x00,
}
