// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userConfig.proto

package role_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserConfig struct {
	Params               string   `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	PubkeyBls            []byte   `protobuf:"bytes,2,opt,name=pubkeyBls,proto3" json:"pubkeyBls,omitempty"`
	PubkeyG              []byte   `protobuf:"bytes,3,opt,name=pubkeyG,proto3" json:"pubkeyG,omitempty"`
	PubkeyU              [][]byte `protobuf:"bytes,4,rep,name=pubkeyU,proto3" json:"pubkeyU,omitempty"`
	PrikeyBls            []byte   `protobuf:"bytes,5,opt,name=prikeyBls,proto3" json:"prikeyBls,omitempty"`
	X                    []byte   `protobuf:"bytes,6,opt,name=X,proto3" json:"X,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserConfig) Reset()         { *m = UserConfig{} }
func (m *UserConfig) String() string { return proto.CompactTextString(m) }
func (*UserConfig) ProtoMessage()    {}
func (*UserConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c81bc290ce0f7be, []int{0}
}

func (m *UserConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserConfig.Unmarshal(m, b)
}
func (m *UserConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserConfig.Marshal(b, m, deterministic)
}
func (m *UserConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserConfig.Merge(m, src)
}
func (m *UserConfig) XXX_Size() int {
	return xxx_messageInfo_UserConfig.Size(m)
}
func (m *UserConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_UserConfig.DiscardUnknown(m)
}

var xxx_messageInfo_UserConfig proto.InternalMessageInfo

func (m *UserConfig) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

func (m *UserConfig) GetPubkeyBls() []byte {
	if m != nil {
		return m.PubkeyBls
	}
	return nil
}

func (m *UserConfig) GetPubkeyG() []byte {
	if m != nil {
		return m.PubkeyG
	}
	return nil
}

func (m *UserConfig) GetPubkeyU() [][]byte {
	if m != nil {
		return m.PubkeyU
	}
	return nil
}

func (m *UserConfig) GetPrikeyBls() []byte {
	if m != nil {
		return m.PrikeyBls
	}
	return nil
}

func (m *UserConfig) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

type UserBLS12Config struct {
	PubkeyBls            []byte   `protobuf:"bytes,2,opt,name=pubkeyBls,proto3" json:"pubkeyBls,omitempty"`
	PubkeyG              []byte   `protobuf:"bytes,3,opt,name=pubkeyG,proto3" json:"pubkeyG,omitempty"`
	PubkeyU              [][]byte `protobuf:"bytes,4,rep,name=pubkeyU,proto3" json:"pubkeyU,omitempty"`
	PubkeyW              [][]byte `protobuf:"bytes,5,rep,name=pubkeyW,proto3" json:"pubkeyW,omitempty"`
	PrikeyBls            []byte   `protobuf:"bytes,6,opt,name=prikeyBls,proto3" json:"prikeyBls,omitempty"`
	X                    []byte   `protobuf:"bytes,7,opt,name=X,proto3" json:"X,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBLS12Config) Reset()         { *m = UserBLS12Config{} }
func (m *UserBLS12Config) String() string { return proto.CompactTextString(m) }
func (*UserBLS12Config) ProtoMessage()    {}
func (*UserBLS12Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c81bc290ce0f7be, []int{1}
}

func (m *UserBLS12Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBLS12Config.Unmarshal(m, b)
}
func (m *UserBLS12Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBLS12Config.Marshal(b, m, deterministic)
}
func (m *UserBLS12Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBLS12Config.Merge(m, src)
}
func (m *UserBLS12Config) XXX_Size() int {
	return xxx_messageInfo_UserBLS12Config.Size(m)
}
func (m *UserBLS12Config) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBLS12Config.DiscardUnknown(m)
}

var xxx_messageInfo_UserBLS12Config proto.InternalMessageInfo

func (m *UserBLS12Config) GetPubkeyBls() []byte {
	if m != nil {
		return m.PubkeyBls
	}
	return nil
}

func (m *UserBLS12Config) GetPubkeyG() []byte {
	if m != nil {
		return m.PubkeyG
	}
	return nil
}

func (m *UserBLS12Config) GetPubkeyU() [][]byte {
	if m != nil {
		return m.PubkeyU
	}
	return nil
}

func (m *UserBLS12Config) GetPubkeyW() [][]byte {
	if m != nil {
		return m.PubkeyW
	}
	return nil
}

func (m *UserBLS12Config) GetPrikeyBls() []byte {
	if m != nil {
		return m.PrikeyBls
	}
	return nil
}

func (m *UserBLS12Config) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func init() {
	proto.RegisterType((*UserConfig)(nil), "role.pb.UserConfig")
	proto.RegisterType((*UserBLS12Config)(nil), "role.pb.UserBLS12Config")
}

func init() { proto.RegisterFile("userConfig.proto", fileDescriptor_1c81bc290ce0f7be) }

var fileDescriptor_1c81bc290ce0f7be = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2d, 0x4e, 0x2d,
	0x72, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0xca,
	0xcf, 0x49, 0xd5, 0x2b, 0x48, 0x52, 0x5a, 0xc4, 0xc8, 0xc5, 0x15, 0x0a, 0x97, 0x15, 0x12, 0xe3,
	0x62, 0x2b, 0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2,
	0x84, 0x64, 0xb8, 0x38, 0x0b, 0x4a, 0x93, 0xb2, 0x53, 0x2b, 0x9d, 0x72, 0x8a, 0x25, 0x98, 0x14,
	0x18, 0x35, 0x78, 0x82, 0x10, 0x02, 0x42, 0x12, 0x5c, 0xec, 0x10, 0x8e, 0xbb, 0x04, 0x33, 0x58,
	0x0e, 0xc6, 0x45, 0xc8, 0x84, 0x4a, 0xb0, 0x28, 0x30, 0x23, 0x64, 0x42, 0xc1, 0x26, 0x16, 0x65,
	0x42, 0x4d, 0x64, 0x85, 0x9a, 0x08, 0x13, 0x10, 0xe2, 0xe1, 0x62, 0x8c, 0x90, 0x60, 0x03, 0x8b,
	0x32, 0x46, 0x28, 0xad, 0x64, 0xe4, 0xe2, 0x07, 0x39, 0xd2, 0xc9, 0x27, 0xd8, 0xd0, 0x08, 0xea,
	0x52, 0xea, 0xbb, 0x08, 0x2e, 0x13, 0x2e, 0xc1, 0x8a, 0x2c, 0x13, 0x8e, 0xea, 0x56, 0x36, 0xac,
	0x6e, 0x65, 0x87, 0xba, 0x35, 0x89, 0x0d, 0x1c, 0xc0, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x72, 0xc6, 0x69, 0x95, 0x74, 0x01, 0x00, 0x00,
}
