// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockCheck.proto

package blocks_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RawData struct {
	CheckSize            int32    `protobuf:"varint,1,opt,name=checkSize,proto3" json:"checkSize,omitempty"`
	Flag                 int32    `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
	Segments             [][]byte `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	Tag                  [][]byte `protobuf:"bytes,4,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawData) Reset()         { *m = RawData{} }
func (m *RawData) String() string { return proto.CompactTextString(m) }
func (*RawData) ProtoMessage()    {}
func (*RawData) Descriptor() ([]byte, []int) {
	return fileDescriptor_98643308f4c70849, []int{0}
}

func (m *RawData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawData.Unmarshal(m, b)
}
func (m *RawData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawData.Marshal(b, m, deterministic)
}
func (m *RawData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawData.Merge(m, src)
}
func (m *RawData) XXX_Size() int {
	return xxx_messageInfo_RawData.Size(m)
}
func (m *RawData) XXX_DiscardUnknown() {
	xxx_messageInfo_RawData.DiscardUnknown(m)
}

var xxx_messageInfo_RawData proto.InternalMessageInfo

func (m *RawData) GetCheckSize() int32 {
	if m != nil {
		return m.CheckSize
	}
	return 0
}

func (m *RawData) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *RawData) GetSegments() [][]byte {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *RawData) GetTag() [][]byte {
	if m != nil {
		return m.Tag
	}
	return nil
}

func init() {
	proto.RegisterType((*RawData)(nil), "blocks.pb.RawData")
}

func init() { proto.RegisterFile("blockCheck.proto", fileDescriptor_98643308f4c70849) }

var fileDescriptor_98643308f4c70849 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xca, 0xc9, 0x4f,
	0xce, 0x76, 0xce, 0x48, 0x4d, 0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x8b,
	0x14, 0xeb, 0x15, 0x24, 0x29, 0x65, 0x72, 0xb1, 0x07, 0x25, 0x96, 0xbb, 0x24, 0x96, 0x24, 0x0a,
	0xc9, 0x70, 0x71, 0x26, 0x83, 0x14, 0x05, 0x67, 0x56, 0xa5, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0,
	0x06, 0x21, 0x04, 0x84, 0x84, 0xb8, 0x58, 0xd2, 0x72, 0x12, 0xd3, 0x25, 0x98, 0xc0, 0x12, 0x60,
	0xb6, 0x90, 0x14, 0x17, 0x47, 0x71, 0x6a, 0x7a, 0x6e, 0x6a, 0x5e, 0x49, 0xb1, 0x04, 0xb3, 0x02,
	0xb3, 0x06, 0x4f, 0x10, 0x9c, 0x2f, 0x24, 0xc0, 0xc5, 0x5c, 0x92, 0x98, 0x2e, 0xc1, 0x02, 0x16,
	0x06, 0x31, 0x93, 0xd8, 0xc0, 0x96, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa9, 0x1b, 0x32,
	0x3f, 0x90, 0x00, 0x00, 0x00,
}
