// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: block.proto

package block_pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Prefix struct {
	Policy      int32 `protobuf:"varint,1,opt,name=Policy,proto3" json:"Policy,omitempty"`
	TagSize     int32 `protobuf:"varint,2,opt,name=TagSize,proto3" json:"TagSize,omitempty"`
	SegmentSize int32 `protobuf:"varint,3,opt,name=SegmentSize,proto3" json:"SegmentSize,omitempty"`
	DataCount   int32 `protobuf:"varint,4,opt,name=DataCount,proto3" json:"DataCount,omitempty"`
	ParityCount int32 `protobuf:"varint,5,opt,name=ParityCount,proto3" json:"ParityCount,omitempty"`
	// number of segments
	Length               int32    `protobuf:"varint,6,opt,name=Length,proto3" json:"Length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prefix) Reset()         { *m = Prefix{} }
func (m *Prefix) String() string { return proto.CompactTextString(m) }
func (*Prefix) ProtoMessage()    {}
func (*Prefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}
func (m *Prefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prefix.Unmarshal(m, b)
}
func (m *Prefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prefix.Marshal(b, m, deterministic)
}
func (m *Prefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prefix.Merge(m, src)
}
func (m *Prefix) XXX_Size() int {
	return xxx_messageInfo_Prefix.Size(m)
}
func (m *Prefix) XXX_DiscardUnknown() {
	xxx_messageInfo_Prefix.DiscardUnknown(m)
}

var xxx_messageInfo_Prefix proto.InternalMessageInfo

func (m *Prefix) GetPolicy() int32 {
	if m != nil {
		return m.Policy
	}
	return 0
}

func (m *Prefix) GetTagSize() int32 {
	if m != nil {
		return m.TagSize
	}
	return 0
}

func (m *Prefix) GetSegmentSize() int32 {
	if m != nil {
		return m.SegmentSize
	}
	return 0
}

func (m *Prefix) GetDataCount() int32 {
	if m != nil {
		return m.DataCount
	}
	return 0
}

func (m *Prefix) GetParityCount() int32 {
	if m != nil {
		return m.ParityCount
	}
	return 0
}

func (m *Prefix) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func init() {
	proto.RegisterType((*Prefix)(nil), "block.pb.Prefix")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d) }

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xca, 0xc9, 0x4f,
	0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x72, 0x92, 0x94, 0xb6, 0x30, 0x72,
	0xb1, 0x05, 0x14, 0xa5, 0xa6, 0x65, 0x56, 0x08, 0x89, 0x71, 0xb1, 0x05, 0xe4, 0xe7, 0x64, 0x26,
	0x57, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x79, 0x42, 0x12, 0x5c, 0xec, 0x21, 0x89,
	0xe9, 0xc1, 0x99, 0x55, 0xa9, 0x12, 0x4c, 0x60, 0x09, 0x18, 0x57, 0x48, 0x81, 0x8b, 0x3b, 0x38,
	0x35, 0x3d, 0x37, 0x35, 0xaf, 0x04, 0x2c, 0xcb, 0x0c, 0x96, 0x45, 0x16, 0x12, 0x92, 0xe1, 0xe2,
	0x74, 0x49, 0x2c, 0x49, 0x74, 0xce, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x01, 0xcb, 0x23, 0x04, 0x40,
	0xfa, 0x03, 0x12, 0x8b, 0x32, 0x4b, 0x2a, 0x21, 0xf2, 0xac, 0x10, 0xfd, 0x48, 0x42, 0x20, 0x37,
	0xf9, 0xa4, 0xe6, 0xa5, 0x97, 0x64, 0x48, 0xb0, 0x41, 0xdc, 0x04, 0xe1, 0x25, 0xb1, 0x81, 0xfd,
	0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x37, 0xdb, 0xe4, 0xf9, 0xd6, 0x00, 0x00, 0x00,
}
